import type { KaiwaScene } from '../../types'

export const scene: KaiwaScene = {
  id: 'tour-airport',
  category: 'tourism',
  title: '機場',
  titleJa: '空港で',
  icon: '✈️',
  suggestedLevel: 'n5',
  dialogues: [
    {
      id: 'tour-airport-d1',
      title: '報到劃位',
      lines: [
        {
          speaker: '職員',
          gender: '女',
          ja: 'おはようございます。パスポートをお願いします。',
          reading: 'おはようございます。パスポートを おねがいします。',
          zh: '早安。麻煩出示您的護照。',
        },
        {
          speaker: '旅客',
          gender: '男',
          ja: 'はい、どうぞ。台北行きです。',
          reading: 'はい、どうぞ。タイペイゆきです。',
          zh: '好的，請看。我是要飛台北的。',
        },
        {
          speaker: '職員',
          gender: '女',
          ja: 'お荷物はいくつですか。',
          reading: 'おにもつは いくつですか。',
          zh: '您有幾件行李呢？',
        },
        {
          speaker: '旅客',
          gender: '男',
          ja: 'スーツケースが一つです。',
          reading: 'スーツケースが ひとつです。',
          zh: '一個行李箱。',
        },
        {
          speaker: '職員',
          gender: '女',
          ja: 'こちらに乗せてください。お席は窓側と通路側、どちらがいいですか。',
          reading: 'こちらに のせてください。おせきは まどがわと つうろがわ、どちらが いいですか。',
          zh: '請放到這上面。座位要靠窗還是靠走道呢？',
        },
        {
          speaker: '旅客',
          gender: '男',
          ja: '窓側をお願いします。',
          reading: 'まどがわを おねがいします。',
          zh: '麻煩給我靠窗的。',
        },
        {
          speaker: '職員',
          gender: '女',
          ja: 'かしこまりました。こちらが搭乗券です。搭乗口は25番です。',
          reading: 'かしこまりました。こちらが とうじょうけんです。とうじょうぐちは にじゅうごばんです。',
          zh: '好的。這是您的登機證，登機門是25號。',
        },
        {
          speaker: '旅客',
          gender: '男',
          ja: 'ありがとうございます。搭乗は何時からですか。',
          reading: 'ありがとうございます。とうじょうは なんじからですか。',
          zh: '謝謝。幾點開始登機呢？',
        },
        {
          speaker: '職員',
          gender: '女',
          ja: '10時半からです。よいご旅行を。',
          reading: 'じゅうじはんからです。よい ごりょこうを。',
          zh: '十點半開始。祝您旅途愉快。',
        },
      ],
    },
    {
      id: 'tour-airport-d2',
      title: '過安檢、問登機門',
      lines: [
        {
          speaker: '係員',
          gender: '男',
          ja: 'ポケットの中の物を全部トレーに出してください。',
          reading: 'ポケットの なかの ものを ぜんぶ トレーに だしてください。',
          zh: '請把口袋裡的東西全部放到托盤上。',
        },
        {
          speaker: '旅客',
          gender: '女',
          ja: '携帯電話もですか。',
          reading: 'けいたいでんわもですか。',
          zh: '手機也要嗎？',
        },
        {
          speaker: '係員',
          gender: '男',
          ja: 'はい。パソコンはかばんから出してください。',
          reading: 'はい。パソコンは かばんから だしてください。',
          zh: '是的。筆電請從包包裡拿出來。',
        },
        {
          speaker: '旅客',
          gender: '女',
          ja: 'ペットボトルの水はだめですか。',
          reading: 'ペットボトルの みずは だめですか。',
          zh: '保特瓶的水不行嗎？',
        },
        {
          speaker: '係員',
          gender: '男',
          ja: 'すみませんが、飲み物はここで捨ててください。',
          reading: 'すみませんが、のみものは ここで すててください。',
          zh: '不好意思，飲料請在這裡丟掉。',
        },
        {
          speaker: '旅客',
          gender: '女',
          ja: 'わかりました。あのう、25番搭乗口はどこですか。',
          reading: 'わかりました。あのう、にじゅうごばん とうじょうぐちは どこですか。',
          zh: '我知道了。請問，25號登機門在哪裡？',
        },
        {
          speaker: '係員',
          gender: '男',
          ja: 'この先をまっすぐ行って、右に曲がってください。',
          reading: 'このさきを まっすぐ いって、みぎに まがってください。',
          zh: '往前直走，然後右轉。',
        },
        {
          speaker: '旅客',
          gender: '女',
          ja: 'どのぐらいかかりますか。',
          zh: '大概要走多久呢？',
        },
        {
          speaker: '係員',
          gender: '男',
          ja: '歩いて五分ぐらいですよ。',
          reading: 'あるいて ごふんぐらいですよ。',
          zh: '走路大約五分鐘喔。',
        },
        {
          speaker: '旅客',
          gender: '女',
          ja: 'ありがとうございました。',
          zh: '謝謝您。',
        },
      ],
    },
    {
      id: 'tour-airport-d3',
      title: '行李遺失詢問',
      lines: [
        {
          speaker: '旅客',
          gender: '男',
          ja: 'すみません。荷物が出てきません。',
          reading: 'すみません。にもつが でてきません。',
          zh: '不好意思，我的行李沒有出來。',
        },
        {
          speaker: '係員',
          gender: '女',
          ja: '申し訳ございません。便名を教えてください。',
          reading: 'もうしわけございません。びんめいを おしえてください。',
          zh: '非常抱歉。請告訴我您的航班編號。',
        },
        {
          speaker: '旅客',
          gender: '男',
          ja: 'JL809便です。これが荷物のタグです。',
          reading: 'ジェーエルはちまるきゅうびんです。これが にもつの タグです。',
          zh: 'JL809航班。這是我的行李條。',
        },
        {
          speaker: '係員',
          gender: '女',
          ja: 'ありがとうございます。どんなスーツケースですか。',
          zh: '謝謝。是什麼樣的行李箱呢？',
        },
        {
          speaker: '旅客',
          gender: '男',
          ja: '青くて、大きいスーツケースです。',
          reading: 'あおくて、おおきい スーツケースです。',
          zh: '是藍色的大行李箱。',
        },
        {
          speaker: '係員',
          gender: '女',
          ja: '少々お待ちください。今調べます。',
          reading: 'しょうしょう おまちください。いま しらべます。',
          zh: '請稍等，我現在查一下。',
        },
        {
          speaker: '係員',
          gender: '女',
          ja: 'お客様のお荷物は次の便で着きます。',
          reading: 'おきゃくさまの おにもつは つぎの びんで つきます。',
          zh: '您的行李會搭下一班飛機抵達。',
        },
        {
          speaker: '旅客',
          gender: '男',
          ja: 'そうですか。ホテルに送ってもらえますか。',
          reading: 'そうですか。ホテルに おくって もらえますか。',
          zh: '這樣啊。可以幫我送到飯店嗎？',
        },
        {
          speaker: '係員',
          gender: '女',
          ja: 'はい、大丈夫です。こちらの紙にホテルの名前を書いてください。',
          reading: 'はい、だいじょうぶです。こちらの かみに ホテルの なまえを かいてください。',
          zh: '可以的。請在這張單子上寫下飯店名稱。',
        },
        {
          speaker: '旅客',
          gender: '男',
          ja: 'わかりました。よろしくお願いします。',
          reading: 'わかりました。よろしく おねがいします。',
          zh: '我知道了，麻煩您了。',
        },
      ],
    },
  ],
  phrases: [
    {
      ja: 'チェックインをお願いします。',
      reading: 'チェックインを おねがいします。',
      zh: '麻煩幫我辦理報到。',
    },
    {
      ja: '窓側の席をお願いします。',
      reading: 'まどがわの せきを おねがいします。',
      zh: '請給我靠窗的座位。',
      note: '靠走道是「通路側（つうろがわ）」。',
    },
    {
      ja: '荷物を預けたいです。',
      reading: 'にもつを あずけたいです。',
      zh: '我想託運行李。',
    },
    {
      ja: '搭乗口はどこですか。',
      reading: 'とうじょうぐちは どこですか。',
      zh: '登機門在哪裡？',
    },
    {
      ja: '搭乗は何時からですか。',
      reading: 'とうじょうは なんじからですか。',
      zh: '幾點開始登機？',
    },
    {
      ja: '荷物が出てきません。',
      reading: 'にもつが でてきません。',
      zh: '我的行李沒有出來。',
      note: '到「手荷物カウンター」出示行李條（タグ）詢問。',
    },
    {
      ja: '両替はどこでできますか。',
      reading: 'りょうがえは どこで できますか。',
      zh: '哪裡可以換錢？',
    },
    {
      ja: '免税店はどこですか。',
      reading: 'めんぜいてんは どこですか。',
      zh: '免稅店在哪裡？',
    },
    {
      ja: 'この便は遅れていますか。',
      reading: 'このびんは おくれていますか。',
      zh: '這班飛機誤點了嗎？',
    },
    {
      ja: 'もう一度言ってください。',
      reading: 'もういちど いってください。',
      zh: '請再說一次。',
      note: '聽不懂廣播或對方講太快時的救命句。',
    },
    {
      ja: 'Wi-Fiはありますか。',
      reading: 'ワイファイは ありますか。',
      zh: '有Wi-Fi嗎？',
    },
    {
      ja: 'タクシー乗り場はどこですか。',
      reading: 'タクシーのりばは どこですか。',
      zh: '計程車招呼站在哪裡？',
    },
  ],
  drills: [
    {
      kind: 'choice',
      id: 'tour-airport-001',
      stem: '窓側の 席（　）お願いします。',
      options: ['を', 'に', 'で', 'が'],
      answerIndex: 0,
      explanation:
        '「名詞＋をお願いします」是點餐、劃位等場合請對方提供某物的固定句型，助詞用「を」。「に」表示對象或方向、「で」表示地點或手段，放在這裡都不合文法；「が」是主格助詞，和「お願いします」搭配不起來。',
      explanationEn:
        '「名詞＋をお願いします」 is the set pattern for requesting something — ordering food, choosing a seat, and so on — and the particle it takes is 「を」. 「に」 marks a target or direction and 「で」 marks a place or means, so neither fits grammatically here; 「が」 is the subject marker and simply does not combine with 「お願いします」.',
    },
    {
      kind: 'choice',
      id: 'tour-airport-002',
      stem: '荷物を （　）たいです。',
      options: ['預け', '預かり', '預ける', '預かる'],
      answerIndex: 0,
      explanation:
        '「〜たいです」要接在ます形語幹後面：「預けます」去掉「ます」變成「預け」，所以是「預けたいです」（我想託運）。「預ける」是辭書形，不能直接接「たい」；「預かる／預かり」是「替別人保管」，主詞方向相反，旅客託運行李不能用。',
      explanationEn:
        '「〜たいです」 attaches to the masu-stem: drop 「ます」 from 「預けます」 to get 「預け」, giving 「預けたいです」 (I want to check my luggage). 「預ける」 is the dictionary form and cannot take 「たい」 directly; 「預かる／預かり」 mean "to keep something for someone else" — the roles are reversed, so a passenger checking in luggage cannot use them.',
    },
    {
      kind: 'choice',
      id: 'tour-airport-003',
      stem: 'すみません、搭乗口（　）どこですか。',
      options: ['は', 'を', 'へ', 'と'],
      answerIndex: 0,
      explanation:
        '「〜はどこですか」是詢問地點的基本句型，用主題助詞「は」提示要問的東西。「を」用來標示他動詞的受詞，這句沒有他動詞；「へ」表示移動方向，後面要接「行きます」等移動動詞；「と」是並列助詞，放在這裡語意不通。',
      explanationEn:
        '「〜はどこですか」 is the basic pattern for asking where something is, with the topic particle 「は」 marking the thing you are asking about. 「を」 marks the object of a transitive verb, and there is no transitive verb in this sentence; 「へ」 indicates direction of movement and needs a motion verb like 「行きます」 after it; 「と」 is the linking particle "and," which makes no sense here.',
    },
    {
      kind: 'choice',
      id: 'tour-airport-004',
      stem: '飲み物は ここで （　）ください。',
      options: ['捨てて', '捨って', '捨てる', '捨て'],
      answerIndex: 0,
      explanation:
        '「〜てください」表示請求，前面要接動詞て形。「捨てます」是二類動詞，て形直接把「る」換成「て」，變成「捨てて」。「捨って」是誤把它當成一類動詞做促音便的錯誤形；「捨てる」是辭書形、「捨て」是ます形語幹，都不能直接接「ください」。',
      explanationEn:
        '「〜てください」 expresses a request and must follow the te-form of the verb. 「捨てる」 is a group 2 (ichidan) verb, so its te-form simply replaces 「る」 with 「て」, giving 「捨てて」. 「捨って」 is a mistaken form created by treating it as a group 1 verb with a double-consonant sound change; 「捨てる」 is the dictionary form and 「捨て」 is the masu-stem — neither can attach directly to 「ください」.',
    },
    {
      kind: 'order',
      id: 'tour-airport-005',
      before: 'この 紙に ',
      after: '。',
      segments: ['ホテルの', '名前を', '書いて', 'ください'],
      starIndex: 2,
      explanation:
        '正解語序是「この紙にホテルの名前を書いてください」。「ホテルの」是修飾「名前」的連體修飾語，必須緊接在「名前を」前面；「書いてください」是「て形＋ください」的請求句型，「書いて」後面只能接「ください」，所以整句只有一種自然語序，★處是「書いて」。',
      explanationEn:
        'The correct order is 「この紙にホテルの名前を書いてください」. 「ホテルの」 modifies 「名前」 and must come immediately before 「名前を」; 「書いてください」 is the te-form plus 「ください」 request pattern, so 「書いて」 can only be followed by 「ください」. That leaves exactly one natural word order, and the starred slot is 「書いて」.',
    },
    {
      kind: 'order',
      id: 'tour-airport-006',
      before: '搭乗口まで ',
      after: 'よ。',
      segments: ['歩いて', '五分', 'ぐらい', 'です'],
      starIndex: 1,
      explanation:
        '正解語序是「搭乗口まで歩いて五分ぐらいですよ」。「歩いて」表示移動手段，要放在所需的花費之前；「ぐらい」表示大約，必須緊接在數量「五分」後面，句尾再接「です」。若把「歩いて」移到「五分ぐらい」之後就不成句了。★處是「五分」。',
      explanationEn:
        'The correct order is 「搭乗口まで歩いて五分ぐらいですよ」. 「歩いて」 expresses the means of movement (on foot) and comes before the time it takes; 「ぐらい」 means "about" and must directly follow the quantity 「五分」, with 「です」 closing the sentence. Moving 「歩いて」 after 「五分ぐらい」 would break the sentence. The starred slot is 「五分」.',
    },
  ],
}
