import type { KaiwaScene } from '../../types'

export const scene: KaiwaScene = {
  id: 'tour-transport',
  category: 'tourism',
  title: '搭車交通',
  titleJa: '電車・バスに乗る',
  icon: '🚃',
  suggestedLevel: 'n4',
  dialogues: [
    {
      id: 'tour-transport-d1',
      title: '買票與問月台',
      lines: [
        {
          speaker: '旅客',
          gender: '男',
          ja: 'すみません、京都までの切符を買いたいんですが。',
          reading: 'すみません、きょうとまでのきっぷをかいたいんですが。',
          zh: '不好意思，我想買到京都的車票。',
        },
        {
          speaker: '駅員',
          gender: '女',
          ja: '新幹線ですか、普通の電車ですか。',
          reading: 'しんかんせんですか、ふつうのでんしゃですか。',
          zh: '是新幹線，還是普通電車呢？',
        },
        {
          speaker: '旅客',
          gender: '男',
          ja: '普通の電車でお願いします。いくらですか。',
          reading: 'ふつうのでんしゃでおねがいします。いくらですか。',
          zh: '麻煩給我普通電車的票。多少錢呢？',
        },
        {
          speaker: '駅員',
          gender: '女',
          ja: '九百六十円になります。',
          reading: 'きゅうひゃくろくじゅうえんになります。',
          zh: '一共是960日圓。',
        },
        {
          speaker: '旅客',
          gender: '男',
          ja: 'じゃあ、これでお願いします。京都行きは何番線から出ますか。',
          reading: 'じゃあ、これでおねがいします。きょうとゆきはなんばんせんからでますか。',
          zh: '那麻煩用這個付。往京都的車從幾號月台發車呢？',
        },
        {
          speaker: '駅員',
          gender: '女',
          ja: '五番線です。次の電車は十時十五分に出ます。',
          reading: 'ごばんせんです。つぎのでんしゃはじゅうじじゅうごふんにでます。',
          zh: '5號月台。下一班電車10點15分發車。',
        },
        {
          speaker: '旅客',
          gender: '男',
          ja: '途中で乗り換えは要りますか。',
          reading: 'とちゅうでのりかえはいりますか。',
          zh: '中途需要轉車嗎？',
        },
        {
          speaker: '駅員',
          gender: '女',
          ja: 'いいえ、乗り換えなしで行けますよ。',
          reading: 'いいえ、のりかえなしでいけますよ。',
          zh: '不用，不需要轉車就能到喔。',
        },
      ],
    },
    {
      id: 'tour-transport-d2',
      title: '車內詢問與讓座',
      lines: [
        {
          speaker: '旅客',
          gender: '女',
          ja: 'すみません、この電車は大阪駅に止まりますか。',
          reading: 'すみません、このでんしゃはおおさかえきにとまりますか。',
          zh: '不好意思，這班電車有停大阪車站嗎？',
        },
        {
          speaker: '乗客',
          gender: '男',
          ja: 'はい、止まりますよ。ここから三つ目です。',
          reading: 'はい、とまりますよ。ここからみっつめです。',
          zh: '有，會停喔。從這裡數第三站。',
        },
        {
          speaker: '旅客',
          gender: '女',
          ja: 'よかった。着いたら教えていただけませんか。',
          reading: 'よかった。ついたらおしえていただけませんか。',
          zh: '太好了。到站時可以告訴我一聲嗎？',
        },
        {
          speaker: '乗客',
          gender: '男',
          ja: 'いいですよ。私も同じ駅で降りますから。',
          reading: 'いいですよ。わたしもおなじえきでおりますから。',
          zh: '好啊，我也在同一站下車。',
        },
        {
          speaker: '旅客',
          gender: '女',
          ja: 'あ、おばあさんが乗ってきました。席を譲りましょう。',
          reading: 'あ、おばあさんがのってきました。せきをゆずりましょう。',
          zh: '啊，有位老奶奶上車了。讓個座吧。',
        },
        {
          speaker: '旅客',
          gender: '女',
          ja: 'すみません、よかったらこの席にどうぞ。',
          reading: 'すみません、よかったらこのせきにどうぞ。',
          zh: '不好意思，不介意的話請坐這個位子。',
        },
        {
          speaker: 'おばあさん',
          gender: '女',
          ja: 'まあ、ご親切にありがとうございます。',
          reading: 'まあ、ごしんせつにありがとうございます。',
          zh: '哎呀，謝謝你這麼親切。',
        },
        {
          speaker: '旅客',
          gender: '女',
          ja: 'いいえ、どうぞ座ってください。',
          reading: 'いいえ、どうぞすわってください。',
          zh: '不會，請坐。',
        },
        {
          speaker: '乗客',
          gender: '男',
          ja: 'もうすぐ大阪駅ですよ。降りる準備をしましょう。',
          reading: 'もうすぐおおさかえきですよ。おりるじゅんびをしましょう。',
          zh: '快到大阪車站了喔，我們準備下車吧。',
        },
        {
          speaker: '旅客',
          gender: '女',
          ja: '教えてくださって、ありがとうございました。',
          reading: 'おしえてくださって、ありがとうございました。',
          zh: '謝謝您告訴我。',
        },
      ],
    },
    {
      id: 'tour-transport-d3',
      title: '搭計程車報地點',
      lines: [
        {
          speaker: '運転手',
          gender: '男',
          ja: 'いらっしゃいませ。どちらまでですか。',
          zh: '歡迎搭車。請問要到哪裡呢？',
        },
        {
          speaker: '客',
          gender: '女',
          ja: '浅草寺までお願いします。',
          reading: 'せんそうじまでおねがいします。',
          zh: '麻煩到淺草寺。',
        },
        {
          speaker: '運転手',
          gender: '男',
          ja: 'かしこまりました。だいたい二十分ぐらいかかりますが、よろしいですか。',
          reading: 'かしこまりました。だいたいにじゅっぷんぐらいかかりますが、よろしいですか。',
          zh: '好的。大概要花20分鐘左右，可以嗎？',
        },
        {
          speaker: '客',
          gender: '女',
          ja: 'はい、大丈夫です。料金はいくらぐらいですか。',
          reading: 'はい、だいじょうぶです。りょうきんはいくらぐらいですか。',
          zh: '好，沒問題。車資大概多少錢呢？',
        },
        {
          speaker: '運転手',
          gender: '男',
          ja: '道が込んでいなければ、二千円ぐらいですね。',
          reading: 'みちがこんでいなければ、にせんえんぐらいですね。',
          zh: '如果路上不塞車的話，大概2000日圓左右。',
        },
        {
          speaker: '客',
          gender: '女',
          ja: 'じゃあ、お願いします。入口の近くで降ろしてもらえますか。',
          reading: 'じゃあ、おねがいします。いりぐちのちかくでおろしてもらえますか。',
          zh: '那就麻煩你了。可以讓我在入口附近下車嗎？',
        },
        {
          speaker: '運転手',
          gender: '男',
          ja: 'はい、雷門の前に止めますね。',
          reading: 'はい、かみなりもんのまえにとめますね。',
          zh: '好的，我停在雷門前面。',
        },
        {
          speaker: '客',
          gender: '女',
          ja: '助かります。カードで払えますか。',
          reading: 'たすかります。カードではらえますか。',
          zh: '太感謝了。可以刷卡嗎？',
        },
        {
          speaker: '運転手',
          gender: '男',
          ja: 'はい、使えますよ。着いたらお知らせします。',
          reading: 'はい、つかえますよ。ついたらおしらせします。',
          zh: '可以喔。到了我再告訴您。',
        },
      ],
    },
  ],
  phrases: [
    {
      ja: 'ICカードにチャージしたいんですが。',
      reading: 'アイシーカードにチャージしたいんですが。',
      zh: '我想幫IC卡加值。',
      note: '加值日文說「チャージ」；在車站的加值機上找這個按鈕就對了。',
    },
    {
      ja: '終電は何時ですか。',
      reading: 'しゅうでんはなんじですか。',
      zh: '末班電車是幾點？',
      note: '「終電」專指電車；末班公車叫「最終バス」。',
    },
    {
      ja: '渋谷までいくらですか。',
      reading: 'しぶやまでいくらですか。',
      zh: '到澀谷要多少錢？',
    },
    {
      ja: 'どこで乗り換えればいいですか。',
      reading: 'どこでのりかえればいいですか。',
      zh: '我該在哪裡轉車呢？',
    },
    {
      ja: 'この電車は急行ですか、各駅停車ですか。',
      reading: 'このでんしゃはきゅうこうですか、かくえきていしゃですか。',
      zh: '這班是快車，還是每站都停的普通車？',
      note: '急行、特急不停小站，上車前先確認要去的站會不會停。',
    },
    {
      ja: '次のバスは何時に来ますか。',
      reading: 'つぎのバスはなんじにきますか。',
      zh: '下一班公車幾點來？',
    },
    {
      ja: '切符売り場はどこですか。',
      reading: 'きっぷうりばはどこですか。',
      zh: '售票處在哪裡？',
    },
    {
      ja: '空港行きのバス乗り場はどこですか。',
      reading: 'くうこうゆきのバスのりばはどこですか。',
      zh: '往機場的公車乘車處在哪裡？',
    },
    {
      ja: '乗り越してしまったので、精算したいんですが。',
      reading: 'のりこしてしまったので、せいさんしたいんですが。',
      zh: '我坐過站了，想補票。',
      note: '出站前用「乗り越し精算機」補差額即可，不用重買一張票。',
    },
    {
      ja: '一日乗車券はありますか。',
      reading: 'いちにちじょうしゃけんはありますか。',
      zh: '有一日乘車券嗎？',
    },
    {
      ja: '終点まで行きますか。',
      reading: 'しゅうてんまでいきますか。',
      zh: '這班車有到終點站嗎？',
    },
    {
      ja: '次で降ります。',
      reading: 'つぎでおります。',
      zh: '我下一站下車。',
      note: '日本公車下車前要按「降車ボタン」，車停穩了再離開座位。',
    },
  ],
  drills: [
    {
      kind: 'choice',
      id: 'tour-transport-001',
      stem: 'すみません、駅に 着いたら 教えて（　）ませんか。',
      options: ['いただけ', 'さしあげ', 'くださり', 'いたし'],
      answerIndex: 0,
      explanation:
        '「動詞て形＋いただけませんか」是客氣地請對方為自己做某事的固定句型，「いただける」是「もらう」的謙讓語可能形，直譯是「能否請您告訴我」。「さしあげ」方向相反，變成我為對方做事；「くださり」形態有誤，正確說法是「くださいませんか」。',
      explanationEn:
        'Te-form + 「いただけませんか」 is the polite set pattern for asking someone to do something for you; 「いただける」 is the potential form of the humble verb for receiving, so the sentence means "could you possibly tell me (when we reach the station)?" 「さしあげ」 points the favor the wrong way — you doing something for the other person; 「くださり」 is the wrong shape here — the correct alternative would be 「くださいませんか」.',
    },
    {
      kind: 'choice',
      id: 'tour-transport-002',
      stem: 'この 電車は 上野駅に（　）か。',
      options: ['止まります', '止めます', '止まらせます', '止めています'],
      answerIndex: 0,
      explanation:
        '「止まる」是自動詞，表示電車自己停靠，詢問「這班電車停不停某站」要說「〜に止まりますか」。「止める」是他動詞，指把某物停住，需要用「を」標示受詞，放在這裡文法不合；「止まらせます」是使役形，語意變成「讓電車停下」，不是乘客詢問的語氣。',
      explanationEn:
        '「止まる」 is intransitive — the train stops on its own — so asking whether this train stops at a station is 「〜に止まりますか」. 「止める」 is transitive, meaning to bring something to a stop, and would need an object marked with 「を」, so it does not fit grammatically; 「止まらせます」 is the causative, "to make the train stop," which is not how a passenger asks about the route.',
    },
    {
      kind: 'choice',
      id: 'tour-transport-003',
      stem: '（　）に 間に合わなかったので、タクシーで ホテルへ 帰りました。',
      options: ['終電', '改札', '定期', '運賃'],
      answerIndex: 0,
      explanation:
        '「終電」指當天最後一班電車，「終電に間に合う」＝趕上末班車，整句意思是「沒趕上末班車，只好搭計程車回飯店」，語意通順。「改札」是驗票閘門、「運賃」是車資，都不能和「間に合う」搭配；「定期」是定期票，也和趕不趕得上無關。',
      explanationEn:
        '「終電」 is the last train of the day, and 「終電に間に合う」 means to catch it — so the sentence reads "I missed the last train, so I took a taxi back to the hotel," which makes perfect sense. 「改札」 is the ticket gate and 「運賃」 is the fare, neither of which collocates with 「間に合う」; 「定期」 is a commuter pass, which has nothing to do with making it in time.',
    },
    {
      kind: 'choice',
      id: 'tour-transport-004',
      stem: '電車で おばあさんに 席を（　）。',
      options: ['譲りました', '渡しました', '返しました', '拾いました'],
      answerIndex: 0,
      explanation:
        '「席を譲る」是「讓座」的固定搭配，在電車上把座位讓給老人家就用這個說法。「渡す」是把東西交到對方手上，座位無法用手交付，搭配不自然；「返す」是歸還原本屬於對方的東西，「拾う」是撿起掉落物，語意都不合。',
      explanationEn:
        '「席を譲る」 is the set collocation for giving up one\'s seat, exactly what you do for an elderly person on the train. 「渡す」 means to hand something over physically, and you cannot hand a seat to someone; 「返す」 means to return something that belonged to the other person, and 「拾う」 means to pick up something dropped — neither meaning fits.',
    },
    {
      kind: 'order',
      id: 'tour-transport-005',
      before: 'すみません、どこで',
      after: 'か 分かりますか。',
      segments: ['切符を', '買えば', 'いい', 'の'],
      starIndex: 1,
      explanation:
        '正解語序是「どこで 切符を 買えば いい の（か）」。「疑問詞＋〜ばいいですか」是請對方給建議的常用句型（該在哪裡買票才好）；「の」接在「いい」後面，和句尾的「か」組成間接疑問「〜のか分かりますか」。「買えば」必須緊跟在受詞「切符を」之後，其他排列都不成句。',
      explanationEn:
        'The correct order is 「どこで 切符を 買えば いい の（か）」. Question word + 「〜ばいいですか」 is the common pattern for asking advice — where should I buy a ticket; 「の」 follows 「いい」 and combines with the final 「か」 to form the embedded question 「〜のか分かりますか」. 「買えば」 must come right after its object 「切符を」, and no other arrangement produces a grammatical sentence.',
    },
    {
      kind: 'order',
      id: 'tour-transport-006',
      before: '京都へ 行くには、大阪で',
      after: '。',
      segments: ['乗り換え', 'なければ', 'ならない', 'そうです'],
      starIndex: 2,
      explanation:
        '正解語序是「乗り換え なければ ならない そうです」。「〜なければならない」表示義務（非做不可），前面接動詞ます形去掉ます的「乗り換え」；句尾的「そうです」是傳聞用法，整句意思是「聽說去京都必須在大阪轉車」。「そうです」若不放在最後，文型就斷裂不成句。',
      explanationEn:
        'The correct order is 「乗り換え なければ ならない そうです」. 「〜なければならない」 expresses obligation (must do), attaching to the stem 「乗り換え」; the final 「そうです」 is the hearsay usage, so the whole sentence means "I hear you have to transfer at Osaka to get to Kyoto." If 「そうです」 is placed anywhere but last, the grammar pattern breaks apart.',
    },
  ],
}
