import type { VocabCard } from '../types'

export const cards: VocabCard[] = [
  // ==================== 名詞（45） ====================
  {
    id: 'n1-card-001',
    term: '示唆',
    reading: 'しさ',
    pos: '名詞',
    zh: '暗示、啟發',
    example: '今回の調査結果は、消費行動の大きな転換を示唆している。',
    exampleZh: '這次的調查結果暗示著消費行為的重大轉變。',
    level: 'n1',
  },
  {
    id: 'n1-card-002',
    term: '逸脱',
    reading: 'いつだつ',
    pos: '名詞',
    zh: '偏離、脫軌',
    example: '本来の趣旨から逸脱した議論は、この場では控えていただきたい。',
    exampleZh: '偏離原本主旨的討論，還請在此場合避免。',
    level: 'n1',
  },
  {
    id: 'n1-card-003',
    term: '目処',
    reading: 'めど',
    pos: '名詞',
    zh: '頭緒、大致目標',
    example: '復旧作業は難航しており、完了の目処は立っていない。',
    exampleZh: '修復作業進展不順，完工尚無眉目。',
    level: 'n1',
  },
  {
    id: 'n1-card-004',
    term: '懸念',
    reading: 'けねん',
    pos: '名詞',
    zh: '擔憂、掛慮',
    example: '専門家の間では、物価の急騰を懸念する声が強まっている。',
    exampleZh: '專家之間對物價飆漲的擔憂聲浪日益高漲。',
    level: 'n1',
  },
  {
    id: 'n1-card-005',
    term: '趣旨',
    reading: 'しゅし',
    pos: '名詞',
    zh: '主旨、宗旨',
    example: '本制度の趣旨を踏まえれば、例外を安易に認めるべきではない。',
    exampleZh: '若考量本制度的宗旨，不應輕易承認例外。',
    level: 'n1',
  },
  {
    id: 'n1-card-006',
    term: '葛藤',
    reading: 'かっとう',
    pos: '名詞',
    zh: '糾葛、內心衝突',
    example: '主人公は理想と現実の間で激しい葛藤を抱えていた。',
    exampleZh: '主角在理想與現實之間懷著激烈的內心掙扎。',
    level: 'n1',
  },
  {
    id: 'n1-card-007',
    term: '打診',
    reading: 'だしん',
    pos: '名詞',
    zh: '試探性詢問',
    example: '先方に共同開発の意向がないか、非公式に打診してみた。',
    exampleZh: '非正式地試探對方有無共同開發的意願。',
    level: 'n1',
  },
  {
    id: 'n1-card-008',
    term: '便宜',
    reading: 'べんぎ',
    pos: '名詞',
    zh: '方便、權宜',
    example: '特定の業者にだけ便宜を図ることは、公平性を著しく損なう。',
    exampleZh: '只給特定業者行方便，將嚴重損及公平性。',
    level: 'n1',
  },
  {
    id: 'n1-card-009',
    term: '施策',
    reading: 'しさく',
    pos: '名詞',
    zh: '政策措施',
    example: '少子化を食い止めるには、実効性のある施策が欠かせない。',
    exampleZh: '要遏止少子化，有實效的政策不可或缺。',
    level: 'n1',
  },
  {
    id: 'n1-card-010',
    term: '是正',
    reading: 'ぜせい',
    pos: '名詞',
    zh: '矯正、糾正',
    example: '地域間の医療格差の是正は、長年の課題であり続けている。',
    exampleZh: '矯正地區間的醫療落差，長年以來一直是課題。',
    level: 'n1',
  },
  {
    id: 'n1-card-011',
    term: '打開',
    reading: 'だかい',
    pos: '名詞',
    zh: '打開（僵局）',
    example: '膠着した事態を打開するには、第三者の仲介が不可欠だろう。',
    exampleZh: '要打開僵持的局面，第三方的斡旋不可或缺。',
    level: 'n1',
  },
  {
    id: 'n1-card-012',
    term: '憶測',
    reading: 'おくそく',
    pos: '名詞',
    zh: '臆測',
    example: '根拠のない憶測で他人を非難するのは慎むべきだ。',
    exampleZh: '不應憑毫無根據的臆測去指責他人。',
    level: 'n1',
  },
  {
    id: 'n1-card-013',
    term: '軌道',
    reading: 'きどう',
    pos: '名詞',
    zh: '軌道；正軌',
    example: '新規事業がようやく軌道に乗り、黒字化の見通しが立った。',
    exampleZh: '新事業總算步上軌道，轉虧為盈有了眉目。',
    level: 'n1',
  },
  {
    id: 'n1-card-014',
    term: '兆し',
    reading: 'きざし',
    pos: '名詞',
    zh: '徵兆、跡象',
    example: '長引く不況にも、ようやく回復の兆しが見え始めた。',
    exampleZh: '持續已久的不景氣，總算開始出現復甦的跡象。',
    level: 'n1',
  },
  {
    id: 'n1-card-015',
    term: '名残',
    reading: 'なごり',
    pos: '名詞',
    zh: '遺跡、餘韻',
    example: 'この石畳の道には、城下町だった頃の名残がとどめられている。',
    exampleZh: '這條石板路上留有昔日城下町的遺韻。',
    level: 'n1',
  },
  {
    id: 'n1-card-016',
    term: '風潮',
    reading: 'ふうちょう',
    pos: '名詞',
    zh: '風潮、風氣',
    example: '何事も効率だけで評価する風潮には、疑問を禁じ得ない。',
    exampleZh: '對凡事只以效率評斷的風氣，不禁令人存疑。',
    level: 'n1',
  },
  {
    id: 'n1-card-017',
    term: '変遷',
    reading: 'へんせん',
    pos: '名詞',
    zh: '變遷',
    example: '本章では、家族観の変遷を戦後の統計とともにたどる。',
    exampleZh: '本章將沿著戰後統計，回顧家庭觀念的變遷。',
    level: 'n1',
  },
  {
    id: 'n1-card-018',
    term: '波紋',
    reading: 'はもん',
    pos: '名詞',
    zh: '漣漪；風波',
    example: '大臣の軽率な発言は、各方面に大きな波紋を広げた。',
    exampleZh: '部長輕率的發言在各界掀起了軒然大波。',
    level: 'n1',
  },
  {
    id: 'n1-card-019',
    term: '創設',
    reading: 'そうせつ',
    pos: '名詞',
    zh: '創設；創辦',
    example: 'この賞は若手研究者を支援する目的で創設された。',
    exampleZh: '這個獎是為支援年輕研究者而創設的。',
    level: 'n1',
  },
  {
    id: 'n1-card-020',
    term: '台頭',
    reading: 'たいとう',
    pos: '名詞',
    zh: '抬頭、崛起',
    example: '新興企業の台頭により、業界の勢力図は塗り替えられつつある。',
    exampleZh: '隨著新興企業崛起，業界版圖正被改寫。',
    level: 'n1',
  },
  {
    id: 'n1-card-021',
    term: '停滞',
    reading: 'ていたい',
    pos: '名詞',
    zh: '停滯',
    example: '交渉は三か月にわたって停滞したままである。',
    exampleZh: '交涉已停滯長達三個月。',
    level: 'n1',
  },
  {
    id: 'n1-card-022',
    term: '緩和',
    reading: 'かんわ',
    pos: '名詞',
    zh: '緩和、放寬',
    example: '規制の緩和が、かえって混乱を招いたとの指摘もある。',
    exampleZh: '也有人指出，放寬管制反而招致混亂。',
    level: 'n1',
  },
  {
    id: 'n1-card-023',
    term: '匿名',
    reading: 'とくめい',
    pos: '名詞',
    zh: '匿名',
    example: '匿名を条件に、関係者の一人が内情を語ってくれた。',
    exampleZh: '以匿名作條件，一名相關人士道出了內情。',
    level: 'n1',
  },
  {
    id: 'n1-card-024',
    term: '危惧',
    reading: 'きぐ',
    pos: '名詞',
    zh: '憂慮、擔心',
    example: '技術の悪用を危惧する声は、開発者自身からも上がっている。',
    exampleZh: '憂心技術遭濫用的聲音，也來自開發者本身。',
    level: 'n1',
  },
  {
    id: 'n1-card-025',
    term: '誇張',
    reading: 'こちょう',
    pos: '名詞',
    zh: '誇張、誇大',
    example: '効果を誇張した広告は、法律で厳しく規制されている。',
    exampleZh: '誇大效果的廣告受到法律嚴格規範。',
    level: 'n1',
  },
  {
    id: 'n1-card-026',
    term: '錯覚',
    reading: 'さっかく',
    pos: '名詞',
    zh: '錯覺',
    example: '順調な売り上げに、誰もが成功したかのような錯覚に陥っていた。',
    exampleZh: '業績亮眼，人人都陷入了彷彿已成功的錯覺。',
    level: 'n1',
  },
  {
    id: 'n1-card-027',
    term: '発端',
    reading: 'ほったん',
    pos: '名詞',
    zh: '開端、起因',
    example: '騒動の発端は、一枚の内部文書の流出だった。',
    exampleZh: '風波的開端是一份內部文件外流。',
    level: 'n1',
  },
  {
    id: 'n1-card-028',
    term: '核心',
    reading: 'かくしん',
    pos: '名詞',
    zh: '核心',
    example: '記者の質問は、ようやく問題の核心に触れ始めた。',
    exampleZh: '記者的提問終於開始觸及問題核心。',
    level: 'n1',
  },
  {
    id: 'n1-card-029',
    term: '憤り',
    reading: 'いきどおり',
    pos: '名詞',
    zh: '憤慨',
    example: '住民たちは、行政の怠慢に対する憤りを隠さなかった。',
    exampleZh: '居民毫不掩飾對行政怠惰的憤慨。',
    level: 'n1',
  },
  {
    id: 'n1-card-030',
    term: '圧巻',
    reading: 'あっかん',
    pos: '名詞',
    zh: '最精彩之處',
    example: '公演の圧巻は、百人の合唱が響き渡る最終幕だった。',
    exampleZh: '公演最精彩之處，是百人合唱迴盪的最終幕。',
    level: 'n1',
  },
  {
    id: 'n1-card-031',
    term: '脚光',
    reading: 'きゃっこう',
    pos: '名詞',
    zh: '矚目（浴びる）',
    example: '長年地道に続けてきた研究が、思わぬ形で脚光を浴びた。',
    exampleZh: '長年默默耕耘的研究，以意想不到的形式受到矚目。',
    level: 'n1',
  },
  {
    id: 'n1-card-032',
    term: '折衷',
    reading: 'せっちゅう',
    pos: '名詞',
    zh: '折衷',
    example: '両案の長所を取り入れた折衷案が、最終的に採択された。',
    exampleZh: '最終通過了兼採兩案優點的折衷方案。',
    level: 'n1',
  },
  {
    id: 'n1-card-033',
    term: '賠償',
    reading: 'ばいしょう',
    pos: '名詞',
    zh: '賠償',
    example: '裁判所は、企業側に多額の賠償を命じる判決を下した。',
    exampleZh: '法院判決命令企業方支付鉅額賠償。',
    level: 'n1',
  },
  {
    id: 'n1-card-034',
    term: '暫定',
    reading: 'ざんてい',
    pos: '名詞',
    zh: '暫定',
    example: '正式な基準が定まるまで、暫定の数値で運用する。',
    exampleZh: '在正式標準確立之前，先以暫定數值運作。',
    level: 'n1',
  },
  {
    id: 'n1-card-035',
    term: '束縛',
    reading: 'そくばく',
    pos: '名詞',
    zh: '束縛',
    example: '彼は組織の束縛を嫌い、独立の道を選んだ。',
    exampleZh: '他厭惡組織的束縛，選擇了獨立之路。',
    level: 'n1',
  },
  {
    id: 'n1-card-036',
    term: '網羅',
    reading: 'もうら',
    pos: '名詞',
    zh: '網羅、涵蓋',
    example: 'この辞典は、近代以降の用例をほぼ網羅している。',
    exampleZh: '這部辭典幾乎網羅了近代以降的用例。',
    level: 'n1',
  },
  {
    id: 'n1-card-037',
    term: '飛躍',
    reading: 'ひやく',
    pos: '名詞',
    zh: '飛躍；跳躍推論',
    example: 'その結論には論理の飛躍があると、査読者から指摘された。',
    exampleZh: '審查人指出該結論存在邏輯跳躍。',
    level: 'n1',
  },
  {
    id: 'n1-card-038',
    term: '中枢',
    reading: 'ちゅうすう',
    pos: '名詞',
    zh: '中樞',
    example: '首都圏には、行政と金融の中枢機能が集中している。',
    exampleZh: '首都圈集中著行政與金融的中樞機能。',
    level: 'n1',
  },
  {
    id: 'n1-card-039',
    term: '岐路',
    reading: 'きろ',
    pos: '名詞',
    zh: '岔路、抉擇關頭',
    example: '半導体産業は今、存続をかけた岐路に立たされている。',
    exampleZh: '半導體產業如今正站在攸關存續的岔路上。',
    level: 'n1',
  },
  {
    id: 'n1-card-040',
    term: '過疎',
    reading: 'かそ',
    pos: '名詞',
    zh: '人口過稀',
    example: '過疎が進む山間部では、学校の統廃合が相次いでいる。',
    exampleZh: '人口日益稀少的山區，學校整併接連不斷。',
    level: 'n1',
  },
  {
    id: 'n1-card-041',
    term: '断念',
    reading: 'だんねん',
    pos: '名詞',
    zh: '死心、放棄',
    example: '資金難により、市は新庁舎の建設を断念せざるを得なかった。',
    exampleZh: '因資金短缺，市府不得不放棄興建新廳舍。',
    level: 'n1',
  },
  {
    id: 'n1-card-042',
    term: '洞察',
    reading: 'どうさつ',
    pos: '名詞',
    zh: '洞察',
    example: '本書には、人間心理への鋭い洞察が随所に光っている。',
    exampleZh: '本書處處閃現對人性心理的敏銳洞察。',
    level: 'n1',
  },
  {
    id: 'n1-card-043',
    term: '収拾',
    reading: 'しゅうしゅう',
    pos: '名詞',
    zh: '收拾（局面）',
    example: '責任者が不在のまま、事態は収拾のつかない状況に陥った。',
    exampleZh: '負責人缺席之下，事態陷入無法收拾的局面。',
    level: 'n1',
  },
  {
    id: 'n1-card-044',
    term: '由緒',
    reading: 'ゆいしょ',
    pos: '名詞',
    zh: '淵源、來歷',
    example: 'この神社は千年の由緒を誇り、多くの参拝客を集めている。',
    exampleZh: '這座神社以千年淵源自豪，吸引眾多參拜者。',
    level: 'n1',
  },
  {
    id: 'n1-card-045',
    term: '融通',
    reading: 'ゆうずう',
    pos: '名詞',
    zh: '通融；靈活',
    example: '規則ばかりを盾に取り、融通の利かない対応が批判を招いた。',
    exampleZh: '事事拿規定當擋箭牌、毫不通融的應對招致批評。',
    level: 'n1',
  },

  // ==================== 動詞（25） ====================
  {
    id: 'n1-card-046',
    term: '賄う',
    reading: 'まかなう',
    pos: '動詞',
    zh: '供應；籌措',
    example: '運営費の大半は、市民からの寄付で賄われている。',
    exampleZh: '營運費用大半由市民捐款支應。',
    level: 'n1',
  },
  {
    id: 'n1-card-047',
    term: '培う',
    reading: 'つちかう',
    pos: '動詞',
    zh: '培養（能力等）',
    example: '長年の現場経験で培った勘は、数値には代えがたい。',
    exampleZh: '長年現場經驗培養出的直覺，難以用數值取代。',
    level: 'n1',
  },
  {
    id: 'n1-card-048',
    term: '蝕む',
    reading: 'むしばむ',
    pos: '動詞',
    zh: '侵蝕；戕害',
    example: '長年の過労が、彼の心身を静かに蝕んでいた。',
    exampleZh: '長年的過勞悄悄侵蝕著他的身心。',
    level: 'n1',
  },
  {
    id: 'n1-card-049',
    term: '顧みる',
    reading: 'かえりみる',
    pos: '動詞',
    zh: '回顧；顧及',
    example: '彼は危険を顧みず、濁流に取り残された子どもを救った。',
    exampleZh: '他不顧危險，救出了受困濁流的孩子。',
    level: 'n1',
  },
  {
    id: 'n1-card-050',
    term: '見極める',
    reading: 'みきわめる',
    pos: '動詞',
    zh: '看清、辨明',
    example: '投資の可否は、市場の動向を見極めたうえで判断すべきだ。',
    exampleZh: '投資與否，應在看清市場動向後再作判斷。',
    level: 'n1',
  },
  {
    id: 'n1-card-051',
    term: '阻む',
    reading: 'はばむ',
    pos: '動詞',
    zh: '阻擋',
    example: '複雑な許認可の手続きが、新規参入を阻んでいる。',
    exampleZh: '繁複的許可程序阻礙著新業者加入。',
    level: 'n1',
  },
  {
    id: 'n1-card-052',
    term: '施す',
    reading: 'ほどこす',
    pos: '動詞',
    zh: '施加；施予',
    example: '輸出する機械には、錆を防ぐ特殊な加工が施されている。',
    exampleZh: '外銷的機械施有防鏽的特殊加工。',
    level: 'n1',
  },
  {
    id: 'n1-card-053',
    term: '途絶える',
    reading: 'とだえる',
    pos: '動詞',
    zh: '中斷；斷絕',
    example: '山崩れで道路が塞がり、村への物資輸送が途絶えた。',
    exampleZh: '山崩堵住道路，運往村莊的物資中斷了。',
    level: 'n1',
  },
  {
    id: 'n1-card-054',
    term: '遮る',
    reading: 'さえぎる',
    pos: '動詞',
    zh: '遮擋、打斷',
    example: '議長は興奮した委員の発言を遮り、休憩を宣言した。',
    exampleZh: '議長打斷情緒激昂的委員發言，宣布休息。',
    level: 'n1',
  },
  {
    id: 'n1-card-055',
    term: '潤う',
    reading: 'うるおう',
    pos: '動詞',
    zh: '濕潤；受惠',
    example: '大型連休の観光客で、地元の商店街は大いに潤った。',
    exampleZh: '長假觀光客湧入，地方商店街大為受惠。',
    level: 'n1',
  },
  {
    id: 'n1-card-056',
    term: '廃れる',
    reading: 'すたれる',
    pos: '動詞',
    zh: '過時、衰微',
    example: '一世を風靡した流行語も、数年で廃れてしまうものだ。',
    exampleZh: '風靡一時的流行語，往往數年便告過時。',
    level: 'n1',
  },
  {
    id: 'n1-card-057',
    term: '志す',
    reading: 'こころざす',
    pos: '動詞',
    zh: '立志；以…為志向',
    example: '幼い頃の闘病経験から、彼女は医師を志すようになった。',
    exampleZh: '因幼時抗病的經驗，她立志成為醫師。',
    level: 'n1',
  },
  {
    id: 'n1-card-058',
    term: '貫く',
    reading: 'つらぬく',
    pos: '動詞',
    zh: '貫徹',
    example: '彼女は周囲の反対にも屈せず、自らの信念を貫いた。',
    exampleZh: '她不屈於周遭反對，貫徹了自身信念。',
    level: 'n1',
  },
  {
    id: 'n1-card-059',
    term: '覆す',
    reading: 'くつがえす',
    pos: '動詞',
    zh: '推翻',
    example: '新たな証拠の発見が、従来の定説を根底から覆した。',
    exampleZh: '新證據的發現徹底推翻了以往定論。',
    level: 'n1',
  },
  {
    id: 'n1-card-060',
    term: '拒む',
    reading: 'こばむ',
    pos: '動詞',
    zh: '拒絕',
    example: '同社は取材を拒み、公式な声明も出していない。',
    exampleZh: '該公司拒絕受訪，也未發表正式聲明。',
    level: 'n1',
  },
  {
    id: 'n1-card-061',
    term: '揺らぐ',
    reading: 'ゆらぐ',
    pos: '動詞',
    zh: '動搖',
    example: '相次ぐ改ざんの発覚で、業界全体への信頼が揺らいでいる。',
    exampleZh: '竄改事件接連曝光，整個業界的信譽正在動搖。',
    level: 'n1',
  },
  {
    id: 'n1-card-062',
    term: '装う',
    reading: 'よそおう',
    pos: '動詞',
    zh: '佯裝；打扮',
    example: '容疑者は関係者を装い、規制線の内側に入り込んだという。',
    exampleZh: '嫌犯據稱假扮相關人士，潛入封鎖線內。',
    level: 'n1',
  },
  {
    id: 'n1-card-063',
    term: '醸す',
    reading: 'かもす',
    pos: '動詞',
    zh: '釀成；引起',
    example: '大臣の軽率な発言が、国内外で物議を醸している。',
    exampleZh: '大臣輕率的發言在國內外引發議論。',
    level: 'n1',
  },
  {
    id: 'n1-card-064',
    term: '委ねる',
    reading: 'ゆだねる',
    pos: '動詞',
    zh: '委任、託付',
    example: '最終的な判断は、司法の場に委ねられることになった。',
    exampleZh: '最終判斷交由司法定奪。',
    level: 'n1',
  },
  {
    id: 'n1-card-065',
    term: '経る',
    reading: 'へる',
    pos: '動詞',
    zh: '經過',
    example: 'この条例は、十年の歳月を経てようやく成立した。',
    exampleZh: '這項條例歷經十年歲月終告成立。',
    level: 'n1',
  },
  {
    id: 'n1-card-066',
    term: '鑑みる',
    reading: 'かんがみる',
    pos: '動詞',
    zh: '有鑑於；參照',
    example: '昨今の物価高に鑑みて、支給額の引き上げが決定された。',
    exampleZh: '有鑑於近來物價高漲，決定調高給付額。',
    level: 'n1',
  },
  {
    id: 'n1-card-067',
    term: '侮る',
    reading: 'あなどる',
    pos: '動詞',
    zh: '輕視',
    example: '相手が新人だからといって、決して侮ってはならない。',
    exampleZh: '即使對手是新人，也絕不可輕視。',
    level: 'n1',
  },
  {
    id: 'n1-card-068',
    term: '唱える',
    reading: 'となえる',
    pos: '動詞',
    zh: '提倡；高喊',
    example: 'この仮説に異議を唱える研究者は、当時ほとんどいなかった。',
    exampleZh: '當時幾乎沒有研究者對此假說提出異議。',
    level: 'n1',
  },
  {
    id: 'n1-card-069',
    term: '免れる',
    reading: 'まぬがれる',
    pos: '動詞',
    zh: '免於、逃過',
    example: '早期の避難により、村は最悪の事態を免れた。',
    exampleZh: '由於及早避難，村子逃過了最糟的事態。',
    level: 'n1',
  },
  {
    id: 'n1-card-070',
    term: '陥る',
    reading: 'おちいる',
    pos: '動詞',
    zh: '陷入',
    example: '急激な拡大路線がたたり、会社は深刻な経営難に陥った。',
    exampleZh: '急速擴張路線種下惡果，公司陷入嚴重營運困境。',
    level: 'n1',
  },

  // ==================== い形容詞（6） ====================
  {
    id: 'n1-card-071',
    term: '芳しい',
    reading: 'かんばしい',
    pos: 'い形容詞',
    zh: '良好（多用否定）',
    example: '新薬の治験は続いているが、結果は芳しくないと聞く。',
    exampleZh: '新藥試驗仍在進行，但聽說結果並不理想。',
    level: 'n1',
  },
  {
    id: 'n1-card-072',
    term: '煩わしい',
    reading: 'わずらわしい',
    pos: 'い形容詞',
    zh: '繁瑣煩人',
    example: '煩わしい手続きを一括で済ませられる窓口が新設された。',
    exampleZh: '新設了可一次辦妥繁瑣手續的窗口。',
    level: 'n1',
  },
  {
    id: 'n1-card-073',
    term: '紛らわしい',
    reading: 'まぎらわしい',
    pos: 'い形容詞',
    zh: '易混淆',
    example: '正規品と紛らわしい包装の模倣品が、市場に出回っている。',
    exampleZh: '包裝與正品易混淆的仿冒品正在市面流通。',
    level: 'n1',
  },
  {
    id: 'n1-card-074',
    term: '目覚ましい',
    reading: 'めざましい',
    pos: 'い形容詞',
    zh: '顯著驚人',
    example: '再生医療の分野は、この十年で目覚ましい進歩を遂げた。',
    exampleZh: '再生醫療領域在這十年有了驚人進步。',
    level: 'n1',
  },
  {
    id: 'n1-card-075',
    term: '素っ気ない',
    reading: 'そっけない',
    pos: 'い形容詞',
    zh: '冷淡',
    example: '問い合わせに対して、担当者は素っ気ない返事しか寄越さなかった。',
    exampleZh: '對於詢問，承辦人只給了冷淡的回覆。',
    level: 'n1',
  },
  {
    id: 'n1-card-076',
    term: '潔い',
    reading: 'いさぎよい',
    pos: 'い形容詞',
    zh: '乾脆、光明磊落',
    example: '言い訳を並べるより、潔く非を認めるほうが信頼につながる。',
    exampleZh: '與其連番辯解，不如乾脆認錯更能贏得信賴。',
    level: 'n1',
  },

  // ==================== な形容詞（10） ====================
  {
    id: 'n1-card-077',
    term: '顕著',
    reading: 'けんちょ',
    pos: 'な形容詞',
    zh: '顯著',
    example: '若年層の活字離れは、統計にも顕著に表れている。',
    exampleZh: '年輕族群遠離文字的傾向，在統計上也很顯著。',
    level: 'n1',
  },
  {
    id: 'n1-card-078',
    term: '綿密',
    reading: 'めんみつ',
    pos: 'な形容詞',
    zh: '縝密；周密',
    example: '綿密な現地調査に基づいて、報告書は作成された。',
    exampleZh: '報告書是根據縝密的實地調查寫成的。',
    level: 'n1',
  },
  {
    id: 'n1-card-079',
    term: '緻密',
    reading: 'ちみつ',
    pos: 'な形容詞',
    zh: '縝密',
    example: 'この作戦は、緻密な計算に基づいて立案されたものだ。',
    exampleZh: '這項作戰是基於縝密計算擬定的。',
    level: 'n1',
  },
  {
    id: 'n1-card-080',
    term: '露骨',
    reading: 'ろこつ',
    pos: 'な形容詞',
    zh: '露骨',
    example: '提案が却下されると、彼は露骨に不満そうな顔をした。',
    exampleZh: '提案遭駁回後，他露骨地擺出不滿的臉色。',
    level: 'n1',
  },
  {
    id: 'n1-card-081',
    term: '巧妙',
    reading: 'こうみょう',
    pos: 'な形容詞',
    zh: '巧妙',
    example: '手口は年々巧妙になっており、被害の把握すら難しい。',
    exampleZh: '手法逐年變得巧妙，連掌握受害情況都困難。',
    level: 'n1',
  },
  {
    id: 'n1-card-082',
    term: '無謀',
    reading: 'むぼう',
    pos: 'な形容詞',
    zh: '魯莽',
    example: '装備も計画もないまま冬山に挑むのは、無謀としか言いようがない。',
    exampleZh: '沒有裝備與規劃就挑戰冬季高山，只能說是魯莽。',
    level: 'n1',
  },
  {
    id: 'n1-card-083',
    term: '億劫',
    reading: 'おっくう',
    pos: 'な形容詞',
    zh: '嫌麻煩；懶得動',
    example: '年を取ると、人と会うのさえ億劫になりがちだ。',
    exampleZh: '上了年紀，連與人見面都容易嫌麻煩。',
    level: 'n1',
  },
  {
    id: 'n1-card-084',
    term: '過酷',
    reading: 'かこく',
    pos: 'な形容詞',
    zh: '嚴苛殘酷',
    example: '砂漠地帯での工事は、想像を絶する過酷な環境で進められた。',
    exampleZh: '沙漠地帶的工程在超乎想像的嚴酷環境中進行。',
    level: 'n1',
  },
  {
    id: 'n1-card-085',
    term: '厳密',
    reading: 'げんみつ',
    pos: 'な形容詞',
    zh: '嚴謹精確',
    example: '両者は似ているが、厳密に言えば別の概念である。',
    exampleZh: '兩者相似，但嚴格說來是不同概念。',
    level: 'n1',
  },
  {
    id: 'n1-card-086',
    term: '健全',
    reading: 'けんぜん',
    pos: 'な形容詞',
    zh: '健全',
    example: '批判を許容する社会こそ、健全な民主主義の証しである。',
    exampleZh: '容許批評的社會，正是健全民主的明證。',
    level: 'n1',
  },

  // ==================== 副詞（8） ====================
  {
    id: 'n1-card-087',
    term: 'あえて',
    reading: 'あえて',
    pos: '副詞',
    zh: '特意；硬是',
    example: '誰も指摘しないので、あえて厳しい意見を述べさせてもらう。',
    exampleZh: '既然沒人指出問題，請容我特意直言。',
    level: 'n1',
  },
  {
    id: 'n1-card-088',
    term: 'ことごとく',
    reading: 'ことごとく',
    pos: '副詞',
    zh: '全部、無一例外',
    example: '会社側の提案は、組合によってことごとく退けられた。',
    exampleZh: '資方的提案被工會悉數駁回。',
    level: 'n1',
  },
  {
    id: 'n1-card-089',
    term: 'かろうじて',
    reading: 'かろうじて',
    pos: '副詞',
    zh: '勉強、好不容易',
    example: '売り上げの落ち込みを新事業が補い、かろうじて赤字を免れた。',
    exampleZh: '新事業彌補了業績下滑，勉強免於虧損。',
    level: 'n1',
  },
  {
    id: 'n1-card-090',
    term: 'もっぱら',
    reading: 'もっぱら',
    pos: '副詞',
    zh: '專門、淨是',
    example: '退職後は、もっぱら畑仕事に精を出しているという。',
    exampleZh: '據說他退休後專心致力於田間勞作。',
    level: 'n1',
  },
  {
    id: 'n1-card-091',
    term: 'あくまで',
    reading: 'あくまで',
    pos: '副詞',
    zh: '終究、始終',
    example: 'この数値はあくまで推計であり、確定値ではない。',
    exampleZh: '這個數字終究只是推估，並非確定值。',
    level: 'n1',
  },
  {
    id: 'n1-card-092',
    term: 'ひいては',
    reading: 'ひいては',
    pos: '副詞',
    zh: '進而、乃至',
    example: '教育への投資は、個人の、ひいては国全体の利益となる。',
    exampleZh: '教育投資造福個人，進而造福整個國家。',
    level: 'n1',
  },
  {
    id: 'n1-card-093',
    term: 'とりわけ',
    reading: 'とりわけ',
    pos: '副詞',
    zh: '尤其',
    example: '若い世代、とりわけ十代への影響が深刻だと報告されている。',
    exampleZh: '據報告，對年輕世代、尤其十多歲者影響嚴重。',
    level: 'n1',
  },
  {
    id: 'n1-card-094',
    term: 'いかにも',
    reading: 'いかにも',
    pos: '副詞',
    zh: '的確、活像',
    example: '彼はいかにも残念そうに、計画の中止を告げた。',
    exampleZh: '他一臉遺憾似地宣告終止規劃。',
    level: 'n1',
  },

  // ==================== 表現（6） ====================
  {
    id: 'n1-card-095',
    term: '腑に落ちない',
    reading: 'ふにおちない',
    pos: '表現',
    zh: '難以信服',
    example: '説明を何度聞いても、あの決定だけは腑に落ちない。',
    exampleZh: '說明聽了多次，唯獨那項決定令人難以信服。',
    level: 'n1',
  },
  {
    id: 'n1-card-096',
    term: '目に余る',
    reading: 'めにあまる',
    pos: '表現',
    zh: '看不下去',
    example: '一部の利用者のマナー違反は、もはや目に余るものがある。',
    exampleZh: '部分使用者違反禮儀的行徑，已令人看不下去。',
    level: 'n1',
  },
  {
    id: 'n1-card-097',
    term: '途方に暮れる',
    reading: 'とほうにくれる',
    pos: '表現',
    zh: '束手無策',
    example: '突然の解雇通知を前に、彼は途方に暮れるばかりだった。',
    exampleZh: '面對突如其來的解僱通知，他只能束手無策。',
    level: 'n1',
  },
  {
    id: 'n1-card-098',
    term: '白紙に戻す',
    reading: 'はくしにもどす',
    pos: '表現',
    zh: '推翻重來',
    example: '住民の強い反発を受け、市は再開発計画を白紙に戻した。',
    exampleZh: '遭居民強烈反彈，市府將再開發規劃推翻重來。',
    level: 'n1',
  },
  {
    id: 'n1-card-099',
    term: '一途をたどる',
    reading: 'いっとをたどる',
    pos: '表現',
    zh: '日趨、一路走向',
    example: '地方の路線バスの利用者数は、減少の一途をたどっている。',
    exampleZh: '地方公車的乘客數正一路減少。',
    level: 'n1',
  },
  {
    id: 'n1-card-100',
    term: '歯止めをかける',
    reading: 'はどめをかける',
    pos: '表現',
    zh: '遏止',
    example: '出生数の減少に歯止めをかける有効な策は、いまだ見えない。',
    exampleZh: '遏止出生數下滑的有效對策，至今仍未可見。',
    level: 'n1',
  },
]
