import type { VocabCard } from '../types'

export const cards: VocabCard[] = [
  // ==================== 名詞（42） ====================
  {
    id: 'n2-card-001',
    term: '把握',
    reading: 'はあく',
    pos: '名詞',
    zh: '掌握；充分理解',
    example: 'まず現場の状況を正確に把握することが、対応の第一歩だ。',
    exampleZh: '首先正確掌握現場狀況，是應對的第一步。',
    level: 'n2',
  },
  {
    id: 'n2-card-002',
    term: '妥協',
    reading: 'だきょう',
    pos: '名詞',
    zh: '妥協；讓步',
    example: '品質に関しては一切妥協しないというのが当社の方針だ。',
    exampleZh: '在品質方面絕不妥協，是本公司的方針。',
    level: 'n2',
  },
  {
    id: 'n2-card-003',
    term: '傾向',
    reading: 'けいこう',
    pos: '名詞',
    zh: '傾向；趨勢',
    example: '若い世代ほど車を持たない傾向が強まっている。',
    exampleZh: '越年輕的世代，不買車的傾向越明顯。',
    level: 'n2',
  },
  {
    id: 'n2-card-004',
    term: '需要',
    reading: 'じゅよう',
    pos: '名詞',
    zh: '需求',
    example: '在宅勤務の広がりで、郊外の住宅への需要が高まった。',
    exampleZh: '隨著居家辦公普及，郊區住宅的需求提高了。',
    level: 'n2',
  },
  {
    id: 'n2-card-005',
    term: '供給',
    reading: 'きょうきゅう',
    pos: '名詞',
    zh: '供給',
    example: '部品の供給が追いつかず、生産ラインが止まった。',
    exampleZh: '零件供給趕不上，生產線因此停擺。',
    level: 'n2',
  },
  {
    id: 'n2-card-006',
    term: '方針',
    reading: 'ほうしん',
    pos: '名詞',
    zh: '方針',
    example: '来年度の経営方針は、来週の会議で正式に発表される。',
    exampleZh: '下年度的經營方針將在下週會議正式發表。',
    level: 'n2',
  },
  {
    id: 'n2-card-007',
    term: '対策',
    reading: 'たいさく',
    pos: '名詞',
    zh: '對策',
    example: '同じミスを繰り返さないよう、早急に対策を立てる必要がある。',
    exampleZh: '為避免重蹈覆轍，必須盡快擬定對策。',
    level: 'n2',
  },
  {
    id: 'n2-card-008',
    term: '見通し',
    reading: 'みとおし',
    pos: '名詞',
    zh: '前景；預估',
    example: '原材料の価格は、当分下がる見通しが立っていない。',
    exampleZh: '原物料價格短期內看不到下跌的前景。',
    level: 'n2',
  },
  {
    id: 'n2-card-009',
    term: '課題',
    reading: 'かだい',
    pos: '名詞',
    zh: '課題；待解問題',
    example: '人材の確保は、多くの中小企業に共通する課題である。',
    exampleZh: '確保人才是許多中小企業共同的課題。',
    level: 'n2',
  },
  {
    id: 'n2-card-010',
    term: '収益',
    reading: 'しゅうえき',
    pos: '名詞',
    zh: '收益',
    example: '新サービスは開始半年で、全体の収益の三割を占めるまでになった。',
    exampleZh: '新服務上線半年，已占整體收益的三成。',
    level: 'n2',
  },
  {
    id: 'n2-card-011',
    term: '交渉',
    reading: 'こうしょう',
    pos: '名詞',
    zh: '交涉；談判',
    example: '価格をめぐる交渉は、三か月に及んでようやくまとまった。',
    exampleZh: '圍繞價格的談判歷時三個月才終於談成。',
    level: 'n2',
  },
  {
    id: 'n2-card-012',
    term: '契約',
    reading: 'けいやく',
    pos: '名詞',
    zh: '契約；合約',
    example: '契約の内容を十分に確認したうえで、署名してください。',
    exampleZh: '請充分確認合約內容之後再簽名。',
    level: 'n2',
  },
  {
    id: 'n2-card-013',
    term: '承認',
    reading: 'しょうにん',
    pos: '名詞',
    zh: '批准；核可',
    example: 'この予算案は、まだ役員会の承認を得ていない。',
    exampleZh: '這份預算案尚未獲得董事會批准。',
    level: 'n2',
  },
  {
    id: 'n2-card-014',
    term: '削減',
    reading: 'さくげん',
    pos: '名詞',
    zh: '削減',
    example: '経費の削減だけでは、赤字の根本的な解決にはならない。',
    exampleZh: '光靠削減經費，無法從根本解決虧損。',
    level: 'n2',
  },
  {
    id: 'n2-card-015',
    term: '拡充',
    reading: 'かくじゅう',
    pos: '名詞',
    zh: '擴充',
    example: '市は子育て支援の拡充を最優先の政策に掲げている。',
    exampleZh: '市政府把擴充育兒支援列為最優先政策。',
    level: 'n2',
  },
  {
    id: 'n2-card-016',
    term: '検討',
    reading: 'けんとう',
    pos: '名詞',
    zh: '研議；評估',
    example: 'ご提案の件は、社内で検討のうえ改めてご連絡いたします。',
    exampleZh: '您提案一事，我們將於公司內部研議後再行聯絡。',
    level: 'n2',
  },
  {
    id: 'n2-card-017',
    term: '措置',
    reading: 'そち',
    pos: '名詞',
    zh: '措施',
    example: '政府は中小企業を守るため、緊急の支援措置を打ち出した。',
    exampleZh: '政府為保護中小企業，推出了緊急支援措施。',
    level: 'n2',
  },
  {
    id: 'n2-card-018',
    term: '基準',
    reading: 'きじゅん',
    pos: '名詞',
    zh: '基準；標準',
    example: '採用の基準を明確にしなければ、公平な選考はできない。',
    exampleZh: '不明訂錄用標準，就無法公平甄選。',
    level: 'n2',
  },
  {
    id: 'n2-card-019',
    term: '現状',
    reading: 'げんじょう',
    pos: '名詞',
    zh: '現況',
    example: '現状のままでは、目標の達成は極めて難しいと言わざるを得ない。',
    exampleZh: '照現況下去，不得不說達成目標極為困難。',
    level: 'n2',
  },
  {
    id: 'n2-card-020',
    term: '背景',
    reading: 'はいけい',
    pos: '名詞',
    zh: '背景',
    example: '若者の読書離れの背景には、生活習慣の変化があると言われる。',
    exampleZh: '據說年輕人遠離閱讀的背景是生活習慣的改變。',
    level: 'n2',
  },
  {
    id: 'n2-card-021',
    term: '要因',
    reading: 'よういん',
    pos: '名詞',
    zh: '主要原因',
    example: '売り上げが伸びた要因として、SNSでの口コミが挙げられる。',
    exampleZh: '銷售成長的主因之一，可舉出社群上的口碑。',
    level: 'n2',
  },
  {
    id: 'n2-card-022',
    term: '成果',
    reading: 'せいか',
    pos: '名詞',
    zh: '成果',
    example: '長年の研究がようやく成果として実を結んだ。',
    exampleZh: '多年的研究終於結成了成果。',
    level: 'n2',
  },
  {
    id: 'n2-card-023',
    term: '効率',
    reading: 'こうりつ',
    pos: '名詞',
    zh: '效率',
    example: '作業の効率を上げるには、手順そのものを見直すべきだ。',
    exampleZh: '要提升作業效率，應該重新檢視流程本身。',
    level: 'n2',
  },
  {
    id: 'n2-card-024',
    term: '負担',
    reading: 'ふたん',
    pos: '名詞',
    zh: '負擔',
    example: '一部の社員に負担が集中しない仕組みづくりが求められている。',
    exampleZh: '需要建立避免負擔集中於部分員工的機制。',
    level: 'n2',
  },
  {
    id: 'n2-card-025',
    term: '見直し',
    reading: 'みなおし',
    pos: '名詞',
    zh: '重新檢視；修正',
    example: '料金体系の見直しは、利用者への十分な説明とともに行うべきだ。',
    exampleZh: '調整費率應伴隨對使用者的充分說明進行。',
    level: 'n2',
  },
  {
    id: 'n2-card-026',
    term: '見積もり',
    reading: 'みつもり',
    pos: '名詞',
    zh: '估價；報價',
    example: '工事の見積もりを三社に依頼して、内容を比較した。',
    exampleZh: '向三家公司索取工程估價，並比較內容。',
    level: 'n2',
  },
  {
    id: 'n2-card-027',
    term: '手配',
    reading: 'てはい',
    pos: '名詞',
    zh: '安排；籌備',
    example: '出張に必要な航空券とホテルの手配はもう済んでいる。',
    exampleZh: '出差所需的機票與飯店都已安排妥當。',
    level: 'n2',
  },
  {
    id: 'n2-card-028',
    term: '手続き',
    reading: 'てつづき',
    pos: '名詞',
    zh: '手續',
    example: '契約更新の手続きは、オンラインでも受け付けている。',
    exampleZh: '續約手續也可在線上辦理。',
    level: 'n2',
  },
  {
    id: 'n2-card-029',
    term: '問い合わせ',
    reading: 'といあわせ',
    pos: '名詞',
    zh: '詢問；洽詢',
    example: '新製品の発表後、問い合わせが例年の三倍に増えた。',
    exampleZh: '新產品發表後，洽詢量增為往年的三倍。',
    level: 'n2',
  },
  {
    id: 'n2-card-030',
    term: '取引',
    reading: 'とりひき',
    pos: '名詞',
    zh: '交易；業務往來',
    example: 'あの会社とは十年以上にわたって取引を続けている。',
    exampleZh: '我們與那家公司持續往來已超過十年。',
    level: 'n2',
  },
  {
    id: 'n2-card-031',
    term: '人手',
    reading: 'ひとで',
    pos: '名詞',
    zh: '人手；人力',
    example: '繁忙期は人手が足りず、他部署に応援を頼むしかない。',
    exampleZh: '旺季人手不足，只能請其他部門支援。',
    level: 'n2',
  },
  {
    id: 'n2-card-032',
    term: '支障',
    reading: 'ししょう',
    pos: '名詞',
    zh: '妨礙；阻礙',
    example: 'システムの障害により、業務に大きな支障が出ている。',
    exampleZh: '系統故障對業務造成了很大的妨礙。',
    level: 'n2',
  },
  {
    id: 'n2-card-033',
    term: '意義',
    reading: 'いぎ',
    pos: '名詞',
    zh: '意義',
    example: '結果だけでなく、挑戦したこと自体に大きな意義がある。',
    exampleZh: '不只結果，挑戰本身就有重大意義。',
    level: 'n2',
  },
  {
    id: 'n2-card-034',
    term: '観点',
    reading: 'かんてん',
    pos: '名詞',
    zh: '觀點',
    example: '安全性という観点から、この設計には再考の余地がある。',
    exampleZh: '從安全性的觀點看，這個設計仍有重新考慮的空間。',
    level: 'n2',
  },
  {
    id: 'n2-card-035',
    term: '領域',
    reading: 'りょういき',
    pos: '名詞',
    zh: '領域',
    example: '人工知能は、医療の領域でも応用が進んでいる。',
    exampleZh: '人工智慧在醫療領域的應用也不斷推進。',
    level: 'n2',
  },
  {
    id: 'n2-card-036',
    term: '矛盾',
    reading: 'むじゅん',
    pos: '名詞',
    zh: '矛盾',
    example: '彼の説明には矛盾が多く、そのまま信じるわけにはいかない。',
    exampleZh: '他的說明矛盾百出，不能照單全收。',
    level: 'n2',
  },
  {
    id: 'n2-card-037',
    term: '譲歩',
    reading: 'じょうほ',
    pos: '名詞',
    zh: '讓步',
    example: '交渉をまとめるため、両者はある程度の譲歩を迫られた。',
    exampleZh: '為了談成協議，雙方都被迫做出一定讓步。',
    level: 'n2',
  },
  {
    id: 'n2-card-038',
    term: '発足',
    reading: 'ほっそく',
    pos: '名詞',
    zh: '（組織）成立；啟動',
    example: '新しいプロジェクトチームは、来月一日に発足する予定だ。',
    exampleZh: '新的專案團隊預定下月一日成立。',
    level: 'n2',
  },
  {
    id: 'n2-card-039',
    term: '普及',
    reading: 'ふきゅう',
    pos: '名詞',
    zh: '普及',
    example: '電子決済の普及によって、現金を使う機会が減った。',
    exampleZh: '隨著電子支付普及，用現金的機會變少了。',
    level: 'n2',
  },
  {
    id: 'n2-card-040',
    term: '維持',
    reading: 'いじ',
    pos: '名詞',
    zh: '維持',
    example: '古い設備の維持には、想像以上の費用がかかる。',
    exampleZh: '維持老舊設備所需費用超乎想像。',
    level: 'n2',
  },
  {
    id: 'n2-card-041',
    term: '実績',
    reading: 'じっせき',
    pos: '名詞',
    zh: '實績；業績',
    example: '海外での実績が評価され、彼は部長に抜擢された。',
    exampleZh: '他在海外的實績受到肯定，被拔擢為經理。',
    level: 'n2',
  },
  {
    id: 'n2-card-042',
    term: '賃金',
    reading: 'ちんぎん',
    pos: '名詞',
    zh: '工資；薪資',
    example: '物価の上昇に賃金の伸びが追いついていない。',
    exampleZh: '薪資成長趕不上物價上漲。',
    level: 'n2',
  },

  // ==================== 動詞（28） ====================
  {
    id: 'n2-card-043',
    term: '図る',
    reading: 'はかる',
    pos: '動詞',
    zh: '謀求；力圖',
    example: '両部門の連携を強め、業務の効率化を図る。',
    exampleZh: '加強兩部門的合作，力求業務效率化。',
    level: 'n2',
  },
  {
    id: 'n2-card-044',
    term: '携わる',
    reading: 'たずさわる',
    pos: '動詞',
    zh: '從事；參與',
    example: '入社以来、ずっと製品開発に携わってきた。',
    exampleZh: '進公司以來一直從事產品開發。',
    level: 'n2',
  },
  {
    id: 'n2-card-045',
    term: '至る',
    reading: 'いたる',
    pos: '動詞',
    zh: '到達；發展至',
    example: '何度も話し合いを重ねたが、合意に至ることはなかった。',
    exampleZh: '雖然多次協商，最終仍未能達成共識。',
    level: 'n2',
  },
  {
    id: 'n2-card-046',
    term: '伴う',
    reading: 'ともなう',
    pos: '動詞',
    zh: '伴隨',
    example: '組織の改編に伴って、社内の規定も改められた。',
    exampleZh: '伴隨組織改組，公司內部規定也修訂了。',
    level: 'n2',
  },
  {
    id: 'n2-card-047',
    term: '補う',
    reading: 'おぎなう',
    pos: '動詞',
    zh: '補足；彌補',
    example: '経験の不足は、入念な準備で補うしかない。',
    exampleZh: '經驗不足只能靠周全的準備來彌補。',
    level: 'n2',
  },
  {
    id: 'n2-card-048',
    term: '生じる',
    reading: 'しょうじる',
    pos: '動詞',
    zh: '產生；發生',
    example: '認識のずれから、両社の間にトラブルが生じた。',
    exampleZh: '由於認知落差，兩家公司之間產生了糾紛。',
    level: 'n2',
  },
  {
    id: 'n2-card-049',
    term: '損なう',
    reading: 'そこなう',
    pos: '動詞',
    zh: '損害；破壞',
    example: '一度の不祥事が、長年築いた信頼を損なうこともある。',
    exampleZh: '一次醜聞就可能損害多年累積的信任。',
    level: 'n2',
  },
  {
    id: 'n2-card-050',
    term: '踏まえる',
    reading: 'ふまえる',
    pos: '動詞',
    zh: '依據；立足於',
    example: '前回の反省を踏まえて、進行の手順を大きく変えた。',
    exampleZh: '根據上次的檢討，大幅改變了進行流程。',
    level: 'n2',
  },
  {
    id: 'n2-card-051',
    term: '見込む',
    reading: 'みこむ',
    pos: '動詞',
    zh: '預估；預期',
    example: '来年度は一割程度の売り上げ増を見込んでいる。',
    exampleZh: '預估下年度銷售額約成長一成。',
    level: 'n2',
  },
  {
    id: 'n2-card-052',
    term: '相次ぐ',
    reading: 'あいつぐ',
    pos: '動詞',
    zh: '相繼發生',
    example: '値上げの発表が相次ぎ、消費者の不満が高まっている。',
    exampleZh: '漲價消息接連發布，消費者不滿升高。',
    level: 'n2',
  },
  {
    id: 'n2-card-053',
    term: '上回る',
    reading: 'うわまわる',
    pos: '動詞',
    zh: '超過；高於',
    example: '応募者数は当初の予想を大きく上回った。',
    exampleZh: '報名人數大幅超出當初預期。',
    level: 'n2',
  },
  {
    id: 'n2-card-054',
    term: '下回る',
    reading: 'したまわる',
    pos: '動詞',
    zh: '低於',
    example: '今年の出荷量は、五年ぶりに前年を下回った。',
    exampleZh: '今年出貨量五年來首度低於前一年。',
    level: 'n2',
  },
  {
    id: 'n2-card-055',
    term: '掲げる',
    reading: 'かかげる',
    pos: '動詞',
    zh: '揭示；標舉',
    example: '新社長は「顧客第一」を経営理念として掲げた。',
    exampleZh: '新社長標舉「顧客至上」作為經營理念。',
    level: 'n2',
  },
  {
    id: 'n2-card-056',
    term: '取り組む',
    reading: 'とりくむ',
    pos: '動詞',
    zh: '致力於；投入',
    example: '全社を挙げて、環境問題の解決に取り組んでいる。',
    exampleZh: '全公司上下都在致力解決環境問題。',
    level: 'n2',
  },
  {
    id: 'n2-card-057',
    term: '引き受ける',
    reading: 'ひきうける',
    pos: '動詞',
    zh: '承接；接下',
    example: '納期が厳しい仕事だが、思い切って引き受けることにした。',
    exampleZh: '雖然交期很緊，還是下定決心接下這份工作。',
    level: 'n2',
  },
  {
    id: 'n2-card-058',
    term: '促す',
    reading: 'うながす',
    pos: '動詞',
    zh: '促使；催促',
    example: '期限を過ぎた取引先に、支払いを促すメールを送った。',
    exampleZh: '向逾期的客戶寄出催促付款的郵件。',
    level: 'n2',
  },
  {
    id: 'n2-card-059',
    term: '妨げる',
    reading: 'さまたげる',
    pos: '動詞',
    zh: '妨礙',
    example: '過剰な規制は、かえって産業の発展を妨げるおそれがある。',
    exampleZh: '過度管制反而可能妨礙產業發展。',
    level: 'n2',
  },
  {
    id: 'n2-card-060',
    term: '応じる',
    reading: 'おうじる',
    pos: '動詞',
    zh: '因應；回應',
    example: '状況の変化に応じて、計画を柔軟に修正していく。',
    exampleZh: '因應情況變化，靈活地修正計畫。',
    level: 'n2',
  },
  {
    id: 'n2-card-061',
    term: '訴える',
    reading: 'うったえる',
    pos: '動詞',
    zh: '訴諸；呼籲；控告',
    example: '住民たちは工事の中止を市に強く訴えた。',
    exampleZh: '居民們強烈向市政府訴求停止施工。',
    level: 'n2',
  },
  {
    id: 'n2-card-062',
    term: '見合わせる',
    reading: 'みあわせる',
    pos: '動詞',
    zh: '暫緩；暫停',
    example: '市場の先行きが不透明なため、新規の投資を見合わせた。',
    exampleZh: '因市場前景不明，暫緩了新投資。',
    level: 'n2',
  },
  {
    id: 'n2-card-063',
    term: '打ち切る',
    reading: 'うちきる',
    pos: '動詞',
    zh: '中止；停辦',
    example: '採算が取れないと判断し、会社はそのサービスを打ち切った。',
    exampleZh: '公司判斷無法回本，中止了那項服務。',
    level: 'n2',
  },
  {
    id: 'n2-card-064',
    term: '乗り越える',
    reading: 'のりこえる',
    pos: '動詞',
    zh: '克服；跨越',
    example: '幾度もの経営危機を乗り越えて、会社は創業百年を迎えた。',
    exampleZh: '公司克服多次經營危機，迎來創業百年。',
    level: 'n2',
  },
  {
    id: 'n2-card-065',
    term: '練る',
    reading: 'ねる',
    pos: '動詞',
    zh: '推敲；仔細擬定',
    example: '発表の前に、もう一度構成を練る時間がほしい。',
    exampleZh: '希望在發表前再有時間推敲一次架構。',
    level: 'n2',
  },
  {
    id: 'n2-card-066',
    term: '兼ねる',
    reading: 'かねる',
    pos: '動詞',
    zh: '兼任；兼具',
    example: '彼は営業部長と広報の責任者を兼ねている。',
    exampleZh: '他兼任業務經理與公關負責人。',
    level: 'n2',
  },
  {
    id: 'n2-card-067',
    term: '滞る',
    reading: 'とどこおる',
    pos: '動詞',
    zh: '停滯；拖延',
    example: '担当者の急な退職で、手続きが滞っている。',
    exampleZh: '因承辦人突然離職，手續停滯不前。',
    level: 'n2',
  },
  {
    id: 'n2-card-068',
    term: '遂げる',
    reading: 'とげる',
    pos: '動詞',
    zh: '達成；完成',
    example: 'この十年で、業界は目覚ましい発展を遂げた。',
    exampleZh: '這十年間，業界達成了驚人的發展。',
    level: 'n2',
  },
  {
    id: 'n2-card-069',
    term: '募る',
    reading: 'つのる',
    pos: '動詞',
    zh: '招募；（情緒）加劇',
    example: '新店舗の開店に向けて、アルバイトを募っている。',
    exampleZh: '為了新店開幕，正在招募工讀生。',
    level: 'n2',
  },
  {
    id: 'n2-card-070',
    term: '占める',
    reading: 'しめる',
    pos: '動詞',
    zh: '占（比例、位置）',
    example: '海外売り上げが全体の半分以上を占めるようになった。',
    exampleZh: '海外銷售額已占整體一半以上。',
    level: 'n2',
  },

  // ==================== い形容詞（8） ====================
  {
    id: 'n2-card-071',
    term: '著しい',
    reading: 'いちじるしい',
    pos: 'い形容詞',
    zh: '顯著的',
    example: 'この分野の技術の進歩は著しく、一年で常識が変わる。',
    exampleZh: '這個領域技術進步顯著，一年就顛覆常識。',
    level: 'n2',
  },
  {
    id: 'n2-card-072',
    term: '乏しい',
    reading: 'とぼしい',
    pos: 'い形容詞',
    zh: '缺乏的',
    example: '資金の乏しい企業ほど、人材の流出に悩まされやすい。',
    exampleZh: '資金越匱乏的企業，越容易苦於人才流失。',
    level: 'n2',
  },
  {
    id: 'n2-card-073',
    term: '望ましい',
    reading: 'のぞましい',
    pos: 'い形容詞',
    zh: '理想的；最好的',
    example: '重要な連絡は、口頭だけでなく文書でも残すのが望ましい。',
    exampleZh: '重要聯絡最好除口頭外也留下書面紀錄。',
    level: 'n2',
  },
  {
    id: 'n2-card-074',
    term: '好ましい',
    reading: 'このましい',
    pos: 'い形容詞',
    zh: '令人有好感的；合宜的',
    example: '面接では、清潔感のある服装が好ましい印象を与える。',
    exampleZh: '面試時整潔的穿著能給人良好印象。',
    level: 'n2',
  },
  {
    id: 'n2-card-075',
    term: '慌ただしい',
    reading: 'あわただしい',
    pos: 'い形容詞',
    zh: '匆忙的；忙亂的',
    example: '年度末は慌ただしくて、昼食を取る暇もないほどだ。',
    exampleZh: '年度末忙亂到連吃午餐的空檔都沒有。',
    level: 'n2',
  },
  {
    id: 'n2-card-076',
    term: '心強い',
    reading: 'こころづよい',
    pos: 'い形容詞',
    zh: '令人安心的',
    example: '経験豊富な先輩が同行してくれるのは、実に心強い。',
    exampleZh: '有經驗豐富的前輩同行，實在令人安心。',
    level: 'n2',
  },
  {
    id: 'n2-card-077',
    term: '根強い',
    reading: 'ねづよい',
    pos: 'い形容詞',
    zh: '根深蒂固的',
    example: '紙の本には、今も根強い人気がある。',
    exampleZh: '紙本書至今仍有根深蒂固的人氣。',
    level: 'n2',
  },
  {
    id: 'n2-card-078',
    term: '幅広い',
    reading: 'はばひろい',
    pos: 'い形容詞',
    zh: '廣泛的',
    example: 'この講座は、学生から高齢者まで幅広い層に支持されている。',
    exampleZh: '這門課受到從學生到銀髮族的廣泛支持。',
    level: 'n2',
  },

  // ==================== な形容詞（10） ====================
  {
    id: 'n2-card-079',
    term: '円滑',
    reading: 'えんかつ',
    pos: 'な形容詞',
    zh: '順暢；圓滑',
    example: '引き継ぎを丁寧に行えば、業務は円滑に進むはずだ。',
    exampleZh: '仔細做好交接，業務應能順暢推進。',
    level: 'n2',
  },
  {
    id: 'n2-card-080',
    term: '妥当',
    reading: 'だとう',
    pos: 'な形容詞',
    zh: '妥當；合理',
    example: 'この価格設定は、品質を考えれば妥当だと言えるだろう。',
    exampleZh: '考量品質，這樣的定價可說相當合理。',
    level: 'n2',
  },
  {
    id: 'n2-card-081',
    term: '迅速',
    reading: 'じんそく',
    pos: 'な形容詞',
    zh: '迅速',
    example: '苦情への迅速な対応が、かえって信頼を高めることもある。',
    exampleZh: '迅速處理客訴，反而可能提升信任。',
    level: 'n2',
  },
  {
    id: 'n2-card-082',
    term: '柔軟',
    reading: 'じゅうなん',
    pos: 'な形容詞',
    zh: '靈活；柔軟',
    example: '前例にとらわれず、柔軟な発想で解決策を探りたい。',
    exampleZh: '不拘泥前例，想以靈活思維尋求解方。',
    level: 'n2',
  },
  {
    id: 'n2-card-083',
    term: '曖昧',
    reading: 'あいまい',
    pos: 'な形容詞',
    zh: '曖昧；含糊',
    example: '責任の所在が曖昧なままでは、同じ問題が繰り返される。',
    exampleZh: '責任歸屬含糊不清，同樣問題就會重演。',
    level: 'n2',
  },
  {
    id: 'n2-card-084',
    term: '頻繁',
    reading: 'ひんぱん',
    pos: 'な形容詞',
    zh: '頻繁',
    example: '仕様の頻繁な変更が、開発チームの負担になっている。',
    exampleZh: '規格頻繁變更成了開發團隊的負擔。',
    level: 'n2',
  },
  {
    id: 'n2-card-085',
    term: '慎重',
    reading: 'しんちょう',
    pos: 'な形容詞',
    zh: '慎重',
    example: '大きな投資だからこそ、慎重に判断する必要がある。',
    exampleZh: '正因是重大投資，才需要慎重判斷。',
    level: 'n2',
  },
  {
    id: 'n2-card-086',
    term: '大幅',
    reading: 'おおはば',
    pos: 'な形容詞',
    zh: '大幅度',
    example: '工程を見直した結果、納期を大幅に短縮できた。',
    exampleZh: '重新檢視流程後，交期得以大幅縮短。',
    level: 'n2',
  },
  {
    id: 'n2-card-087',
    term: '良好',
    reading: 'りょうこう',
    pos: 'な形容詞',
    zh: '良好',
    example: '両社の関係は良好で、新たな共同事業の話も出ている。',
    exampleZh: '兩公司關係良好，也談到了新的合作事業。',
    level: 'n2',
  },
  {
    id: 'n2-card-088',
    term: '厄介',
    reading: 'やっかい',
    pos: 'な形容詞',
    zh: '麻煩；棘手',
    example: 'クレームの中でも、原因が特定できないものが最も厄介だ。',
    exampleZh: '客訴當中，查不出原因的最為棘手。',
    level: 'n2',
  },

  // ==================== 副詞（9） ====================
  {
    id: 'n2-card-089',
    term: '思い切って',
    reading: 'おもいきって',
    pos: '副詞',
    zh: '下定決心地；毅然',
    example: '長年勤めた会社を、思い切って辞めることにした。',
    exampleZh: '毅然決定辭去任職多年的公司。',
    level: 'n2',
  },
  {
    id: 'n2-card-090',
    term: 'いったん',
    reading: 'いったん',
    pos: '副詞',
    zh: '暫且；一旦',
    example: '議論が行き詰まったので、いったん休憩を挟むことにした。',
    exampleZh: '討論陷入僵局，於是決定暫且休息一下。',
    level: 'n2',
  },
  {
    id: 'n2-card-091',
    term: 'あらかじめ',
    reading: 'あらかじめ',
    pos: '副詞',
    zh: '預先',
    example: '質問事項はあらかじめメールで送っておいてください。',
    exampleZh: '請預先用郵件寄來提問事項。',
    level: 'n2',
  },
  {
    id: 'n2-card-092',
    term: 'いっそう',
    reading: 'いっそう',
    pos: '副詞',
    zh: '更加',
    example: '競争が激しくなり、品質管理の重要性はいっそう増した。',
    exampleZh: '競爭加劇，品質管理的重要性更加提高。',
    level: 'n2',
  },
  {
    id: 'n2-card-093',
    term: '依然として',
    reading: 'いぜんとして',
    pos: '副詞',
    zh: '依然',
    example: '対策を重ねても、事故の件数は依然として減っていない。',
    exampleZh: '儘管一再採取對策，事故件數依然未減。',
    level: 'n2',
  },
  {
    id: 'n2-card-094',
    term: '次第に',
    reading: 'しだいに',
    pos: '副詞',
    zh: '逐漸',
    example: '新制度への反発は、時間がたつにつれて次第に収まった。',
    exampleZh: '對新制度的反彈隨時間逐漸平息。',
    level: 'n2',
  },
  {
    id: 'n2-card-095',
    term: '極めて',
    reading: 'きわめて',
    pos: '副詞',
    zh: '極為',
    example: 'この条件で合意できたのは、極めてまれなことだ。',
    exampleZh: '能以這種條件達成共識，是極為罕見的事。',
    level: 'n2',
  },
  {
    id: 'n2-card-096',
    term: '案の定',
    reading: 'あんのじょう',
    pos: '副詞',
    zh: '果不其然',
    example: '準備不足のまま臨んだ発表は、案の定うまくいかなかった。',
    exampleZh: '準備不足就上場的發表，果不其然不順利。',
    level: 'n2',
  },
  {
    id: 'n2-card-097',
    term: '直ちに',
    reading: 'ただちに',
    pos: '副詞',
    zh: '立刻',
    example: '異常を検知した場合は、直ちに装置を停止してください。',
    exampleZh: '偵測到異常時，請立刻停止裝置。',
    level: 'n2',
  },

  // ==================== 表現（3） ====================
  {
    id: 'n2-card-098',
    term: 'やむを得ない',
    reading: 'やむをえない',
    pos: '表現',
    zh: '不得已；無可奈何',
    example: '台風の接近を考えれば、イベントの中止はやむを得ない。',
    exampleZh: '考量颱風逼近，活動停辦也是不得已。',
    level: 'n2',
  },
  {
    id: 'n2-card-099',
    term: 'お手数ですが',
    reading: 'おてすうですが',
    pos: '表現',
    zh: '勞煩您；麻煩您',
    example: 'お手数ですが、添付の書類にご記入のうえご返送ください。',
    exampleZh: '勞煩您填寫附件文件後寄回。',
    level: 'n2',
  },
  {
    id: 'n2-card-100',
    term: '差し支えなければ',
    reading: 'さしつかえなければ',
    pos: '表現',
    zh: '方便的話；不介意的話',
    example: '差し支えなければ、ご検討の状況をお聞かせいただけますか。',
    exampleZh: '方便的話，能否告知您評估的進度？',
    level: 'n2',
  },
]
