import type { VocabCard } from '../types'

export const cards: VocabCard[] = [
  // ==================== 名詞（職場） ====================
  {
    id: 'n3-card-001',
    term: '遠慮',
    reading: 'えんりょ',
    pos: '名詞',
    zh: '客氣；顧慮',
    example: 'どうぞ遠慮しないで、たくさん召し上がってください。',
    exampleZh: '請別客氣，多吃一點。',
    level: 'n3',
  },
  {
    id: 'n3-card-002',
    term: '我慢',
    reading: 'がまん',
    pos: '名詞',
    zh: '忍耐；忍受',
    example: '歯が痛かったが、会議が終わるまで我慢した。',
    exampleZh: '雖然牙齒很痛，但忍到會議結束。',
    level: 'n3',
  },
  {
    id: 'n3-card-003',
    term: '締め切り',
    reading: 'しめきり',
    pos: '名詞',
    zh: '截止日期',
    example: 'レポートの締め切りは金曜日の午後五時です。',
    exampleZh: '報告的截止期限是星期五下午五點。',
    level: 'n3',
  },
  {
    id: 'n3-card-004',
    term: '確認',
    reading: 'かくにん',
    pos: '名詞',
    zh: '確認；核對',
    example: 'メールを送る前に、宛先をもう一度確認してください。',
    exampleZh: '寄信之前，請再確認一次收件人。',
    level: 'n3',
  },
  {
    id: 'n3-card-005',
    term: '打ち合わせ',
    reading: 'うちあわせ',
    pos: '名詞',
    zh: '事前商量；碰頭會',
    example: '明日の午後、新しい企画の打ち合わせがあります。',
    exampleZh: '明天下午有新企劃的討論會。',
    level: 'n3',
  },
  {
    id: 'n3-card-006',
    term: '残業',
    reading: 'ざんぎょう',
    pos: '名詞',
    zh: '加班',
    example: '今週は仕事が多くて、毎日残業しています。',
    exampleZh: '這週工作很多，每天都在加班。',
    level: 'n3',
  },
  {
    id: 'n3-card-007',
    term: '出張',
    reading: 'しゅっちょう',
    pos: '名詞',
    zh: '出差',
    example: '部長は来週、大阪へ出張する予定です。',
    exampleZh: '部長預定下週去大阪出差。',
    level: 'n3',
  },
  {
    id: 'n3-card-008',
    term: '上司',
    reading: 'じょうし',
    pos: '名詞',
    zh: '上司；主管',
    example: '上司に相談してから、返事をしてもいいですか。',
    exampleZh: '我可以先和上司商量後再回覆嗎？',
    level: 'n3',
  },
  {
    id: 'n3-card-009',
    term: '同僚',
    reading: 'どうりょう',
    pos: '名詞',
    zh: '同事',
    example: '昼休みに同僚とラーメンを食べに行った。',
    exampleZh: '午休時和同事去吃了拉麵。',
    level: 'n3',
  },
  {
    id: 'n3-card-010',
    term: '書類',
    reading: 'しょるい',
    pos: '名詞',
    zh: '文件；資料',
    example: 'この書類に名前と住所を書いてください。',
    exampleZh: '請在這份文件上寫下姓名和地址。',
    level: 'n3',
  },
  {
    id: 'n3-card-011',
    term: '資料',
    reading: 'しりょう',
    pos: '名詞',
    zh: '資料',
    example: '会議の前に、この資料を読んでおいてください。',
    exampleZh: '開會前請先讀過這份資料。',
    level: 'n3',
  },
  {
    id: 'n3-card-012',
    term: '報告',
    reading: 'ほうこく',
    pos: '名詞',
    zh: '報告；匯報',
    example: '出張の結果を課長に報告しました。',
    exampleZh: '向課長報告了出差的結果。',
    level: 'n3',
  },
  {
    id: 'n3-card-013',
    term: '連絡',
    reading: 'れんらく',
    pos: '名詞',
    zh: '聯絡；聯繫',
    example: '遅れる場合は、必ず連絡してください。',
    exampleZh: '會遲到的話，請務必聯絡。',
    level: 'n3',
  },
  {
    id: 'n3-card-014',
    term: '提案',
    reading: 'ていあん',
    pos: '名詞',
    zh: '提案；建議',
    example: '会議で新しい売り方について提案をした。',
    exampleZh: '在會議上提出了新銷售方式的提案。',
    level: 'n3',
  },
  {
    id: 'n3-card-015',
    term: '面接',
    reading: 'めんせつ',
    pos: '名詞',
    zh: '面試',
    example: '明日は初めての面接なので、少し緊張しています。',
    exampleZh: '明天是第一次面試，所以有點緊張。',
    level: 'n3',
  },
  {
    id: 'n3-card-016',
    term: '応募',
    reading: 'おうぼ',
    pos: '名詞',
    zh: '應徵；報名',
    example: 'アルバイトの募集を見て、すぐに応募した。',
    exampleZh: '看到打工的招募，馬上就去應徵了。',
    level: 'n3',
  },
  {
    id: 'n3-card-017',
    term: '情報',
    reading: 'じょうほう',
    pos: '名詞',
    zh: '資訊；情報',
    example: 'インターネットで旅行の情報を集めています。',
    exampleZh: '正在網路上蒐集旅遊資訊。',
    level: 'n3',
  },
  {
    id: 'n3-card-018',
    term: '知識',
    reading: 'ちしき',
    pos: '名詞',
    zh: '知識',
    example: 'この仕事にはパソコンの知識が必要です。',
    exampleZh: '這份工作需要電腦方面的知識。',
    level: 'n3',
  },
  {
    id: 'n3-card-019',
    term: '命令',
    reading: 'めいれい',
    pos: '名詞',
    zh: '命令',
    example: '社長の命令で、急に出張することになった。',
    exampleZh: '因為社長的命令，突然要去出差了。',
    level: 'n3',
  },
  {
    id: 'n3-card-020',
    term: '給料',
    reading: 'きゅうりょう',
    pos: '名詞',
    zh: '薪水',
    example: '給料が上がったので、家族と外食した。',
    exampleZh: '因為薪水調漲了，就和家人外出用餐。',
    level: 'n3',
  },
  // ==================== 名詞（生活・狀態） ====================
  {
    id: 'n3-card-021',
    term: '性格',
    reading: 'せいかく',
    pos: '名詞',
    zh: '性格；個性',
    example: '妹は明るい性格で、誰とでもすぐ仲良くなる。',
    exampleZh: '妹妹個性開朗，和誰都能馬上變熟。',
    level: 'n3',
  },
  {
    id: 'n3-card-022',
    term: '態度',
    reading: 'たいど',
    pos: '名詞',
    zh: '態度',
    example: 'お客様に対する態度には気をつけましょう。',
    exampleZh: '對待客人的態度要多加注意。',
    level: 'n3',
  },
  {
    id: 'n3-card-023',
    term: '様子',
    reading: 'ようす',
    pos: '名詞',
    zh: '樣子；情況',
    example: '彼は朝から様子がおかしいので、心配だ。',
    exampleZh: '他從早上開始就怪怪的，讓人擔心。',
    level: 'n3',
  },
  {
    id: 'n3-card-024',
    term: '状況',
    reading: 'じょうきょう',
    pos: '名詞',
    zh: '狀況；情勢',
    example: '状況が変わったら、すぐに知らせてください。',
    exampleZh: '狀況有變的話，請立刻通知我。',
    level: 'n3',
  },
  {
    id: 'n3-card-025',
    term: '目標',
    reading: 'もくひょう',
    pos: '名詞',
    zh: '目標',
    example: '今年の目標は日本語能力試験に合格することです。',
    exampleZh: '今年的目標是通過日本語能力測驗。',
    level: 'n3',
  },
  {
    id: 'n3-card-026',
    term: '結果',
    reading: 'けっか',
    pos: '名詞',
    zh: '結果',
    example: '検査の結果は一週間後にわかります。',
    exampleZh: '檢查結果一週後會知道。',
    level: 'n3',
  },
  {
    id: 'n3-card-027',
    term: '目的',
    reading: 'もくてき',
    pos: '名詞',
    zh: '目的',
    example: '今回の出張の目的は新しい工場の見学です。',
    exampleZh: '這次出差的目的是參觀新工廠。',
    level: 'n3',
  },
  {
    id: 'n3-card-028',
    term: '影響',
    reading: 'えいきょう',
    pos: '名詞',
    zh: '影響',
    example: '台風の影響で、電車が止まっています。',
    exampleZh: '受颱風影響，電車停駛中。',
    level: 'n3',
  },
  {
    id: 'n3-card-029',
    term: '効果',
    reading: 'こうか',
    pos: '名詞',
    zh: '效果',
    example: 'この薬は効果が出るまで時間がかかります。',
    exampleZh: '這種藥要花一段時間才會出現效果。',
    level: 'n3',
  },
  {
    id: 'n3-card-030',
    term: '印象',
    reading: 'いんしょう',
    pos: '名詞',
    zh: '印象',
    example: '面接では第一印象がとても大切だ。',
    exampleZh: '面試時第一印象非常重要。',
    level: 'n3',
  },
  {
    id: 'n3-card-031',
    term: '感想',
    reading: 'かんそう',
    pos: '名詞',
    zh: '感想',
    example: '映画を見た感想を友達と話し合った。',
    exampleZh: '和朋友聊了看完電影的感想。',
    level: 'n3',
  },
  {
    id: 'n3-card-032',
    term: '不満',
    reading: 'ふまん',
    pos: '名詞',
    zh: '不滿',
    example: '彼は給料に不満があるようだ。',
    exampleZh: '他似乎對薪水有所不滿。',
    level: 'n3',
  },
  {
    id: 'n3-card-033',
    term: '文句',
    reading: 'もんく',
    pos: '名詞',
    zh: '抱怨；牢騷',
    example: '文句ばかり言っていないで、早く仕事をしなさい。',
    exampleZh: '別光是抱怨，快點工作。',
    level: 'n3',
  },
  {
    id: 'n3-card-034',
    term: '噂',
    reading: 'うわさ',
    pos: '名詞',
    zh: '傳聞；謠言',
    example: 'あの店が閉まるという噂を聞きました。',
    exampleZh: '聽到那家店要關門的傳聞。',
    level: 'n3',
  },
  {
    id: 'n3-card-035',
    term: '留守',
    reading: 'るす',
    pos: '名詞',
    zh: '不在家',
    example: '昨日訪ねたら、田中さんは留守だった。',
    exampleZh: '昨天去拜訪時，田中先生不在家。',
    level: 'n3',
  },
  {
    id: 'n3-card-036',
    term: '渋滞',
    reading: 'じゅうたい',
    pos: '名詞',
    zh: '塞車',
    example: '連休なので、高速道路はひどい渋滞だった。',
    exampleZh: '因為是連假，高速公路塞車塞得很嚴重。',
    level: 'n3',
  },
  {
    id: 'n3-card-037',
    term: '行列',
    reading: 'ぎょうれつ',
    pos: '名詞',
    zh: '排隊的隊伍',
    example: 'あのパン屋は朝から行列ができている。',
    exampleZh: '那家麵包店從早上就大排長龍。',
    level: 'n3',
  },
  {
    id: 'n3-card-038',
    term: '割引',
    reading: 'わりびき',
    pos: '名詞',
    zh: '折扣',
    example: '学生証を見せると、二割引になります。',
    exampleZh: '出示學生證的話，可以打八折。',
    level: 'n3',
  },
  {
    id: 'n3-card-039',
    term: '貯金',
    reading: 'ちょきん',
    pos: '名詞',
    zh: '存款；儲蓄',
    example: '旅行のために、毎月少しずつ貯金しています。',
    exampleZh: '為了旅行，每個月一點一點地存錢。',
    level: 'n3',
  },
  {
    id: 'n3-card-040',
    term: '家賃',
    reading: 'やちん',
    pos: '名詞',
    zh: '房租',
    example: 'この辺りは駅に近いので、家賃が高い。',
    exampleZh: '這一帶離車站近，所以房租很貴。',
    level: 'n3',
  },
  // ==================== 動詞 ====================
  {
    id: 'n3-card-041',
    term: 'あわてる',
    reading: 'あわてる',
    pos: '動詞',
    zh: '慌張；驚慌',
    example: '時間はまだあるから、あわてなくてもいいですよ。',
    exampleZh: '時間還很充裕，不用慌張喔。',
    level: 'n3',
  },
  {
    id: 'n3-card-042',
    term: '確かめる',
    reading: 'たしかめる',
    pos: '動詞',
    zh: '弄清楚；查證',
    example: '出かける前に、ドアの鍵を確かめた。',
    exampleZh: '出門前確認了門有沒有上鎖。',
    level: 'n3',
  },
  {
    id: 'n3-card-043',
    term: '片付ける',
    reading: 'かたづける',
    pos: '動詞',
    zh: '收拾；整理',
    example: 'お客さんが来る前に、部屋を片付けておこう。',
    exampleZh: '客人來之前先把房間收拾好吧。',
    level: 'n3',
  },
  {
    id: 'n3-card-044',
    term: '間に合う',
    reading: 'まにあう',
    pos: '動詞',
    zh: '來得及；趕上',
    example: '急げば、最終の電車に間に合うはずだ。',
    exampleZh: '快一點的話，應該趕得上末班電車。',
    level: 'n3',
  },
  {
    id: 'n3-card-045',
    term: '伝える',
    reading: 'つたえる',
    pos: '動詞',
    zh: '傳達；轉告',
    example: '会議の時間が変わったことを、みんなに伝えてください。',
    exampleZh: '請告訴大家會議時間改了。',
    level: 'n3',
  },
  {
    id: 'n3-card-046',
    term: '預ける',
    reading: 'あずける',
    pos: '動詞',
    zh: '寄放；託付',
    example: '荷物をホテルのフロントに預けてから、観光に出かけた。',
    exampleZh: '把行李寄放在飯店櫃檯後，就出門觀光了。',
    level: 'n3',
  },
  {
    id: 'n3-card-047',
    term: '断る',
    reading: 'ことわる',
    pos: '動詞',
    zh: '拒絕；謝絕',
    example: '残業を頼まれたが、用事があったので断った。',
    exampleZh: '被拜託加班，但因為有事就拒絕了。',
    level: 'n3',
  },
  {
    id: 'n3-card-048',
    term: '頼む',
    reading: 'たのむ',
    pos: '動詞',
    zh: '拜託；請求',
    example: '引っ越しの手伝いを友達に頼んだ。',
    exampleZh: '拜託朋友幫忙搬家。',
    level: 'n3',
  },
  {
    id: 'n3-card-049',
    term: '任せる',
    reading: 'まかせる',
    pos: '動詞',
    zh: '交給；託付',
    example: 'この仕事は経験のある君に任せるよ。',
    exampleZh: '這個工作就交給有經驗的你了。',
    level: 'n3',
  },
  {
    id: 'n3-card-050',
    term: '諦める',
    reading: 'あきらめる',
    pos: '動詞',
    zh: '放棄；死心',
    example: '雨が強いので、今日の登山は諦めましょう。',
    exampleZh: '雨太大了，今天的登山就放棄吧。',
    level: 'n3',
  },
  {
    id: 'n3-card-051',
    term: '間違える',
    reading: 'まちがえる',
    pos: '動詞',
    zh: '弄錯；搞錯',
    example: '駅の出口を間違えて、遠回りしてしまった。',
    exampleZh: '弄錯車站出口，結果繞了遠路。',
    level: 'n3',
  },
  {
    id: 'n3-card-052',
    term: '比べる',
    reading: 'くらべる',
    pos: '動詞',
    zh: '比較',
    example: '値段をよく比べてから、どちらを買うか決めよう。',
    exampleZh: '仔細比較價格後，再決定買哪一個吧。',
    level: 'n3',
  },
  {
    id: 'n3-card-053',
    term: '増やす',
    reading: 'ふやす',
    pos: '動詞',
    zh: '增加（他動詞）',
    example: '単語を増やすために、毎日カードで復習している。',
    exampleZh: '為了增加單字量，每天用卡片複習。',
    level: 'n3',
  },
  {
    id: 'n3-card-054',
    term: '減らす',
    reading: 'へらす',
    pos: '動詞',
    zh: '減少（他動詞）',
    example: '健康のために、甘い物を減らすことにした。',
    exampleZh: '為了健康，決定減少甜食。',
    level: 'n3',
  },
  {
    id: 'n3-card-055',
    term: '育てる',
    reading: 'そだてる',
    pos: '動詞',
    zh: '養育；栽培',
    example: 'ベランダで小さなトマトを育てています。',
    exampleZh: '在陽台上種著小小的番茄。',
    level: 'n3',
  },
  {
    id: 'n3-card-056',
    term: '進める',
    reading: 'すすめる',
    pos: '動詞',
    zh: '推進；進行',
    example: '計画どおりに準備を進めてください。',
    exampleZh: '請按照計畫進行準備。',
    level: 'n3',
  },
  {
    id: 'n3-card-057',
    term: '済ませる',
    reading: 'すませる',
    pos: '動詞',
    zh: '辦完；解決',
    example: '昼ご飯はコンビニのおにぎりで済ませた。',
    exampleZh: '午餐用超商飯糰打發了。',
    level: 'n3',
  },
  {
    id: 'n3-card-058',
    term: '気づく',
    reading: 'きづく',
    pos: '動詞',
    zh: '察覺；注意到',
    example: '家に帰ってから、傘を忘れたことに気づいた。',
    exampleZh: '回到家後才發現忘了帶傘。',
    level: 'n3',
  },
  {
    id: 'n3-card-059',
    term: '迷う',
    reading: 'まよう',
    pos: '動詞',
    zh: '猶豫；迷路',
    example: 'どちらの色を買うか、ずっと迷っている。',
    exampleZh: '一直在猶豫要買哪個顏色。',
    level: 'n3',
  },
  {
    id: 'n3-card-060',
    term: '悩む',
    reading: 'なやむ',
    pos: '動詞',
    zh: '煩惱；苦惱',
    example: '転職するかどうか、一人で悩んでいた。',
    exampleZh: '一個人煩惱著要不要換工作。',
    level: 'n3',
  },
  {
    id: 'n3-card-061',
    term: '頼る',
    reading: 'たよる',
    pos: '動詞',
    zh: '依靠；仰賴',
    example: '困ったときは、一人で悩まないで周りの人に頼ってください。',
    exampleZh: '遇到困難時，別獨自煩惱，請依靠身邊的人。',
    level: 'n3',
  },
  {
    id: 'n3-card-062',
    term: '褒める',
    reading: 'ほめる',
    pos: '動詞',
    zh: '稱讚；表揚',
    example: '発表がよかったと、部長に褒められた。',
    exampleZh: '被部長稱讚簡報做得好。',
    level: 'n3',
  },
  {
    id: 'n3-card-063',
    term: '叱る',
    reading: 'しかる',
    pos: '動詞',
    zh: '責罵；訓斥',
    example: '遅刻して、また課長に叱られてしまった。',
    exampleZh: '遲到又被課長罵了。',
    level: 'n3',
  },
  {
    id: 'n3-card-064',
    term: '謝る',
    reading: 'あやまる',
    pos: '動詞',
    zh: '道歉',
    example: '約束を破ってしまったので、彼に謝った。',
    exampleZh: '因為失約了，向他道了歉。',
    level: 'n3',
  },
  {
    id: 'n3-card-065',
    term: '稼ぐ',
    reading: 'かせぐ',
    pos: '動詞',
    zh: '賺錢',
    example: '夏休みにアルバイトをして、旅行の費用を稼いだ。',
    exampleZh: '暑假打工賺了旅行的費用。',
    level: 'n3',
  },
  {
    id: 'n3-card-066',
    term: '雇う',
    reading: 'やとう',
    pos: '動詞',
    zh: '雇用',
    example: '店が忙しくなったので、新しいスタッフを雇うことにした。',
    exampleZh: '因為店裡變忙了，決定雇用新員工。',
    level: 'n3',
  },
  {
    id: 'n3-card-067',
    term: '支払う',
    reading: 'しはらう',
    pos: '動詞',
    zh: '支付',
    example: '料金は月末までに支払ってください。',
    exampleZh: '費用請在月底前支付。',
    level: 'n3',
  },
  {
    id: 'n3-card-068',
    term: '取り消す',
    reading: 'とりけす',
    pos: '動詞',
    zh: '取消',
    example: '急に都合が悪くなり、ホテルの予約を取り消した。',
    exampleZh: '突然不方便，取消了飯店的預約。',
    level: 'n3',
  },
  // ==================== い形容詞 ====================
  {
    id: 'n3-card-069',
    term: '詳しい',
    reading: 'くわしい',
    pos: 'い形容詞',
    zh: '詳細的；熟悉的',
    example: '彼はこの町の歴史に詳しい。',
    exampleZh: '他對這個城鎮的歷史很熟。',
    level: 'n3',
  },
  {
    id: 'n3-card-070',
    term: '細かい',
    reading: 'こまかい',
    pos: 'い形容詞',
    zh: '細小的；仔細的',
    example: '契約書は細かい字までよく読んでください。',
    exampleZh: '契約書連細小的字也請仔細閱讀。',
    level: 'n3',
  },
  {
    id: 'n3-card-071',
    term: '激しい',
    reading: 'はげしい',
    pos: 'い形容詞',
    zh: '激烈的；猛烈的',
    example: '午後から激しい雨が降り始めた。',
    exampleZh: '下午開始下起了猛烈的雨。',
    level: 'n3',
  },
  {
    id: 'n3-card-072',
    term: '悔しい',
    reading: 'くやしい',
    pos: 'い形容詞',
    zh: '不甘心的；懊悔的',
    example: 'あと一点で合格だったので、本当に悔しい。',
    exampleZh: '只差一分就及格了，真的很不甘心。',
    level: 'n3',
  },
  {
    id: 'n3-card-073',
    term: '羨ましい',
    reading: 'うらやましい',
    pos: 'い形容詞',
    zh: '令人羨慕的',
    example: '毎年海外旅行に行ける人が羨ましい。',
    exampleZh: '真羨慕每年都能出國旅行的人。',
    level: 'n3',
  },
  {
    id: 'n3-card-074',
    term: 'もったいない',
    reading: 'もったいない',
    pos: 'い形容詞',
    zh: '可惜的；浪費的',
    example: 'まだ食べられるのに捨てるなんて、もったいない。',
    exampleZh: '明明還能吃卻丟掉，太浪費了。',
    level: 'n3',
  },
  {
    id: 'n3-card-075',
    term: '親しい',
    reading: 'したしい',
    pos: 'い形容詞',
    zh: '親近的；要好的',
    example: '彼女とは高校時代から親しい友人です。',
    exampleZh: '我和她是從高中時代就要好的朋友。',
    level: 'n3',
  },
  {
    id: 'n3-card-076',
    term: 'ずうずうしい',
    reading: 'ずうずうしい',
    pos: 'い形容詞',
    zh: '厚臉皮的',
    example: '並んでいる列に割り込むなんて、ずうずうしい人だ。',
    exampleZh: '竟然插隊，真是厚臉皮的人。',
    level: 'n3',
  },
  // ==================== な形容詞 ====================
  {
    id: 'n3-card-077',
    term: '順調',
    reading: 'じゅんちょう',
    pos: 'な形容詞',
    zh: '順利',
    example: '新しいプロジェクトは順調に進んでいます。',
    exampleZh: '新專案進行得很順利。',
    level: 'n3',
  },
  {
    id: 'n3-card-078',
    term: '素直',
    reading: 'すなお',
    pos: 'な形容詞',
    zh: '坦率；老實',
    example: '彼女は注意されても素直に聞ける人だ。',
    exampleZh: '她是被提醒也能坦率接受的人。',
    level: 'n3',
  },
  {
    id: 'n3-card-079',
    term: '立派',
    reading: 'りっぱ',
    pos: 'な形容詞',
    zh: '出色；氣派',
    example: '駅前に立派なホールが完成した。',
    exampleZh: '車站前蓋好了一座氣派的會館。',
    level: 'n3',
  },
  {
    id: 'n3-card-080',
    term: '正直',
    reading: 'しょうじき',
    pos: 'な形容詞',
    zh: '誠實；老實',
    example: '失敗したときは、正直に話したほうがいい。',
    exampleZh: '失敗的時候，還是老實說出來比較好。',
    level: 'n3',
  },
  {
    id: 'n3-card-081',
    term: '面倒',
    reading: 'めんどう',
    pos: 'な形容詞',
    zh: '麻煩；費事',
    example: '手続きが面倒で、申し込むのをやめてしまった。',
    exampleZh: '手續太麻煩，就放棄申請了。',
    level: 'n3',
  },
  {
    id: 'n3-card-082',
    term: '意外',
    reading: 'いがい',
    pos: 'な形容詞',
    zh: '意外；出乎意料',
    example: '静かな彼がカラオケが好きだとは意外だった。',
    exampleZh: '文靜的他竟然喜歡唱KTV，真是出乎意料。',
    level: 'n3',
  },
  {
    id: 'n3-card-083',
    term: '確実',
    reading: 'かくじつ',
    pos: 'な形容詞',
    zh: '確實；可靠',
    example: '席を取りたいなら、予約するのが確実です。',
    exampleZh: '想要有位子的話，預約最可靠。',
    level: 'n3',
  },
  {
    id: 'n3-card-084',
    term: '贅沢',
    reading: 'ぜいたく',
    pos: 'な形容詞',
    zh: '奢侈',
    example: 'ボーナスが出たので、今夜は贅沢な食事をしよう。',
    exampleZh: '因為發了獎金，今晚就吃頓奢侈的大餐吧。',
    level: 'n3',
  },
  // ==================== 副詞 ====================
  {
    id: 'n3-card-085',
    term: 'うっかり',
    reading: 'うっかり',
    pos: '副詞',
    zh: '不小心；一時疏忽',
    example: 'うっかりして、大事な書類を家に忘れてきた。',
    exampleZh: '一時疏忽，把重要文件忘在家裡了。',
    level: 'n3',
  },
  {
    id: 'n3-card-086',
    term: 'さっそく',
    reading: 'さっそく',
    pos: '副詞',
    zh: '立刻；馬上',
    example: '新しい炊飯器が届いたので、さっそく使ってみた。',
    exampleZh: '新的電子鍋送到了，馬上就試用看看。',
    level: 'n3',
  },
  {
    id: 'n3-card-087',
    term: 'しばらく',
    reading: 'しばらく',
    pos: '副詞',
    zh: '暫時；好一陣子',
    example: '工事のため、この道はしばらく通れません。',
    exampleZh: '因為施工，這條路暫時無法通行。',
    level: 'n3',
  },
  {
    id: 'n3-card-088',
    term: '思わず',
    reading: 'おもわず',
    pos: '副詞',
    zh: '不由得；不禁',
    example: 'おかしくて、思わず笑ってしまった。',
    exampleZh: '太好笑了，不禁笑了出來。',
    level: 'n3',
  },
  {
    id: 'n3-card-089',
    term: '相変わらず',
    reading: 'あいかわらず',
    pos: '副詞',
    zh: '依然；一如往常',
    example: 'あの店は相変わらず混んでいますね。',
    exampleZh: '那家店還是一樣擁擠呢。',
    level: 'n3',
  },
  {
    id: 'n3-card-090',
    term: 'めったに',
    reading: 'めったに',
    pos: '副詞',
    zh: '很少（後接否定）',
    example: '父は忙しくて、めったに家で夕食を食べない。',
    exampleZh: '爸爸很忙，很少在家吃晚餐。',
    level: 'n3',
  },
  {
    id: 'n3-card-091',
    term: 'ぐっすり',
    reading: 'ぐっすり',
    pos: '副詞',
    zh: '熟睡貌',
    example: '疲れていたので、昨夜はぐっすり眠れた。',
    exampleZh: '因為很累，昨晚睡得很熟。',
    level: 'n3',
  },
  {
    id: 'n3-card-092',
    term: 'わざと',
    reading: 'わざと',
    pos: '副詞',
    zh: '故意地',
    example: '弟はわざと負けて、妹を喜ばせた。',
    exampleZh: '弟弟故意輸掉，讓妹妹開心。',
    level: 'n3',
  },
  {
    id: 'n3-card-093',
    term: 'いよいよ',
    reading: 'いよいよ',
    pos: '副詞',
    zh: '終於；即將',
    example: 'いよいよ明日、新しい店がオープンする。',
    exampleZh: '新店終於要在明天開幕了。',
    level: 'n3',
  },
  {
    id: 'n3-card-094',
    term: 'とりあえず',
    reading: 'とりあえず',
    pos: '副詞',
    zh: '姑且；先',
    example: '細かいことは後で決めて、とりあえず日程だけ押さえよう。',
    exampleZh: '細節之後再定，先把日期敲定吧。',
    level: 'n3',
  },
  // ==================== 表現 ====================
  {
    id: 'n3-card-095',
    term: 'お疲れ様です',
    reading: 'おつかれさまです',
    pos: '表現',
    zh: '辛苦了（職場問候）',
    example: 'お疲れ様です。先ほどの資料をお送りします。',
    exampleZh: '辛苦了。剛才的資料寄給您。',
    level: 'n3',
  },
  {
    id: 'n3-card-096',
    term: 'お世話になっております',
    reading: 'おせわになっております',
    pos: '表現',
    zh: '承蒙關照（商務問候）',
    example: 'いつもお世話になっております。山田商事の林です。',
    exampleZh: '一直承蒙您的關照。我是山田商事的林。',
    level: 'n3',
  },
  {
    id: 'n3-card-097',
    term: '恐れ入りますが',
    reading: 'おそれいりますが',
    pos: '表現',
    zh: '不好意思（鄭重開場）',
    example: '恐れ入りますが、こちらにお名前をご記入ください。',
    exampleZh: '不好意思，請在這裡填寫您的大名。',
    level: 'n3',
  },
  {
    id: 'n3-card-098',
    term: '申し訳ありません',
    reading: 'もうしわけありません',
    pos: '表現',
    zh: '非常抱歉',
    example: '申し訳ありません。ただいま確認いたします。',
    exampleZh: '非常抱歉，我馬上為您確認。',
    level: 'n3',
  },
  {
    id: 'n3-card-099',
    term: 'お先に失礼します',
    reading: 'おさきにしつれいします',
    pos: '表現',
    zh: '我先走一步（下班）',
    example: '今日の仕事は終わったので、お先に失礼します。',
    exampleZh: '今天的工作結束了，我先走一步。',
    level: 'n3',
  },
  {
    id: 'n3-card-100',
    term: 'よろしくお伝えください',
    reading: 'よろしくおつたえください',
    pos: '表現',
    zh: '請代我問好',
    example: '奥様にもどうぞよろしくお伝えください。',
    exampleZh: '也請代我向您夫人問好。',
    level: 'n3',
  },
]
