import type { VocabCard } from '../types'

export const cards: VocabCard[] = [
  // ==================== 名詞（心情・預定） ====================
  {
    id: 'n4-card-001',
    term: '気分',
    reading: 'きぶん',
    pos: '名詞',
    zh: '心情；身體狀況',
    example: '今日は 気分が いいので、散歩に 行きます。',
    exampleZh: '今天心情很好，所以去散步。',
    level: 'n4',
  },
  {
    id: 'n4-card-002',
    term: '気持ち',
    reading: 'きもち',
    pos: '名詞',
    zh: '心情；感受',
    example: 'プレゼントを もらって、うれしい 気持ちに なりました。',
    exampleZh: '收到禮物，心情變得很開心。',
    level: 'n4',
  },
  {
    id: 'n4-card-003',
    term: '予定',
    reading: 'よてい',
    pos: '名詞',
    zh: '預定；計畫',
    example: '来週の 予定を 手帳に 書きました。',
    exampleZh: '把下週的預定寫進了手帳。',
    level: 'n4',
  },
  {
    id: 'n4-card-004',
    term: '用事',
    reading: 'ようじ',
    pos: '名詞',
    zh: '要辦的事',
    example: '用事が あるので、先に 帰ります。',
    exampleZh: '因為有事要辦，先回去了。',
    level: 'n4',
  },
  {
    id: 'n4-card-005',
    term: '約束',
    reading: 'やくそく',
    pos: '名詞',
    zh: '約定',
    example: '友達との 約束を 忘れて しまいました。',
    exampleZh: '不小心忘了和朋友的約定。',
    level: 'n4',
  },
  {
    id: 'n4-card-006',
    term: '都合',
    reading: 'つごう',
    pos: '名詞',
    zh: '方便與否；情況',
    example: '明日は 都合が 悪くて、行けません。',
    exampleZh: '明天不方便，沒辦法去。',
    level: 'n4',
  },
  {
    id: 'n4-card-007',
    term: '経験',
    reading: 'けいけん',
    pos: '名詞',
    zh: '經驗',
    example: '外国で 働いた 経験が あります。',
    exampleZh: '有在國外工作過的經驗。',
    level: 'n4',
  },
  {
    id: 'n4-card-008',
    term: '趣味',
    reading: 'しゅみ',
    pos: '名詞',
    zh: '嗜好',
    example: '私の 趣味は 山に 登る ことです。',
    exampleZh: '我的嗜好是爬山。',
    level: 'n4',
  },
  {
    id: 'n4-card-009',
    term: '興味',
    reading: 'きょうみ',
    pos: '名詞',
    zh: '興趣；關注',
    example: '日本の 歴史に 興味が あります。',
    exampleZh: '對日本歷史有興趣。',
    level: 'n4',
  },
  {
    id: 'n4-card-010',
    term: '説明',
    reading: 'せつめい',
    pos: '名詞',
    zh: '說明',
    example: '先生の 説明は とても わかりやすいです。',
    exampleZh: '老師的說明非常容易懂。',
    level: 'n4',
  },
  {
    id: 'n4-card-011',
    term: '準備',
    reading: 'じゅんび',
    pos: '名詞',
    zh: '準備',
    example: '旅行の 準備は もう できましたか。',
    exampleZh: '旅行的準備已經好了嗎？',
    level: 'n4',
  },
  {
    id: 'n4-card-012',
    term: '練習',
    reading: 'れんしゅう',
    pos: '名詞',
    zh: '練習',
    example: '毎日 ピアノの 練習を して います。',
    exampleZh: '每天都在練習鋼琴。',
    level: 'n4',
  },
  {
    id: 'n4-card-013',
    term: '試合',
    reading: 'しあい',
    pos: '名詞',
    zh: '比賽',
    example: '日曜日に サッカーの 試合が あります。',
    exampleZh: '星期天有足球比賽。',
    level: 'n4',
  },
  {
    id: 'n4-card-014',
    term: '予約',
    reading: 'よやく',
    pos: '名詞',
    zh: '預約',
    example: 'レストランを 予約して おきました。',
    exampleZh: '事先預約好了餐廳。',
    level: 'n4',
  },
  {
    id: 'n4-card-015',
    term: '理由',
    reading: 'りゆう',
    pos: '名詞',
    zh: '理由',
    example: '遅れた 理由を 教えて ください。',
    exampleZh: '請告訴我遲到的理由。',
    level: 'n4',
  },
  {
    id: 'n4-card-016',
    term: '原因',
    reading: 'げんいん',
    pos: '名詞',
    zh: '原因',
    example: '火事の 原因は まだ わかりません。',
    exampleZh: '火災的原因還不清楚。',
    level: 'n4',
  },
  {
    id: 'n4-card-017',
    term: '意見',
    reading: 'いけん',
    pos: '名詞',
    zh: '意見',
    example: '会議で 自分の 意見を 言いました。',
    exampleZh: '在會議上說了自己的意見。',
    level: 'n4',
  },
  {
    id: 'n4-card-018',
    term: '相談',
    reading: 'そうだん',
    pos: '名詞',
    zh: '商量；諮詢',
    example: '進学の ことを 先生に 相談しました。',
    exampleZh: '升學的事和老師商量了。',
    level: 'n4',
  },
  {
    id: 'n4-card-019',
    term: '紹介',
    reading: 'しょうかい',
    pos: '名詞',
    zh: '介紹',
    example: '友達に いい 店を 紹介して もらいました。',
    exampleZh: '請朋友介紹了不錯的店。',
    level: 'n4',
  },
  {
    id: 'n4-card-020',
    term: '招待',
    reading: 'しょうたい',
    pos: '名詞',
    zh: '邀請；招待',
    example: '結婚式に 招待されました。',
    exampleZh: '受邀參加婚禮。',
    level: 'n4',
  },
  // ==================== 名詞（生活・社會） ====================
  {
    id: 'n4-card-021',
    term: '会議',
    reading: 'かいぎ',
    pos: '名詞',
    zh: '會議',
    example: '会議は 三時から 始まります。',
    exampleZh: '會議從三點開始。',
    level: 'n4',
  },
  {
    id: 'n4-card-022',
    term: '受付',
    reading: 'うけつけ',
    pos: '名詞',
    zh: '櫃檯；受理',
    example: '受付で 名前を 書いて ください。',
    exampleZh: '請在櫃檯寫下名字。',
    level: 'n4',
  },
  {
    id: 'n4-card-023',
    term: '案内',
    reading: 'あんない',
    pos: '名詞',
    zh: '導覽；引導',
    example: 'お客さんを 工場の 中を 案内しました。',
    exampleZh: '帶客人參觀了工廠內部。',
    level: 'n4',
  },
  {
    id: 'n4-card-024',
    term: '住所',
    reading: 'じゅうしょ',
    pos: '名詞',
    zh: '地址',
    example: 'ここに 住所と 名前を 書いて ください。',
    exampleZh: '請在這裡寫下地址和姓名。',
    level: 'n4',
  },
  {
    id: 'n4-card-025',
    term: '事故',
    reading: 'じこ',
    pos: '名詞',
    zh: '事故',
    example: '事故で 道が 込んで います。',
    exampleZh: '因為事故，路上塞車。',
    level: 'n4',
  },
  {
    id: 'n4-card-026',
    term: '地震',
    reading: 'じしん',
    pos: '名詞',
    zh: '地震',
    example: 'ゆうべ、大きい 地震が ありました。',
    exampleZh: '昨晚發生了大地震。',
    level: 'n4',
  },
  {
    id: 'n4-card-027',
    term: '台風',
    reading: 'たいふう',
    pos: '名詞',
    zh: '颱風',
    example: '台風で 学校が 休みに なりました。',
    exampleZh: '因為颱風，學校停課了。',
    level: 'n4',
  },
  {
    id: 'n4-card-028',
    term: '季節',
    reading: 'きせつ',
    pos: '名詞',
    zh: '季節',
    example: '一番 好きな 季節は 秋です。',
    exampleZh: '最喜歡的季節是秋天。',
    level: 'n4',
  },
  {
    id: 'n4-card-029',
    term: '景色',
    reading: 'けしき',
    pos: '名詞',
    zh: '景色',
    example: '山の 上からの 景色は すばらしかったです。',
    exampleZh: '從山上看到的景色非常棒。',
    level: 'n4',
  },
  {
    id: 'n4-card-030',
    term: '空気',
    reading: 'くうき',
    pos: '名詞',
    zh: '空氣',
    example: '田舎は 空気が きれいです。',
    exampleZh: '鄉下的空氣很乾淨。',
    level: 'n4',
  },
  {
    id: 'n4-card-031',
    term: '港',
    reading: 'みなと',
    pos: '名詞',
    zh: '港口',
    example: '港に 大きな 船が 着きました。',
    exampleZh: '大船抵達了港口。',
    level: 'n4',
  },
  {
    id: 'n4-card-032',
    term: '島',
    reading: 'しま',
    pos: '名詞',
    zh: '島嶼',
    example: 'この 島には 珍しい 鳥が います。',
    exampleZh: '這座島上有罕見的鳥。',
    level: 'n4',
  },
  {
    id: 'n4-card-033',
    term: '湖',
    reading: 'みずうみ',
    pos: '名詞',
    zh: '湖',
    example: '湖の 水は とても 冷たかったです。',
    exampleZh: '湖水非常冰冷。',
    level: 'n4',
  },
  {
    id: 'n4-card-034',
    term: '森',
    reading: 'もり',
    pos: '名詞',
    zh: '森林',
    example: '森の 中を ゆっくり 歩きました。',
    exampleZh: '在森林裡慢慢地走了走。',
    level: 'n4',
  },
  {
    id: 'n4-card-035',
    term: '星',
    reading: 'ほし',
    pos: '名詞',
    zh: '星星',
    example: '今夜は 星が きれいに 見えます。',
    exampleZh: '今晚星星看起來很美。',
    level: 'n4',
  },
  {
    id: 'n4-card-036',
    term: '昔',
    reading: 'むかし',
    pos: '名詞',
    zh: '從前；很久以前',
    example: 'この 町は 昔、小さな 村でした。',
    exampleZh: '這個城鎮從前是個小村莊。',
    level: 'n4',
  },
  {
    id: 'n4-card-037',
    term: '将来',
    reading: 'しょうらい',
    pos: '名詞',
    zh: '將來',
    example: '将来は 医者に なりたいです。',
    exampleZh: '將來想當醫生。',
    level: 'n4',
  },
  {
    id: 'n4-card-038',
    term: '習慣',
    reading: 'しゅうかん',
    pos: '名詞',
    zh: '習慣',
    example: '早く 起きる 習慣を つけたいです。',
    exampleZh: '想養成早起的習慣。',
    level: 'n4',
  },
  // ==================== 動詞 ====================
  {
    id: 'n4-card-039',
    term: '遅れる',
    reading: 'おくれる',
    pos: '動詞',
    zh: '遲到；誤點',
    example: '電車が 遅れて、会議に 間に合いませんでした。',
    exampleZh: '電車誤點，沒趕上會議。',
    level: 'n4',
  },
  {
    id: 'n4-card-040',
    term: '急ぐ',
    reading: 'いそぐ',
    pos: '動詞',
    zh: '趕快；急著做',
    example: '時間が ないので、急ぎましょう。',
    exampleZh: '沒時間了，我們快一點吧。',
    level: 'n4',
  },
  {
    id: 'n4-card-041',
    term: '決める',
    reading: 'きめる',
    pos: '動詞',
    zh: '決定',
    example: '旅行の 行き先を 決めました。',
    exampleZh: '決定了旅行的目的地。',
    level: 'n4',
  },
  {
    id: 'n4-card-042',
    term: '続ける',
    reading: 'つづける',
    pos: '動詞',
    zh: '繼續',
    example: '日本語の 勉強を 続けて います。',
    exampleZh: '持續在學日語。',
    level: 'n4',
  },
  {
    id: 'n4-card-043',
    term: '調べる',
    reading: 'しらべる',
    pos: '動詞',
    zh: '查詢；調查',
    example: '言葉の 意味を 辞書で 調べました。',
    exampleZh: '用字典查了單字的意思。',
    level: 'n4',
  },
  {
    id: 'n4-card-044',
    term: '探す',
    reading: 'さがす',
    pos: '動詞',
    zh: '尋找',
    example: '新しい アパートを 探して います。',
    exampleZh: '正在找新的公寓。',
    level: 'n4',
  },
  {
    id: 'n4-card-045',
    term: '見つける',
    reading: 'みつける',
    pos: '動詞',
    zh: '找到；發現',
    example: 'なくした かぎを やっと 見つけました。',
    exampleZh: '終於找到弄丟的鑰匙了。',
    level: 'n4',
  },
  {
    id: 'n4-card-046',
    term: '拾う',
    reading: 'ひろう',
    pos: '動詞',
    zh: '撿拾',
    example: '公園で ごみを 拾いました。',
    exampleZh: '在公園撿了垃圾。',
    level: 'n4',
  },
  {
    id: 'n4-card-047',
    term: '落とす',
    reading: 'おとす',
    pos: '動詞',
    zh: '弄掉；使落下',
    example: '財布を どこかで 落として しまいました。',
    exampleZh: '不小心把錢包掉在某個地方了。',
    level: 'n4',
  },
  {
    id: 'n4-card-048',
    term: '壊れる',
    reading: 'こわれる',
    pos: '動詞',
    zh: '壞掉',
    example: 'パソコンが 壊れて、仕事が できません。',
    exampleZh: '電腦壞了，沒辦法工作。',
    level: 'n4',
  },
  {
    id: 'n4-card-049',
    term: '直す',
    reading: 'なおす',
    pos: '動詞',
    zh: '修理；改正',
    example: '父は 自分で 自転車を 直しました。',
    exampleZh: '爸爸自己修好了腳踏車。',
    level: 'n4',
  },
  {
    id: 'n4-card-050',
    term: '慣れる',
    reading: 'なれる',
    pos: '動詞',
    zh: '習慣；適應',
    example: '新しい 生活に だんだん 慣れて きました。',
    exampleZh: '漸漸適應了新生活。',
    level: 'n4',
  },
  {
    id: 'n4-card-051',
    term: '覚える',
    reading: 'おぼえる',
    pos: '動詞',
    zh: '記住；學會',
    example: '毎日 新しい 言葉を 五つ 覚えます。',
    exampleZh: '每天記五個新單字。',
    level: 'n4',
  },
  {
    id: 'n4-card-052',
    term: '忘れる',
    reading: 'わすれる',
    pos: '動詞',
    zh: '忘記；遺忘',
    example: '傘を 電車に 忘れて しまいました。',
    exampleZh: '不小心把傘忘在電車上了。',
    level: 'n4',
  },
  {
    id: 'n4-card-053',
    term: '思い出す',
    reading: 'おもいだす',
    pos: '動詞',
    zh: '想起',
    example: 'この 歌を 聞くと、子どもの ころを 思い出します。',
    exampleZh: '一聽到這首歌，就想起小時候。',
    level: 'n4',
  },
  {
    id: 'n4-card-054',
    term: '届く',
    reading: 'とどく',
    pos: '動詞',
    zh: '送達；寄到',
    example: '国の 母から 手紙が 届きました。',
    exampleZh: '收到了家鄉母親寄來的信。',
    level: 'n4',
  },
  {
    id: 'n4-card-055',
    term: '迎える',
    reading: 'むかえる',
    pos: '動詞',
    zh: '迎接',
    example: '空港へ 友達を 迎えに 行きます。',
    exampleZh: '去機場接朋友。',
    level: 'n4',
  },
  {
    id: 'n4-card-056',
    term: '運ぶ',
    reading: 'はこぶ',
    pos: '動詞',
    zh: '搬運',
    example: '重い 荷物を 二階へ 運びました。',
    exampleZh: '把很重的行李搬到了二樓。',
    level: 'n4',
  },
  {
    id: 'n4-card-057',
    term: '渡る',
    reading: 'わたる',
    pos: '動詞',
    zh: '越過；過（橋、馬路）',
    example: 'この 橋を 渡ると、海が 見えます。',
    exampleZh: '過了這座橋，就能看到海。',
    level: 'n4',
  },
  {
    id: 'n4-card-058',
    term: '通う',
    reading: 'かよう',
    pos: '動詞',
    zh: '通勤；通學',
    example: 'バスで 学校に 通って います。',
    exampleZh: '搭公車上下學。',
    level: 'n4',
  },
  {
    id: 'n4-card-059',
    term: '集める',
    reading: 'あつめる',
    pos: '動詞',
    zh: '收集',
    example: '兄は 古い 切手を 集めて います。',
    exampleZh: '哥哥在收集舊郵票。',
    level: 'n4',
  },
  {
    id: 'n4-card-060',
    term: '増える',
    reading: 'ふえる',
    pos: '動詞',
    zh: '增加',
    example: 'この 町は 人口が 増えて います。',
    exampleZh: '這個城鎮的人口持續增加。',
    level: 'n4',
  },
  {
    id: 'n4-card-061',
    term: '減る',
    reading: 'へる',
    pos: '動詞',
    zh: '減少',
    example: '最近、体重が 少し 減りました。',
    exampleZh: '最近體重稍微減輕了。',
    level: 'n4',
  },
  {
    id: 'n4-card-062',
    term: '変わる',
    reading: 'かわる',
    pos: '動詞',
    zh: '改變；變化',
    example: '信号が 赤に 変わりました。',
    exampleZh: '號誌燈變成紅色了。',
    level: 'n4',
  },
  {
    id: 'n4-card-063',
    term: '手伝う',
    reading: 'てつだう',
    pos: '動詞',
    zh: '幫忙',
    example: '母の 料理を 手伝いました。',
    exampleZh: '幫媽媽做了菜。',
    level: 'n4',
  },
  {
    id: 'n4-card-064',
    term: '頑張る',
    reading: 'がんばる',
    pos: '動詞',
    zh: '努力；加油',
    example: '来月の 試験に 向けて 頑張って います。',
    exampleZh: '正朝著下個月的考試努力。',
    level: 'n4',
  },
  {
    id: 'n4-card-065',
    term: '驚く',
    reading: 'おどろく',
    pos: '動詞',
    zh: '吃驚',
    example: '急な ニュースに みんな 驚きました。',
    exampleZh: '大家都對突如其來的消息感到吃驚。',
    level: 'n4',
  },
  {
    id: 'n4-card-066',
    term: '誘う',
    reading: 'さそう',
    pos: '動詞',
    zh: '邀約',
    example: '同僚を 食事に 誘いました。',
    exampleZh: '約了同事去吃飯。',
    level: 'n4',
  },
  // ==================== い形容詞 ====================
  {
    id: 'n4-card-067',
    term: '嬉しい',
    reading: 'うれしい',
    pos: 'い形容詞',
    zh: '高興的',
    example: '合格の 知らせを 聞いて、とても 嬉しいです。',
    exampleZh: '聽到合格的通知，非常高興。',
    level: 'n4',
  },
  {
    id: 'n4-card-068',
    term: '悲しい',
    reading: 'かなしい',
    pos: 'い形容詞',
    zh: '悲傷的',
    example: '悲しい 映画を 見て、泣いて しまいました。',
    exampleZh: '看了悲傷的電影，忍不住哭了。',
    level: 'n4',
  },
  {
    id: 'n4-card-069',
    term: '寂しい',
    reading: 'さびしい',
    pos: 'い形容詞',
    zh: '寂寞的',
    example: '家族と 離れて 住むのは 寂しいです。',
    exampleZh: '和家人分開住很寂寞。',
    level: 'n4',
  },
  {
    id: 'n4-card-070',
    term: '恥ずかしい',
    reading: 'はずかしい',
    pos: 'い形容詞',
    zh: '害羞的；難為情的',
    example: '人の 前で 歌うのは 恥ずかしいです。',
    exampleZh: '在別人面前唱歌很難為情。',
    level: 'n4',
  },
  {
    id: 'n4-card-071',
    term: '眠い',
    reading: 'ねむい',
    pos: 'い形容詞',
    zh: '睏的；想睡的',
    example: 'ゆうべ あまり 寝られなくて、今 眠いです。',
    exampleZh: '昨晚沒睡好，現在很睏。',
    level: 'n4',
  },
  {
    id: 'n4-card-072',
    term: '珍しい',
    reading: 'めずらしい',
    pos: 'い形容詞',
    zh: '罕見的；稀奇的',
    example: 'この 動物園には 珍しい 動物が います。',
    exampleZh: '這座動物園裡有罕見的動物。',
    level: 'n4',
  },
  {
    id: 'n4-card-073',
    term: '優しい',
    reading: 'やさしい',
    pos: 'い形容詞',
    zh: '溫柔的；體貼的',
    example: '田中さんは だれにでも 優しいです。',
    exampleZh: '田中對任何人都很溫柔。',
    level: 'n4',
  },
  {
    id: 'n4-card-074',
    term: '厳しい',
    reading: 'きびしい',
    pos: 'い形容詞',
    zh: '嚴格的',
    example: 'コーチは 練習に とても 厳しいです。',
    exampleZh: '教練對練習非常嚴格。',
    level: 'n4',
  },
  {
    id: 'n4-card-075',
    term: '深い',
    reading: 'ふかい',
    pos: 'い形容詞',
    zh: '深的',
    example: 'この 川は 深いので、気を つけて ください。',
    exampleZh: '這條河很深，請小心。',
    level: 'n4',
  },
  {
    id: 'n4-card-076',
    term: '苦い',
    reading: 'にがい',
    pos: 'い形容詞',
    zh: '苦的',
    example: 'この 薬は 苦くて、飲みにくいです。',
    exampleZh: '這種藥很苦，很難吞。',
    level: 'n4',
  },
  // ==================== な形容詞 ====================
  {
    id: 'n4-card-077',
    term: '安全',
    reading: 'あんぜん',
    pos: 'な形容詞',
    zh: '安全',
    example: '夜でも この 道は 安全です。',
    exampleZh: '即使晚上，這條路也很安全。',
    level: 'n4',
  },
  {
    id: 'n4-card-078',
    term: '危険',
    reading: 'きけん',
    pos: 'な形容詞',
    zh: '危險',
    example: 'ここで 泳ぐのは 危険です。',
    exampleZh: '在這裡游泳很危險。',
    level: 'n4',
  },
  {
    id: 'n4-card-079',
    term: '大切',
    reading: 'たいせつ',
    pos: 'な形容詞',
    zh: '重要；珍惜',
    example: '家族との 時間を 大切に して います。',
    exampleZh: '珍惜與家人相處的時光。',
    level: 'n4',
  },
  {
    id: 'n4-card-080',
    term: '熱心',
    reading: 'ねっしん',
    pos: 'な形容詞',
    zh: '熱衷；認真投入',
    example: '彼は 熱心に 日本語を 勉強して います。',
    exampleZh: '他很認真地在學日語。',
    level: 'n4',
  },
  {
    id: 'n4-card-081',
    term: '丁寧',
    reading: 'ていねい',
    pos: 'な形容詞',
    zh: '有禮貌；細心',
    example: '店員は 丁寧に 説明して くれました。',
    exampleZh: '店員細心地為我說明。',
    level: 'n4',
  },
  {
    id: 'n4-card-082',
    term: '複雑',
    reading: 'ふくざつ',
    pos: 'な形容詞',
    zh: '複雜',
    example: 'この 問題は 複雑で、すぐには 答えられません。',
    exampleZh: '這個問題很複雜，沒辦法立刻回答。',
    level: 'n4',
  },
  {
    id: 'n4-card-083',
    term: '特別',
    reading: 'とくべつ',
    pos: 'な形容詞',
    zh: '特別',
    example: '今日は 特別な 日ですから、ケーキを 買いました。',
    exampleZh: '今天是特別的日子，所以買了蛋糕。',
    level: 'n4',
  },
  {
    id: 'n4-card-084',
    term: '真面目',
    reading: 'まじめ',
    pos: 'な形容詞',
    zh: '認真',
    example: '弟は 真面目に 宿題を して います。',
    exampleZh: '弟弟認真地在寫作業。',
    level: 'n4',
  },
  // ==================== 副詞 ====================
  {
    id: 'n4-card-085',
    term: 'やっと',
    reading: 'やっと',
    pos: '副詞',
    zh: '終於',
    example: 'レポートが やっと 終わりました。',
    exampleZh: '報告終於完成了。',
    level: 'n4',
  },
  {
    id: 'n4-card-086',
    term: 'なかなか',
    reading: 'なかなか',
    pos: '副詞',
    zh: '相當；（接否定）遲遲不',
    example: 'バスが なかなか 来ません。',
    exampleZh: '公車遲遲不來。',
    level: 'n4',
  },
  {
    id: 'n4-card-087',
    term: 'ずいぶん',
    reading: 'ずいぶん',
    pos: '副詞',
    zh: '相當；非常',
    example: '日本語が ずいぶん 上手に なりましたね。',
    exampleZh: '日語變得相當好了呢。',
    level: 'n4',
  },
  {
    id: 'n4-card-088',
    term: 'きっと',
    reading: 'きっと',
    pos: '副詞',
    zh: '一定',
    example: '明日は きっと 晴れるでしょう。',
    exampleZh: '明天一定會放晴吧。',
    level: 'n4',
  },
  {
    id: 'n4-card-089',
    term: 'ぜひ',
    reading: 'ぜひ',
    pos: '副詞',
    zh: '務必；一定要',
    example: 'ぜひ うちに 遊びに 来て ください。',
    exampleZh: '請務必來我家玩。',
    level: 'n4',
  },
  {
    id: 'n4-card-090',
    term: 'そろそろ',
    reading: 'そろそろ',
    pos: '副詞',
    zh: '差不多該',
    example: 'そろそろ 帰る 時間です。',
    exampleZh: '差不多是該回去的時間了。',
    level: 'n4',
  },
  {
    id: 'n4-card-091',
    term: 'だいぶ',
    reading: 'だいぶ',
    pos: '副詞',
    zh: '相當地；很',
    example: '病気は だいぶ よく なりました。',
    exampleZh: '病已經好了很多。',
    level: 'n4',
  },
  {
    id: 'n4-card-092',
    term: 'しっかり',
    reading: 'しっかり',
    pos: '副詞',
    zh: '好好地；牢牢地',
    example: '朝ごはんを しっかり 食べて ください。',
    exampleZh: '請好好地吃早餐。',
    level: 'n4',
  },
  {
    id: 'n4-card-093',
    term: '急に',
    reading: 'きゅうに',
    pos: '副詞',
    zh: '突然',
    example: '急に 雨が 降り出しました。',
    exampleZh: '突然下起雨來了。',
    level: 'n4',
  },
  // ==================== 表現 ====================
  {
    id: 'n4-card-094',
    term: 'おかげさまで',
    reading: 'おかげさまで',
    pos: '表現',
    zh: '託您的福',
    example: 'おかげさまで、元気に して います。',
    exampleZh: '託您的福，我過得很好。',
    level: 'n4',
  },
  {
    id: 'n4-card-095',
    term: 'お大事に',
    reading: 'おだいじに',
    pos: '表現',
    zh: '請保重（對病人說）',
    example: 'かぜですね。どうぞ お大事に。',
    exampleZh: '是感冒呢。請多保重。',
    level: 'n4',
  },
  {
    id: 'n4-card-096',
    term: 'おめでとうございます',
    reading: 'おめでとうございます',
    pos: '表現',
    zh: '恭喜',
    example: 'ご結婚、おめでとうございます。',
    exampleZh: '恭喜您結婚。',
    level: 'n4',
  },
  {
    id: 'n4-card-097',
    term: 'かしこまりました',
    reading: 'かしこまりました',
    pos: '表現',
    zh: '我明白了（謙敬說法）',
    example: '「コーヒーを お願いします。」「かしこまりました。」',
    exampleZh: '「請給我咖啡。」「好的，我明白了。」',
    level: 'n4',
  },
  {
    id: 'n4-card-098',
    term: 'お待たせしました',
    reading: 'おまたせしました',
    pos: '表現',
    zh: '讓您久等了',
    example: 'お待たせしました。こちらが メニューです。',
    exampleZh: '讓您久等了，這是菜單。',
    level: 'n4',
  },
  {
    id: 'n4-card-099',
    term: 'ごちそうさまでした',
    reading: 'ごちそうさまでした',
    pos: '表現',
    zh: '多謝款待',
    example: 'ごちそうさまでした。とても おいしかったです。',
    exampleZh: '多謝款待，非常好吃。',
    level: 'n4',
  },
  {
    id: 'n4-card-100',
    term: 'いってらっしゃい',
    reading: 'いってらっしゃい',
    pos: '表現',
    zh: '慢走（送人出門）',
    example: '「行って きます。」「いってらっしゃい。」',
    exampleZh: '「我出門了。」「路上小心。」',
    level: 'n4',
  },
]
