import type { VocabCard } from '../types'

export const cards: VocabCard[] = [
  // ==================== 名詞（時間） ====================
  {
    id: 'n5-card-001',
    term: '朝',
    reading: 'あさ',
    pos: '名詞',
    zh: '早上；早晨',
    example: '朝は いつも 六時に 起きます。',
    exampleZh: '早上總是六點起床。',
    level: 'n5',
  },
  {
    id: 'n5-card-002',
    term: '今日',
    reading: 'きょう',
    pos: '名詞',
    zh: '今天',
    example: '今日は 天気が いいですね。',
    exampleZh: '今天天氣真好呢。',
    level: 'n5',
  },
  {
    id: 'n5-card-003',
    term: '明日',
    reading: 'あした',
    pos: '名詞',
    zh: '明天',
    example: '明日 友達と 映画を 見ます。',
    exampleZh: '明天要和朋友看電影。',
    level: 'n5',
  },
  {
    id: 'n5-card-004',
    term: '昨日',
    reading: 'きのう',
    pos: '名詞',
    zh: '昨天',
    example: '昨日は 一日中 雨でした。',
    exampleZh: '昨天下了一整天的雨。',
    level: 'n5',
  },
  {
    id: 'n5-card-005',
    term: '時間',
    reading: 'じかん',
    pos: '名詞',
    zh: '時間',
    example: '時間が ありませんから、タクシーで 行きます。',
    exampleZh: '因為沒時間了，所以搭計程車去。',
    level: 'n5',
  },
  {
    id: 'n5-card-006',
    term: '週末',
    reading: 'しゅうまつ',
    pos: '名詞',
    zh: '週末',
    example: '週末に 家族と 山へ 行きます。',
    exampleZh: '週末要和家人去山上。',
    level: 'n5',
  },
  // ==================== 名詞（家族） ====================
  {
    id: 'n5-card-007',
    term: '家族',
    reading: 'かぞく',
    pos: '名詞',
    zh: '家人；家庭',
    example: '私の 家族は 五人です。',
    exampleZh: '我家有五個人。',
    level: 'n5',
  },
  {
    id: 'n5-card-008',
    term: '父',
    reading: 'ちち',
    pos: '名詞',
    zh: '（自己的）父親',
    example: '父は 銀行で 働いて います。',
    exampleZh: '父親在銀行工作。',
    level: 'n5',
  },
  {
    id: 'n5-card-009',
    term: '母',
    reading: 'はは',
    pos: '名詞',
    zh: '（自己的）母親',
    example: '母の 料理は とても おいしいです。',
    exampleZh: '母親做的菜非常好吃。',
    level: 'n5',
  },
  {
    id: 'n5-card-010',
    term: '兄',
    reading: 'あに',
    pos: '名詞',
    zh: '（自己的）哥哥',
    example: '兄は 大学で 音楽を 勉強して います。',
    exampleZh: '哥哥在大學學音樂。',
    level: 'n5',
  },
  {
    id: 'n5-card-011',
    term: '妹',
    reading: 'いもうと',
    pos: '名詞',
    zh: '（自己的）妹妹',
    example: '妹は 歌が とても 上手です。',
    exampleZh: '妹妹很會唱歌。',
    level: 'n5',
  },
  {
    id: 'n5-card-012',
    term: '友達',
    reading: 'ともだち',
    pos: '名詞',
    zh: '朋友',
    example: '学校で 新しい 友達が できました。',
    exampleZh: '在學校交到了新朋友。',
    level: 'n5',
  },
  // ==================== 名詞（食物） ====================
  {
    id: 'n5-card-013',
    term: 'ご飯',
    reading: 'ごはん',
    pos: '名詞',
    zh: '飯；餐',
    example: '毎晩 七時に ご飯を 食べます。',
    exampleZh: '每天晚上七點吃飯。',
    level: 'n5',
  },
  {
    id: 'n5-card-014',
    term: '水',
    reading: 'みず',
    pos: '名詞',
    zh: '水',
    example: '暑いですから、冷たい 水が 飲みたいです。',
    exampleZh: '因為很熱，想喝冰涼的水。',
    level: 'n5',
  },
  {
    id: 'n5-card-015',
    term: 'お茶',
    reading: 'おちゃ',
    pos: '名詞',
    zh: '茶',
    example: '食事の あとで お茶を 飲みます。',
    exampleZh: '飯後喝茶。',
    level: 'n5',
  },
  {
    id: 'n5-card-016',
    term: '肉',
    reading: 'にく',
    pos: '名詞',
    zh: '肉',
    example: '私は 魚より 肉の ほうが 好きです。',
    exampleZh: '比起魚，我更喜歡肉。',
    level: 'n5',
  },
  {
    id: 'n5-card-017',
    term: '魚',
    reading: 'さかな',
    pos: '名詞',
    zh: '魚',
    example: '川で 大きな 魚を 見ました。',
    exampleZh: '在河裡看到了很大的魚。',
    level: 'n5',
  },
  {
    id: 'n5-card-018',
    term: '野菜',
    reading: 'やさい',
    pos: '名詞',
    zh: '蔬菜',
    example: '毎日 野菜を たくさん 食べましょう。',
    exampleZh: '每天多吃蔬菜吧。',
    level: 'n5',
  },
  {
    id: 'n5-card-019',
    term: '卵',
    reading: 'たまご',
    pos: '名詞',
    zh: '蛋；雞蛋',
    example: '朝ご飯に 卵を 二つ 使いました。',
    exampleZh: '早餐用了兩顆蛋。',
    level: 'n5',
  },
  {
    id: 'n5-card-020',
    term: 'パン',
    reading: 'パン',
    pos: '名詞',
    zh: '麵包',
    example: '駅の 前の 店で パンを 買いました。',
    exampleZh: '在車站前的店買了麵包。',
    level: 'n5',
  },
  {
    id: 'n5-card-021',
    term: '果物',
    reading: 'くだもの',
    pos: '名詞',
    zh: '水果',
    example: 'この 果物は 甘くて おいしいです。',
    exampleZh: '這種水果又甜又好吃。',
    level: 'n5',
  },
  // ==================== 名詞（教室・學校） ====================
  {
    id: 'n5-card-022',
    term: '学校',
    reading: 'がっこう',
    pos: '名詞',
    zh: '學校',
    example: '毎朝 歩いて 学校へ 行きます。',
    exampleZh: '每天早上走路去學校。',
    level: 'n5',
  },
  {
    id: 'n5-card-023',
    term: '先生',
    reading: 'せんせい',
    pos: '名詞',
    zh: '老師',
    example: '分からない ときは 先生に 聞きます。',
    exampleZh: '不懂的時候會問老師。',
    level: 'n5',
  },
  {
    id: 'n5-card-024',
    term: '学生',
    reading: 'がくせい',
    pos: '名詞',
    zh: '學生',
    example: 'この 大学の 学生は みんな 親切です。',
    exampleZh: '這所大學的學生都很親切。',
    level: 'n5',
  },
  {
    id: 'n5-card-025',
    term: '宿題',
    reading: 'しゅくだい',
    pos: '名詞',
    zh: '功課；作業',
    example: '寝る 前に 宿題を しました。',
    exampleZh: '睡前做了功課。',
    level: 'n5',
  },
  {
    id: 'n5-card-026',
    term: '本',
    reading: 'ほん',
    pos: '名詞',
    zh: '書',
    example: '図書館で 本を 三冊 借りました。',
    exampleZh: '在圖書館借了三本書。',
    level: 'n5',
  },
  {
    id: 'n5-card-027',
    term: '辞書',
    reading: 'じしょ',
    pos: '名詞',
    zh: '字典；辭典',
    example: '新しい 言葉は 辞書で 調べます。',
    exampleZh: '生字會用字典查。',
    level: 'n5',
  },
  {
    id: 'n5-card-028',
    term: '教室',
    reading: 'きょうしつ',
    pos: '名詞',
    zh: '教室',
    example: '教室に 学生が 二十人 います。',
    exampleZh: '教室裡有二十個學生。',
    level: 'n5',
  },
  // ==================== 名詞（場所） ====================
  {
    id: 'n5-card-029',
    term: '家',
    reading: 'いえ',
    pos: '名詞',
    zh: '家；房子',
    example: '日曜日は 家で ゆっくり 休みます。',
    exampleZh: '星期天在家好好休息。',
    level: 'n5',
  },
  {
    id: 'n5-card-030',
    term: '駅',
    reading: 'えき',
    pos: '名詞',
    zh: '車站',
    example: '駅から 会社まで 歩いて 十分です。',
    exampleZh: '從車站走到公司要十分鐘。',
    level: 'n5',
  },
  {
    id: 'n5-card-031',
    term: '店',
    reading: 'みせ',
    pos: '名詞',
    zh: '商店；店家',
    example: 'あの 店は 夜 十時まで 開いて います。',
    exampleZh: '那家店開到晚上十點。',
    level: 'n5',
  },
  {
    id: 'n5-card-032',
    term: '病院',
    reading: 'びょういん',
    pos: '名詞',
    zh: '醫院',
    example: '風邪を ひきましたから、病院へ 行きました。',
    exampleZh: '因為感冒了，所以去了醫院。',
    level: 'n5',
  },
  {
    id: 'n5-card-033',
    term: '図書館',
    reading: 'としょかん',
    pos: '名詞',
    zh: '圖書館',
    example: '図書館で 毎日 二時間 勉強します。',
    exampleZh: '每天在圖書館唸書兩小時。',
    level: 'n5',
  },
  {
    id: 'n5-card-034',
    term: '公園',
    reading: 'こうえん',
    pos: '名詞',
    zh: '公園',
    example: '公園で 子どもたちが 遊んで います。',
    exampleZh: '孩子們正在公園裡玩。',
    level: 'n5',
  },
  {
    id: 'n5-card-035',
    term: '会社',
    reading: 'かいしゃ',
    pos: '名詞',
    zh: '公司',
    example: '父の 会社は 東京に あります。',
    exampleZh: '父親的公司在東京。',
    level: 'n5',
  },
  // ==================== 名詞（交通・其他） ====================
  {
    id: 'n5-card-036',
    term: '電車',
    reading: 'でんしゃ',
    pos: '名詞',
    zh: '電車',
    example: '電車の 中で 音楽を 聞きます。',
    exampleZh: '在電車上聽音樂。',
    level: 'n5',
  },
  {
    id: 'n5-card-037',
    term: 'バス',
    reading: 'バス',
    pos: '名詞',
    zh: '公車；巴士',
    example: '次の バスは 三時に 来ます。',
    exampleZh: '下一班公車三點來。',
    level: 'n5',
  },
  {
    id: 'n5-card-038',
    term: '自転車',
    reading: 'じてんしゃ',
    pos: '名詞',
    zh: '腳踏車',
    example: '天気が いい 日は 自転車で 行きます。',
    exampleZh: '天氣好的日子就騎腳踏車去。',
    level: 'n5',
  },
  {
    id: 'n5-card-039',
    term: '飛行機',
    reading: 'ひこうき',
    pos: '名詞',
    zh: '飛機',
    example: '飛行機で 北海道へ 行きました。',
    exampleZh: '搭飛機去了北海道。',
    level: 'n5',
  },
  {
    id: 'n5-card-040',
    term: '天気',
    reading: 'てんき',
    pos: '名詞',
    zh: '天氣',
    example: '明日の 天気は どうですか。',
    exampleZh: '明天天氣如何？',
    level: 'n5',
  },
  // ==================== 動詞 ====================
  {
    id: 'n5-card-041',
    term: '行く',
    reading: 'いく',
    pos: '動詞',
    zh: '去',
    example: '夏休みに 海へ 行きたいです。',
    exampleZh: '暑假想去海邊。',
    level: 'n5',
  },
  {
    id: 'n5-card-042',
    term: '来る',
    reading: 'くる',
    pos: '動詞',
    zh: '來',
    example: '友達が うちへ 遊びに 来ます。',
    exampleZh: '朋友要來我家玩。',
    level: 'n5',
  },
  {
    id: 'n5-card-043',
    term: '帰る',
    reading: 'かえる',
    pos: '動詞',
    zh: '回去；回家',
    example: '毎日 六時ごろ 家に 帰ります。',
    exampleZh: '每天六點左右回家。',
    level: 'n5',
  },
  {
    id: 'n5-card-044',
    term: '食べる',
    reading: 'たべる',
    pos: '動詞',
    zh: '吃',
    example: '昼ご飯は もう 食べましたか。',
    exampleZh: '午餐已經吃了嗎？',
    level: 'n5',
  },
  {
    id: 'n5-card-045',
    term: '飲む',
    reading: 'のむ',
    pos: '動詞',
    zh: '喝',
    example: '寝る 前に 温かい 牛乳を 飲みます。',
    exampleZh: '睡前喝溫牛奶。',
    level: 'n5',
  },
  {
    id: 'n5-card-046',
    term: '見る',
    reading: 'みる',
    pos: '動詞',
    zh: '看',
    example: '週末に 家で 映画を 見ました。',
    exampleZh: '週末在家看了電影。',
    level: 'n5',
  },
  {
    id: 'n5-card-047',
    term: '聞く',
    reading: 'きく',
    pos: '動詞',
    zh: '聽；問',
    example: '毎朝 ラジオで ニュースを 聞きます。',
    exampleZh: '每天早上聽廣播新聞。',
    level: 'n5',
  },
  {
    id: 'n5-card-048',
    term: '読む',
    reading: 'よむ',
    pos: '動詞',
    zh: '讀；唸',
    example: '電車の 中で 新聞を 読みます。',
    exampleZh: '在電車上讀報紙。',
    level: 'n5',
  },
  {
    id: 'n5-card-049',
    term: '書く',
    reading: 'かく',
    pos: '動詞',
    zh: '寫',
    example: '母に 長い 手紙を 書きました。',
    exampleZh: '寫了一封長信給母親。',
    level: 'n5',
  },
  {
    id: 'n5-card-050',
    term: '話す',
    reading: 'はなす',
    pos: '動詞',
    zh: '說話；講',
    example: '先生と 日本語で 話しました。',
    exampleZh: '和老師用日語交談了。',
    level: 'n5',
  },
  {
    id: 'n5-card-051',
    term: '買う',
    reading: 'かう',
    pos: '動詞',
    zh: '買',
    example: 'スーパーで 野菜と 卵を 買いました。',
    exampleZh: '在超市買了蔬菜和蛋。',
    level: 'n5',
  },
  {
    id: 'n5-card-052',
    term: '会う',
    reading: 'あう',
    pos: '動詞',
    zh: '見面；遇見',
    example: '駅の 前で 友達に 会いました。',
    exampleZh: '在車站前遇到了朋友。',
    level: 'n5',
  },
  {
    id: 'n5-card-053',
    term: '起きる',
    reading: 'おきる',
    pos: '動詞',
    zh: '起床',
    example: '明日は 五時に 起きなければ なりません。',
    exampleZh: '明天必須五點起床。',
    level: 'n5',
  },
  {
    id: 'n5-card-054',
    term: '寝る',
    reading: 'ねる',
    pos: '動詞',
    zh: '睡覺',
    example: '昨日は 十一時に 寝ました。',
    exampleZh: '昨天十一點睡的。',
    level: 'n5',
  },
  {
    id: 'n5-card-055',
    term: '休む',
    reading: 'やすむ',
    pos: '動詞',
    zh: '休息；請假',
    example: '熱が ありますから、今日は 会社を 休みます。',
    exampleZh: '因為發燒，今天向公司請假。',
    level: 'n5',
  },
  {
    id: 'n5-card-056',
    term: '働く',
    reading: 'はたらく',
    pos: '動詞',
    zh: '工作',
    example: '姉は 病院で 働いて います。',
    exampleZh: '姊姊在醫院工作。',
    level: 'n5',
  },
  {
    id: 'n5-card-057',
    term: '待つ',
    reading: 'まつ',
    pos: '動詞',
    zh: '等待',
    example: '喫茶店で 一時間 待ちました。',
    exampleZh: '在咖啡廳等了一個小時。',
    level: 'n5',
  },
  {
    id: 'n5-card-058',
    term: '作る',
    reading: 'つくる',
    pos: '動詞',
    zh: '做；製作',
    example: '母と いっしょに ケーキを 作りました。',
    exampleZh: '和母親一起做了蛋糕。',
    level: 'n5',
  },
  {
    id: 'n5-card-059',
    term: '使う',
    reading: 'つかう',
    pos: '動詞',
    zh: '使用',
    example: 'はさみを 使って 紙を 切ります。',
    exampleZh: '用剪刀剪紙。',
    level: 'n5',
  },
  {
    id: 'n5-card-060',
    term: '教える',
    reading: 'おしえる',
    pos: '動詞',
    zh: '教；告訴',
    example: '田中さんに 駅への 道を 教えました。',
    exampleZh: '告訴了田中先生去車站的路。',
    level: 'n5',
  },
  {
    id: 'n5-card-061',
    term: '泳ぐ',
    reading: 'およぐ',
    pos: '動詞',
    zh: '游泳',
    example: '夏は よく プールで 泳ぎます。',
    exampleZh: '夏天常在游泳池游泳。',
    level: 'n5',
  },
  {
    id: 'n5-card-062',
    term: '遊ぶ',
    reading: 'あそぶ',
    pos: '動詞',
    zh: '玩',
    example: '弟は 外で 犬と 遊んで います。',
    exampleZh: '弟弟正在外面和狗玩。',
    level: 'n5',
  },
  {
    id: 'n5-card-063',
    term: '洗う',
    reading: 'あらう',
    pos: '動詞',
    zh: '洗',
    example: '食事の 前に 手を 洗いましょう。',
    exampleZh: '吃飯前先洗手吧。',
    level: 'n5',
  },
  {
    id: 'n5-card-064',
    term: '入る',
    reading: 'はいる',
    pos: '動詞',
    zh: '進入',
    example: '寒いですから、早く 中に 入って ください。',
    exampleZh: '外面很冷，請快進來裡面。',
    level: 'n5',
  },
  {
    id: 'n5-card-065',
    term: '出る',
    reading: 'でる',
    pos: '動詞',
    zh: '出去；離開',
    example: '毎朝 七時半に 家を 出ます。',
    exampleZh: '每天早上七點半出門。',
    level: 'n5',
  },
  // ==================== い形容詞 ====================
  {
    id: 'n5-card-066',
    term: '大きい',
    reading: 'おおきい',
    pos: 'い形容詞',
    zh: '大的',
    example: '動物園で 大きい ゾウを 見ました。',
    exampleZh: '在動物園看到了很大的大象。',
    level: 'n5',
  },
  {
    id: 'n5-card-067',
    term: '小さい',
    reading: 'ちいさい',
    pos: 'い形容詞',
    zh: '小的',
    example: '旅行の ために 小さい かばんを 買いました。',
    exampleZh: '為了旅行買了一個小包包。',
    level: 'n5',
  },
  {
    id: 'n5-card-068',
    term: '高い',
    reading: 'たかい',
    pos: 'い形容詞',
    zh: '高的；貴的',
    example: 'この レストランは おいしいですが、高いです。',
    exampleZh: '這家餐廳好吃但很貴。',
    level: 'n5',
  },
  {
    id: 'n5-card-069',
    term: '安い',
    reading: 'やすい',
    pos: 'い形容詞',
    zh: '便宜的',
    example: 'あの 店は 何でも 安いです。',
    exampleZh: '那家店什麼都便宜。',
    level: 'n5',
  },
  {
    id: 'n5-card-070',
    term: '新しい',
    reading: 'あたらしい',
    pos: 'い形容詞',
    zh: '新的',
    example: '新しい くつを はいて 出かけました。',
    exampleZh: '穿著新鞋出門了。',
    level: 'n5',
  },
  {
    id: 'n5-card-071',
    term: '古い',
    reading: 'ふるい',
    pos: 'い形容詞',
    zh: '舊的；古老的',
    example: 'この 寺は とても 古いです。',
    exampleZh: '這座寺廟非常古老。',
    level: 'n5',
  },
  {
    id: 'n5-card-072',
    term: '暑い',
    reading: 'あつい',
    pos: 'い形容詞',
    zh: '（天氣）熱的',
    example: '今年の 夏は 去年より 暑いです。',
    exampleZh: '今年夏天比去年熱。',
    level: 'n5',
  },
  {
    id: 'n5-card-073',
    term: '寒い',
    reading: 'さむい',
    pos: 'い形容詞',
    zh: '寒冷的',
    example: '冬の 朝は 寒くて 起きたく ないです。',
    exampleZh: '冬天的早晨很冷，不想起床。',
    level: 'n5',
  },
  {
    id: 'n5-card-074',
    term: 'おいしい',
    reading: 'おいしい',
    pos: 'い形容詞',
    zh: '好吃的',
    example: '母が 作った カレーは おいしかったです。',
    exampleZh: '母親做的咖哩很好吃。',
    level: 'n5',
  },
  {
    id: 'n5-card-075',
    term: '楽しい',
    reading: 'たのしい',
    pos: 'い形容詞',
    zh: '開心的；愉快的',
    example: '昨日の パーティーは とても 楽しかったです。',
    exampleZh: '昨天的派對非常開心。',
    level: 'n5',
  },
  {
    id: 'n5-card-076',
    term: '忙しい',
    reading: 'いそがしい',
    pos: 'い形容詞',
    zh: '忙碌的',
    example: '今週は 仕事が 多くて 忙しいです。',
    exampleZh: '這週工作多，很忙。',
    level: 'n5',
  },
  {
    id: 'n5-card-077',
    term: '難しい',
    reading: 'むずかしい',
    pos: 'い形容詞',
    zh: '困難的',
    example: '昨日の テストは 難しかったです。',
    exampleZh: '昨天的考試很難。',
    level: 'n5',
  },
  // ==================== な形容詞 ====================
  {
    id: 'n5-card-078',
    term: '元気',
    reading: 'げんき',
    pos: 'な形容詞',
    zh: '有精神的；健康的',
    example: 'おばあさんは 九十歳ですが、とても 元気です。',
    exampleZh: '奶奶九十歲了，但非常健康。',
    level: 'n5',
  },
  {
    id: 'n5-card-079',
    term: '静か',
    reading: 'しずか',
    pos: 'な形容詞',
    zh: '安靜的',
    example: 'この 公園は 朝は 静かです。',
    exampleZh: '這座公園早上很安靜。',
    level: 'n5',
  },
  {
    id: 'n5-card-080',
    term: 'にぎやか',
    reading: 'にぎやか',
    pos: 'な形容詞',
    zh: '熱鬧的',
    example: '駅の 近くは 店が 多くて にぎやかです。',
    exampleZh: '車站附近店家多，很熱鬧。',
    level: 'n5',
  },
  {
    id: 'n5-card-081',
    term: '便利',
    reading: 'べんり',
    pos: 'な形容詞',
    zh: '方便的',
    example: 'この アパートは 駅に 近くて 便利です。',
    exampleZh: '這間公寓離車站近，很方便。',
    level: 'n5',
  },
  {
    id: 'n5-card-082',
    term: '有名',
    reading: 'ゆうめい',
    pos: 'な形容詞',
    zh: '有名的',
    example: '京都は 古い 寺で 有名です。',
    exampleZh: '京都以古老的寺廟聞名。',
    level: 'n5',
  },
  {
    id: 'n5-card-083',
    term: '好き',
    reading: 'すき',
    pos: 'な形容詞',
    zh: '喜歡的',
    example: '私は 甘い 果物が 好きです。',
    exampleZh: '我喜歡甜的水果。',
    level: 'n5',
  },
  {
    id: 'n5-card-084',
    term: 'きれい',
    reading: 'きれい',
    pos: 'な形容詞',
    zh: '漂亮的；乾淨的',
    example: '庭に きれいな 花が 咲いて います。',
    exampleZh: '院子裡開著漂亮的花。',
    level: 'n5',
  },
  {
    id: 'n5-card-085',
    term: '簡単',
    reading: 'かんたん',
    pos: 'な形容詞',
    zh: '簡單的',
    example: '今日の テストは 簡単でした。',
    exampleZh: '今天的考試很簡單。',
    level: 'n5',
  },
  // ==================== 副詞 ====================
  {
    id: 'n5-card-086',
    term: 'とても',
    reading: 'とても',
    pos: '副詞',
    zh: '非常',
    example: 'この 映画は とても おもしろかったです。',
    exampleZh: '這部電影非常有趣。',
    level: 'n5',
  },
  {
    id: 'n5-card-087',
    term: '少し',
    reading: 'すこし',
    pos: '副詞',
    zh: '一點；稍微',
    example: '日本語が 少し 分かります。',
    exampleZh: '懂一點日語。',
    level: 'n5',
  },
  {
    id: 'n5-card-088',
    term: 'たくさん',
    reading: 'たくさん',
    pos: '副詞',
    zh: '很多',
    example: '誕生日に プレゼントを たくさん もらいました。',
    exampleZh: '生日收到了很多禮物。',
    level: 'n5',
  },
  {
    id: 'n5-card-089',
    term: 'いつも',
    reading: 'いつも',
    pos: '副詞',
    zh: '總是；平常',
    example: '父は いつも 七時の ニュースを 見ます。',
    exampleZh: '父親總是看七點的新聞。',
    level: 'n5',
  },
  {
    id: 'n5-card-090',
    term: '時々',
    reading: 'ときどき',
    pos: '副詞',
    zh: '有時；偶爾',
    example: '時々 一人で 旅行に 行きます。',
    exampleZh: '偶爾一個人去旅行。',
    level: 'n5',
  },
  {
    id: 'n5-card-091',
    term: 'もう',
    reading: 'もう',
    pos: '副詞',
    zh: '已經',
    example: '宿題は もう 終わりました。',
    exampleZh: '功課已經做完了。',
    level: 'n5',
  },
  {
    id: 'n5-card-092',
    term: 'まだ',
    reading: 'まだ',
    pos: '副詞',
    zh: '還（沒）；仍然',
    example: '弟は まだ 寝て います。',
    exampleZh: '弟弟還在睡。',
    level: 'n5',
  },
  {
    id: 'n5-card-093',
    term: 'ゆっくり',
    reading: 'ゆっくり',
    pos: '副詞',
    zh: '慢慢地；悠閒地',
    example: 'もう 少し ゆっくり 話して ください。',
    exampleZh: '請再講慢一點。',
    level: 'n5',
  },
  // ==================== 表現 ====================
  {
    id: 'n5-card-094',
    term: 'おはようございます',
    reading: 'おはようございます',
    pos: '表現',
    zh: '早安（禮貌說法）',
    example: '毎朝 先生に 「おはようございます」と あいさつします。',
    exampleZh: '每天早上向老師道早安。',
    level: 'n5',
  },
  {
    id: 'n5-card-095',
    term: 'ありがとうございます',
    reading: 'ありがとうございます',
    pos: '表現',
    zh: '謝謝（禮貌說法）',
    example: 'プレゼントを もらって、「ありがとうございます」と 言いました。',
    exampleZh: '收到禮物後道了謝。',
    level: 'n5',
  },
  {
    id: 'n5-card-096',
    term: 'すみません',
    reading: 'すみません',
    pos: '表現',
    zh: '不好意思；對不起',
    example: '道を 聞く とき、まず 「すみません」と 言います。',
    exampleZh: '問路時要先講「不好意思」。',
    level: 'n5',
  },
  {
    id: 'n5-card-097',
    term: 'いただきます',
    reading: 'いただきます',
    pos: '表現',
    zh: '（用餐前）開動了',
    example: '食べる 前に 「いただきます」と 言います。',
    exampleZh: '開動前要講「我開動了」。',
    level: 'n5',
  },
  {
    id: 'n5-card-098',
    term: 'お願いします',
    reading: 'おねがいします',
    pos: '表現',
    zh: '麻煩你；拜託了',
    example: '「コーヒーを 一つ お願いします」と 注文しました。',
    exampleZh: '向店員點了一杯咖啡。',
    level: 'n5',
  },
  {
    id: 'n5-card-099',
    term: 'はじめまして',
    reading: 'はじめまして',
    pos: '表現',
    zh: '初次見面',
    example: '「はじめまして。リンと 申します」と 言いました。',
    exampleZh: '講了「初次見面，敝姓林」。',
    level: 'n5',
  },
  {
    id: 'n5-card-100',
    term: 'おやすみなさい',
    reading: 'おやすみなさい',
    pos: '表現',
    zh: '晚安（睡前）',
    example: '寝る 前に 家族に 「おやすみなさい」と 言います。',
    exampleZh: '睡前對家人道晚安。',
    level: 'n5',
  },
]
