import type { JlptQuestion } from '../../types'

export const questions: JlptQuestion[] = [
  {
    id: 'n1-listening-kadai-001',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '広告代理店で女の部長と男の社員が、クライアントに出す企画書について話しています。' },
      { speaker: '女', text: '例の飲料メーカーの企画書、ざっと目を通したんだけど。' },
      { speaker: '男', text: 'いかがでしたか。ビジュアルにはかなりこだわったつもりなんですが。' },
      { speaker: '女', text: 'うん、デザインは申し分ないのよ。ただ、そもそもの切り口が先方の与件とずれてる気がするのよね。若年層の開拓が主眼だったでしょう。' },
      { speaker: '男', text: 'では、写真を若者向けのものに差し替えて、色味も明るく調整しましょうか。' },
      { speaker: '女', text: 'うーん、見た目でどうにかなる話じゃないと思うの。骨組みから考え直したほうが早いんじゃない。' },
      { speaker: '男', text: 'わかりました。コンセプトの部分から練り直します。制作費の見積もりはどうしましょう。' },
      { speaker: '女', text: '見積もりは構成が固まってからで十分。先方とのアポの調整はこっちでやっておくから。' },
      { speaker: '男', text: '承知しました。では早速取りかかります。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '企画のコンセプトを練り直す',
      '写真や色味を差し替える',
      '制作費の見積もりを作る',
      'クライアントに連絡を取る',
    ],
    answerIndex: 0,
    explanation:
      '部長雖稱讚設計「申し分ない」，卻指出切入點偏離客戶需求，並以「見た目でどうにかなる話じゃない」「骨組みから考え直したほうが」委婉否定只改視覺的提案，男の人也回答「コンセプトの部分から練り直します」。更換照片與色調是被否決的方案；估價被延到「構成が固まってから」；聯絡客戶由部長負責，都不是他現在該做的事。',
    explanationEn:
      'The department head praises the design as 「申し分ない」 but says the whole angle misses the client\'s brief, and she gently rejects a visual-only fix with 「見た目でどうにかなる話じゃない」 and 「骨組みから考え直したほうが」. The man then answers 「コンセプトの部分から練り直します」, so reworking the concept is his first task. Swapping photos and adjusting colors is the proposal she shot down; the cost estimate is postponed until 「構成が固まってから」; and contacting the client is something she says she will handle herself.',
  },
  {
    id: 'n1-listening-kadai-002',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '出版社で男の編集長と女の編集者が、来月刊行する本の原稿について話しています。' },
      { speaker: '男', text: '例の新書の原稿、初校まで進んでるんだよね。' },
      { speaker: '女', text: 'はい。ただ、第三章の統計の引用元がどうも曖昧で、校閲からも疑義が出ています。' },
      { speaker: '男', text: 'それは放っておけないな。刊行後に指摘されたら、回収騒ぎになりかねない。' },
      { speaker: '女', text: 'ですよね。著者の先生に出典を問い合わせようと思うんですが、ご多忙のようで、つい後回しにしてしまって。' },
      { speaker: '男', text: 'いや、そこが片付かないことには先へ進めないだろう。今日中に連絡を取ってくれ。' },
      { speaker: '女', text: 'わかりました。それから、装丁の案はまだデザイナーから上がってきていません。' },
      { speaker: '男', text: '装丁は催促しなくても今週中には来る手はずだ。帯の文句は校了間際でも間に合うし。' },
      { speaker: '女', text: 'では、まず先生に当たります。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '著者に統計の出典を問い合わせる',
      '装丁の案をデザイナーに催促する',
      '帯の文句を考える',
      '校閲に疑義の内容を確認する',
    ],
    answerIndex: 0,
    explanation:
      '第三章統計出處不明，編輯長認為「そこが片付かないことには先へ進めない」，指示「今日中に連絡を取ってくれ」，她也回答「まず先生に当たります」，故第一件事是向作者查證出處。裝幀案被明言「催促しなくても今週中には来る」不必催；書腰文案「校了間際でも間に合う」不急；校閱早已提出疑義，無須再向校閱確認。',
    explanationEn:
      'The sourcing of the statistics in chapter three is unclear, and the editor-in-chief says 「そこが片付かないことには先へ進めない」 and orders 「今日中に連絡を取ってくれ」; she replies 「まず先生に当たります」, so her first task is to ask the author about the source. The cover design needs no chasing — it is due this week anyway (「催促しなくても今週中には来る」); the obi copy 「校了間際でも間に合う」, so it is not urgent; and the proofreaders have already raised their query, so there is nothing to confirm with them.',
  },
  {
    id: 'n1-listening-kadai-003',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '商社で女の課長と男の社員が、海外メーカーとの契約書について話しています。' },
      { speaker: '男', text: '課長、先方から代理店契約のドラフトが届きました。おおむね先日の合意どおりですが、一点、支払い条件が前払いになっていまして。' },
      { speaker: '女', text: '前払い？うちの社内規定だと、新規の取引先にそれは通らないんじゃなかった？' },
      { speaker: '男', text: 'ええ、規定に抵触しかねないと私も思ったんですが、断言はできなくて。' },
      { speaker: '女', text: '自己判断で先方に回答して、後でひっくり返すのが一番まずいのよ。' },
      { speaker: '男', text: 'そうですね。では、法務部に条項の確認を依頼します。' },
      { speaker: '女', text: 'お願い。和訳は外部に出してあるから、上がってくるのを待てばいいわ。' },
      { speaker: '男', text: '承知しました。先方への返事は法務の見解が出てからにします。' },
      { speaker: '女', text: 'ええ。調印の段取りはそのあとゆっくり詰めましょう。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '法務部に契約の条項の確認を頼む',
      '先方に支払い条件の修正を求める',
      '契約書の和訳を作る',
      '調印の日程を調整する',
    ],
    answerIndex: 0,
    explanation:
      '付款條件可能牴觸社內規定，課長以「自己判断で先方に回答して、後でひっくり返すのが一番まずい」暗示不能自行答覆，男の人於是說「法務部に条項の確認を依頼します」，這就是他的下一步。向對方要求修改得等法務見解出來，順序在後；日文翻譯已外包，只需等成品；簽約流程被「そのあとゆっくり詰めましょう」排到最後。',
    explanationEn:
      'The payment terms may violate internal rules, and the section chief hints he must not reply on his own judgment: 「自己判断で先方に回答して、後でひっくり返すのが一番まずい」. He therefore says 「法務部に条項の確認を依頼します」 — asking the legal department to review the clause is his next step. Requesting a revision from the other party must wait for legal\'s opinion, so it comes later; the Japanese translation is already outsourced and only needs waiting for; and the signing arrangements are pushed to the very end by 「そのあとゆっくり詰めましょう」.',
  },
  {
    id: 'n1-listening-kadai-004',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'メーカーの品質保証部で男の部長と女の社員が、製品の不具合について話しています。' },
      { speaker: '女', text: '部長、販売店から炊飯器の蓋が閉まりにくいという申し出が三件、続けて入っています。' },
      { speaker: '男', text: '三件か。偶発的ならまだしも、同じロットに固まってるとなると穏やかじゃないな。' },
      { speaker: '女', text: '製造番号を見る限り、いずれも先月の第二ロットのようです。' },
      { speaker: '男', text: 'だとすると、まず工場の検査記録を取り寄せて、出荷時の数値を洗い出すのが先決だろう。' },
      { speaker: '女', text: 'わかりました。お客様へのお詫びの文面も用意しておきましょうか。' },
      { speaker: '男', text: '案内文は原因の見当がついてからでいい。広報とも擦り合わせが要るしね。' },
      { speaker: '女', text: '回収の判断はどうなさいますか。' },
      { speaker: '男', text: '回収うんぬんはデータを見てからだ。先走ると現場が混乱しかねない。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '工場から検査記録を取り寄せる',
      'お客様への案内文を用意する',
      '製品の回収の手配をする',
      '広報と案内文の擦り合わせをする',
    ],
    answerIndex: 0,
    explanation:
      '部長判斷不良品集中在同一批次「穏やかじゃない」，明言「まず工場の検査記録を取り寄せて…のが先決」，所以她要先調出出廠檢驗紀錄。道歉文被「原因の見当がついてからでいい」延後；回收與否「データを見てからだ」尚未決定，貿然安排反而會讓「現場が混乱しかねない」；與公關協調是進到文案階段才需要的事。',
    explanationEn:
      'Seeing the defects clustered in one lot, the manager calls it 「穏やかじゃない」 and states plainly 「まず工場の検査記録を取り寄せて…のが先決」, so her first task is to obtain the factory\'s inspection records and check the shipment figures. The apology notice is deferred by 「案内文は原因の見当がついてからでいい」; whether to recall is 「データを見てからだ」 — undecided, and jumping ahead could leave the field 「混乱しかねない」; and coordinating with PR only becomes necessary once they reach the notice-drafting stage.',
  },
  {
    id: 'n1-listening-kadai-005',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'ＩＴ会社で女のリーダーと男の社員が、システム障害への対応について話しています。' },
      { speaker: '女', text: '昨夜からの障害、復旧の見通しはまだ立たないの？' },
      { speaker: '男', text: 'インフラチームが当たっていますが、完全復旧は夕方までかかりそうだと。' },
      { speaker: '女', text: 'そう。じゃあ、こちらはこちらでやるべきことを進めましょう。' },
      { speaker: '男', text: '私のほうで、主要なお客様に片っ端からお詫びの電話を入れましょうか。' },
      { speaker: '女', text: '個別の対応は営業に任せたほうがいいわ。それより、どの契約のどの機能に影響が出ているのか、全体像が見えないと動きようがないでしょう。' },
      { speaker: '男', text: 'たしかに。ログを突き合わせて、影響を受けた顧客の一覧にまとめます。' },
      { speaker: '女', text: 'お願い。対外的な発表をするかどうかは、広報がその一覧を見て判断するそうだから。' },
      { speaker: '男', text: '承知しました。すぐに取りかかります。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '障害の影響範囲を調べて一覧にまとめる',
      '主要な顧客にお詫びの電話をかける',
      'システムの復旧作業に加わる',
      '広報と対外発表の相談をする',
    ],
    answerIndex: 0,
    explanation:
      '男の人提議逐一致電道歉，被リーダー以「個別の対応は営業に任せたほうがいい」婉拒，並指出「全体像が見えないと動きようがない」，他因而接下「影響を受けた顧客の一覧にまとめます」的工作，這是他的首要課題。致電客戶已改由業務負責；復原作業是基礎架構團隊在處理；是否對外發表由公關看過清單後判斷，皆非他現在該做的事。',
    explanationEn:
      'The man offers to phone every major customer with apologies, but the leader deflects it with 「個別の対応は営業に任せたほうがいい」 and points out 「全体像が見えないと動きようがない」. He then takes on the task himself: 「影響を受けた顧客の一覧にまとめます」 — compiling the list of affected customers is his first job. Apology calls have been reassigned to the sales team; the recovery work is being handled by the infrastructure team; and whether to make a public announcement is for PR to judge after seeing the list, so none of those are his immediate task.',
  },
  {
    id: 'n1-listening-kadai-006',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社の人事部で女の課長と男の社員が、採用の最終面接について話しています。' },
      { speaker: '男', text: '課長、最終面接に進む三名が決まりましたので、候補者に日程の希望を聞こうと思います。' },
      { speaker: '女', text: 'ちょっと待って。最終は役員の同席が要るでしょう。先に候補者の希望を聞いても、役員の予定と合わなかったら二度手間になるだけよ。' },
      { speaker: '男', text: 'あ、おっしゃるとおりですね。では、まず秘書室に役員の空いている日を確認して、枠を押さえます。' },
      { speaker: '女', text: 'そうして。候補者への連絡はそれからでも遅くないから。' },
      { speaker: '男', text: '会議室はどうしましょう。' },
      { speaker: '女', text: '部屋の手配はアシスタントの田村さんに頼んであるから、日程さえ伝えれば動いてくれるわ。' },
      { speaker: '男', text: 'わかりました。評価シートの準備もありますね。' },
      { speaker: '女', text: 'シートは前日に刷れば十分。とにかく枠が先よ。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '秘書室に役員の予定を確認する',
      '候補者に日程の希望を聞く',
      '面接に使う会議室を予約する',
      '評価シートを印刷する',
    ],
    answerIndex: 0,
    explanation:
      '男の人原想先詢問應徵者的時段，課長以「二度手間になるだけよ」點出順序不對——最終面試需要董事在場，得先向秘書室確認並鎖定董事的空檔，最後更強調「とにかく枠が先よ」。詢問候補者被明確排到之後（それからでも遅くない）；會議室已交代給助理田村處理；評分表「前日に刷れば十分」並不急。',
    explanationEn:
      'The man wanted to ask the candidates for their preferred dates first, but the section chief points out the order is wrong with 「二度手間になるだけよ」: the final interview requires executives to attend, so he must first check their availability with the secretariat and lock in slots — she even stresses 「とにかく枠が先よ」. Contacting the candidates is explicitly moved to afterward (「それからでも遅くない」); the meeting room is already entrusted to the assistant Tamura; and the evaluation sheets 「前日に刷れば十分」, so they are not urgent.',
  },
  {
    id: 'n1-listening-kadai-007',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '建設会社の現場事務所で男の所長と女の社員が、来月の工事の段取りについて話しています。' },
      { speaker: '男', text: '来月頭の外壁工事だけど、クレーンを歩道に据えることになったから、道路使用許可が要るね。' },
      { speaker: '女', text: '申請から許可が下りるまで、確か二週間はみておかないといけませんよね。' },
      { speaker: '男', text: 'そう。だから書類が今日明日のうちに警察署に出せないと、工程全体がずれ込みかねない。' },
      { speaker: '女', text: '申請書の様式は前回のものが残っていますから、すぐ整えられます。' },
      { speaker: '男', text: 'じゃあ、頼むよ。資材の搬入日は許可が出てから業者と詰めればいい。' },
      { speaker: '女', text: '近隣へのご挨拶はいかがしましょう。' },
      { speaker: '男', text: '挨拶回りは私も同行するから、来週まとめて回ろう。図面の手直しは設計に戻してあるし、君はまず申請だ。' },
      { speaker: '女', text: '承知しました。書類をまとめて、午後にも出してきます。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '道路使用許可の申請書類を警察署に出す',
      '資材の搬入日を業者と決める',
      '近隣への挨拶回りをする',
      '工事の図面を手直しする',
    ],
    answerIndex: 0,
    explanation:
      '許可核發需時兩週，所長說「書類が今日明日のうちに警察署に出せないと工程全体がずれ込みかねない」，最後直接指示「君はまず申請だ」，她也回答下午就去送件，所以第一件事是提出道路使用許可申請。搬入日期要「許可が出てから」再與業者敲定；訪鄰打招呼由所長同行、排在下週；圖面修改已退回設計部門，輪不到她做。',
    explanationEn:
      'The permit takes two weeks, and the site manager warns 「書類が今日明日のうちに警察署に出せないと工程全体がずれ込みかねない」, then instructs her directly with 「君はまず申請だ」; she answers that she will submit the papers this afternoon, so filing the road-use permit application is her first task. The material delivery date is to be settled with the contractor 「許可が出てから」; the courtesy visits to neighbors are scheduled for next week with the manager along; and the drawing revisions have already been sent back to the design team, so they are not hers to do.',
  },
  {
    id: 'n1-listening-kadai-008',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '番組制作会社で女のプロデューサーと男のアシスタントが、商店街でのロケについて話しています。' },
      { speaker: '女', text: '再来週の商店街ロケ、準備はどこまで進んでる？' },
      { speaker: '男', text: 'カメラなどの機材は手配済みです。出演者のスケジュールは、マネージャーさんに調整してもらっているところで。' },
      { speaker: '女', text: 'そっちはいいとして、組合長さんの承諾書はもう返ってきた？' },
      { speaker: '男', text: 'いえ、先日お電話で快諾はいただいたんですが、書面はまだでして。' },
      { speaker: '女', text: '口約束だけでロケ当日を迎えるのは、さすがにまずいんじゃない。万一組合の中で話が通ってなかったら、撮影自体が飛びかねないわよ。' },
      { speaker: '男', text: 'おっしゃるとおりです。では、承諾書の書式を今日お送りして、返送をお願いします。' },
      { speaker: '女', text: 'ええ、そうして。台本の直しは、そこが固まってからで構わないから。' },
      { speaker: '男', text: 'わかりました。すぐに書類を用意します。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '商店街の組合に承諾書の書類を送る',
      'ロケに使う機材を手配する',
      '出演者のスケジュールを調整する',
      '台本を直す',
    ],
    answerIndex: 0,
    explanation:
      'プロデューサー以「口約束だけで…まずいんじゃない」「撮影自体が飛びかねない」暗示只有口頭允諾風險太大，男の人領會後說「承諾書の書式を今日お送りして」，故第一件事是把同意書格式寄給商店街組合。機材已「手配済み」；藝人檔期正由經紀人協調中，不是他親自處理；劇本修改被指示等許可「固まってから」再做。',
    explanationEn:
      'The producer signals that a verbal OK is too risky with 「口約束だけで…まずいんじゃない」 and 「撮影自体が飛びかねない」; the man takes the hint and says 「承諾書の書式を今日お送りして」, so sending the consent form to the shopping street association is his first task. The equipment is already 「手配済み」; the performers\' schedules are being coordinated by their manager, not by him personally; and the script revisions are told to wait until the permission is 「固まってから」.',
  },
  {
    id: 'n1-listening-kadai-009',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '法律事務所で男の弁護士と女のスタッフが、裁判の準備について話しています。' },
      { speaker: '男', text: '例の損害賠償の件、控訴審に向けて準備書面を組み立てないといけないんだが。' },
      { speaker: '女', text: '提出期限は再来週の金曜でしたね。ドラフトから取りかかりましょうか。' },
      { speaker: '男', text: 'いや、いきなり書き始めるより、まず似たような事案で高裁がどう判断したか、判例を当たって論点を整理してもらえると助かるんだ。' },
      { speaker: '女', text: 'わかりました。近年の裁判例を検索して、要点を表にまとめます。' },
      { speaker: '男', text: '頼むよ。依頼者への経過報告は私から電話を入れておくから。' },
      { speaker: '女', text: '承知しました。相手方の代理人から届いた書面への返事はいかがしますか。' },
      { speaker: '男', text: 'こちらから動くのは、戦略が固まるまで控えたほうがいいだろうね。' },
      { speaker: '女', text: 'では、まず判例の調査から始めます。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '似た事案の判例を調べて要点をまとめる',
      '準備書面のドラフトを書き始める',
      '依頼者に経過を報告する',
      '相手方の代理人に返事を出す',
    ],
    answerIndex: 0,
    explanation:
      '她提議直接動筆寫草稿，律師以「いきなり書き始めるより…判例を当たって…もらえると助かる」委婉調整順序，要她先查類似案件的高等法院判決並整理論點，她最後也說「まず判例の調査から始めます」。草稿因此排在調查之後；向委託人回報由律師親自打電話；回覆對造代理人被「控えたほうがいい」擋下，現階段不能做。',
    explanationEn:
      'She proposes starting on the draft brief, but the lawyer gently reorders things with 「いきなり書き始めるより…判例を当たって…もらえると助かる」, asking her first to research how high courts ruled in similar cases and organize the points of contention; she closes with 「まず判例の調査から始めます」. The draft therefore comes after the research; the progress report to the client is a phone call the lawyer will make himself; and replying to the opposing counsel is blocked for now by 「控えたほうがいい」 until the strategy is set.',
  },
  {
    id: 'n1-listening-kadai-010',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '市役所の広報課で女の係長と男の職員が、市のイベントの発表資料について話しています。' },
      { speaker: '男', text: '係長、秋の防災フェアのプレスリリース案です。ご確認いただけますか。' },
      { speaker: '女', text: '拝見。うん、文面はこれでほぼいいと思う。ただ、この去年の会場の写真、撮った方の使用許諾って取れてたかしら。' },
      { speaker: '男', text: 'えっと、広報誌に載せた時のものなので、大丈夫かと思っていたんですが。' },
      { speaker: '女', text: '用途が変われば話は別よ。無断で配って後から揉めるのが一番困るの。' },
      { speaker: '男', text: '確かにそうですね。では、撮影された方に改めて許諾の確認を取ります。' },
      { speaker: '女', text: 'お願い。記者クラブへの投げ込みは、課長の決裁が下りてからね。' },
      { speaker: '男', text: 'はい。ＳＮＳでの告知はどうしましょう。' },
      { speaker: '女', text: 'ＳＮＳは担当の佐藤さんの持ち場だから、リリースが確定したら共有すれば足りるわ。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '写真の使用許諾を撮影者に確認する',
      'プレスリリースを記者クラブに配る',
      'ＳＮＳでイベントの告知をする',
      'リリースの文面を書き直す',
    ],
    answerIndex: 0,
    explanation:
      '係長認可文案「ほぼいい」，卻對照片授權提出疑問，再以「用途が変われば話は別」「後から揉めるのが一番困る」暗示不能沿用舊授權，男の人於是說要向攝影者重新確認使用許諾，這是他的首要工作。發給記者俱樂部要等「課長の決裁が下りてから」；社群告知是佐藤的職掌；文案本身已獲肯定，不需重寫。',
    explanationEn:
      'The chief approves the text as 「ほぼいい」 but questions the photo\'s usage permission, hinting the old clearance cannot be reused: 「用途が変われば話は別」 and 「後から揉めるのが一番困る」. The man then says he will confirm the permission with the photographer again — that is his first task. Delivering the release to the press club must wait until 「課長の決裁が下りてから」; the social media announcement is Sato\'s responsibility; and the text itself has already been approved, so no rewrite is needed.',
  },
  {
    id: 'n1-listening-kadai-011',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '物流倉庫で男の主任と女のスタッフが、誤出荷への対応について話しています。' },
      { speaker: '女', text: '主任、昨日の出荷分で品番違いの荷物が届いたというお申し出が、二件続けて入っています。' },
      { speaker: '男', text: '二件か。伝票を見る限り、同じ時間帯のピッキングでまとめて取り違えたようだな。' },
      { speaker: '女', text: 'ラベルの印字機が不調なのかもしれません。業者に点検を頼みましょうか。' },
      { speaker: '男', text: '機械のせいなら品番が軒並みずれるはずだよ。今回はそういう筋じゃなさそうだ。それより、同じリストで処理した荷物が午後の便に載るんじゃなかったか。' },
      { speaker: '女', text: 'はい、三十個ほど。出てしまってからでは手の打ちようがありませんね。積み込みの前に中身を照合します。' },
      { speaker: '男', text: '頼む。お客様への代わりの品は、営業がお詫びかたがた手配する決まりだから。' },
      { speaker: '女', text: '承知しました。棚の在庫の数え直しはいかがしますか。' },
      { speaker: '男', text: '棚卸しは週末の定例のときで十分だよ。とにかく午後の便が先だ。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '午後に出荷する荷物の中身を照合する',
      'ラベルの印字機の点検を業者に頼む',
      'お客様に代わりの商品を発送する',
      '棚の在庫を数え直す',
    ],
    answerIndex: 0,
    explanation:
      '主任指出誤出貨集中在同一張揀貨單，強調同批貨「出てしまってからでは手の打ちようがない」，最後說「とにかく午後の便が先だ」，所以她要先在裝車前核對下午出貨的內容物。印表機檢修被「機械のせいなら品番が軒並みずれるはず」委婉否定；補寄替代品是業務部門的既定職責；盤點庫存被延到「週末の定例」，都不是她現在的首要工作。',
    explanationEn:
      'The supervisor notes the mis-shipments trace to one picking list, stresses that once the same batch goes out 「出てしまってからでは手の打ちようがない」, and finishes with 「とにかく午後の便が先だ」 — so her first task is to verify the contents of the afternoon shipment before loading. The printer inspection is gently dismissed with 「機械のせいなら品番が軒並みずれるはず」; sending replacement goods is by rule the sales team\'s job, handled together with the apology; and the stock recount is pushed to the regular weekend stocktake, so none of those come first.',
  },
  {
    id: 'n1-listening-kadai-012',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '大学の研究室で女の教授と男の大学院生が、来月の学会発表の準備について話しています。' },
      { speaker: '男', text: '先生、発表用のスライドの構成案ができましたので、そろそろ作り込みに入ろうかと思うんですが。' },
      { speaker: '女', text: 'うん、構成はよく練れていると思う。ただね、三枚目のグラフのデータ、一回の測定分しかないでしょう。' },
      { speaker: '男', text: 'ええ、追試の時間が取れなくて。先行研究を引いて、傍証を厚くしようかと考えているんですが。' },
      { speaker: '女', text: '文献でいくら固めても、質疑で「再現性は」と聞かれたら立ち往生よ。同じ条件でもう一度測って、数字をそろえるのが先じゃない。' },
      { speaker: '男', text: 'おっしゃるとおりです。では装置の予約を取って、今週中に測り直します。' },
      { speaker: '女', text: 'そうして。スライドの仕上げは、データが出そろってからで間に合うから。' },
      { speaker: '男', text: 'はい。抄録の差し替えはどうしましょう。' },
      { speaker: '女', text: '事務局への連絡は私から入れておくわ。あなたは実験に専念して。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '同じ条件で実験をやり直してデータを取る',
      '先行研究を調べて引用を増やす',
      '発表用のスライドを仕上げる',
      '学会の事務局に抄録の差し替えを連絡する',
    ],
    answerIndex: 0,
    explanation:
      '教授肯定投影片架構，卻點出關鍵圖表只有一次測量資料，並以「文献でいくら固めても…立ち往生よ」委婉否定用先行研究補強的提案，要他「同じ条件でもう一度測って」，他也答應本週內重測，故第一件事是重做實驗補數據。增加文獻引用是被婉拒的方案；完成投影片被延到「データが出そろってから」；聯絡學會事務局由教授親自處理。',
    explanationEn:
      'The professor approves the slide structure but flags that the key graph rests on a single measurement, and she gently rejects shoring it up with prior studies — 「文献でいくら固めても…立ち往生よ」 — telling him to 「同じ条件でもう一度測って」. He agrees to re-measure within the week, so redoing the experiment to gather data is his first task. Adding citations is the proposal she turned down; finishing the slides is deferred until 「データが出そろってから」; and contacting the conference secretariat is something the professor will do herself.',
  },
  {
    id: 'n1-listening-kadai-013',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '病院の事務室で女の事務長と男の職員が、会計の請求ミスについて話しています。' },
      { speaker: '男', text: '事務長、先月分の外来会計で、検査料を二重に請求していた例が見つかりました。' },
      { speaker: '女', text: '二重請求？システムを更新したあとの分じゃない、それ。' },
      { speaker: '男', text: 'おそらく。気づいた患者さんがお一人窓口にいらして、その場で返金はしたんですが。' },
      { speaker: '女', text: '一人で済む話かしらね。同じ処理をした会計がほかにもあるとしたら、黙っているわけにはいかないでしょう。' },
      { speaker: '男', text: 'では、該当しそうな患者さんに片っ端からお詫びの電話を入れます。' },
      { speaker: '女', text: '待って。何件あるかも分からないうちに動くと、かえって混乱を招くわよ。まず請求データを洗い出して、対象と金額の一覧を作るのが筋じゃない。' },
      { speaker: '男', text: 'わかりました。先月分を突き合わせてリストにします。' },
      { speaker: '女', text: 'お願い。システム会社への原因の確認はこちらから入れておくし、返金の段取りは一覧ができてから会計課と詰めましょう。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '請求データを調べて対象の一覧を作る',
      '該当する患者に電話でお詫びをする',
      '返金の手続きを進める',
      'システム会社に不具合の原因を問い合わせる',
    ],
    answerIndex: 0,
    explanation:
      '男の人提議逐一致電向患者道歉，被事務長以「何件あるかも分からないうちに動くと、かえって混乱を招く」婉拒，並指示「まず請求データを洗い出して…一覧を作るのが筋」，他也回答要比對上月資料做成清單，這就是首要工作。致電道歉是被擋下的提案；退費安排要等「一覧ができてから」再與會計課討論；向系統公司查原因由事務長那邊負責。',
    explanationEn:
      'The man proposes phoning every affected patient with apologies, but the administrator stops him with 「何件あるかも分からないうちに動くと、かえって混乱を招く」 and directs 「まず請求データを洗い出して…一覧を作るのが筋」; he agrees to cross-check last month\'s data and build the list, which is his first task. The apology calls are the rejected proposal; the refund arrangements will be worked out with the accounting section only 「一覧ができてから」; and querying the system vendor about the cause is being handled from the administrator\'s side.',
  },
  {
    id: 'n1-listening-kadai-014',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'ホテルの宴会部で男の部長と女のスタッフが、来週の企業の祝賀会について話しています。' },
      { speaker: '女', text: '部長、来週の山田物産様の祝賀会ですが、幹事の方から出席者が二十名ほど増えそうだと連絡がありました。' },
      { speaker: '男', text: '二十名か。定員ぎりぎりの会場だから、簡単には請け合えない数だな。' },
      { speaker: '女', text: 'ひとまずお受けできるとお返事して、席次表を作り直しましょうか。' },
      { speaker: '男', text: '安請け合いして当日料理が出ませんでした、では取り返しがつかないよ。人数が増えて一番きついのは厨房だろう。' },
      { speaker: '女', text: 'そうですね。では料理長に、二十食の追加が可能かどうか確かめてまいります。' },
      { speaker: '男', text: 'うん、まずそこだ。テーブルの追加のレイアウトは、厨房の返事を聞いてから考えれば十分。' },
      { speaker: '女', text: '飲み物の追加の発注はいかがしましょう。' },
      { speaker: '男', text: '飲料は当日でも業者が間に合わせてくれるから、担当の吉田さんに任せておけばいい。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '料理を追加できるかどうか厨房に確認する',
      '幹事に人数の増加を受けられると返事をする',
      '会場のテーブルの配置を考え直す',
      '飲み物を追加で発注する',
    ],
    answerIndex: 0,
    explanation:
      '她提議先答應幹事再改座位表，部長以「安請け合いして…取り返しがつかない」婉拒，點出「一番きついのは厨房」，她於是說要去向主廚確認能否加二十份餐，部長也肯定「まずそこだ」。回覆幹事是被擋下的輕率承諾；調整桌位配置要等「厨房の返事を聞いてから」；追加飲料交由負責的吉田處理，皆非她現在該做的事。',
    explanationEn:
      'She suggests accepting the extra guests first and redoing the seating chart, but the manager rejects the hasty promise with 「安請け合いして…取り返しがつかない」 and pinpoints that 「一番きついのは厨房」. She then says she will check with the head chef whether twenty extra meals are possible, and the manager confirms 「まずそこだ」. Replying yes to the organizer is the rash commitment he blocked; rethinking the table layout waits until 「厨房の返事を聞いてから」; and the extra drinks are left to Yoshida, the person in charge — none of these are her immediate task.',
  },
  {
    id: 'n1-listening-kadai-015',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '学会の事務局で女の事務局長と男のスタッフが、秋の大会に招く海外の講演者について話しています。' },
      { speaker: '男', text: '局長、基調講演のリー先生から、来日の準備を始めたいと連絡がありました。まず航空券を押さえてしまいましょうか。' },
      { speaker: '女', text: 'うーん、チケットが先というのはどうかしらね。ビザが下りなかったら、それこそ全部無駄になりかねないわよ。' },
      { speaker: '男', text: 'あ、リー先生の国からですと、査証が要るんでしたね。' },
      { speaker: '女', text: 'そう。それで申請には受け入れ側の招聘状が必須なの。うちがそれを出さないことには、先方は身動きが取れないわけ。' },
      { speaker: '男', text: 'では、招聘状の文面を整えて、今日中に先生にお送りします。' },
      { speaker: '女', text: 'ええ、急いでね。宿の手配は提携の旅行会社に回してあるから、心配いらないわ。' },
      { speaker: '男', text: 'プログラムの冊子には、先生のご略歴も載せるんですよね。' },
      { speaker: '女', text: '冊子の入稿は来月の頭よ。今やることじゃないでしょう。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '招聘状を作って講演者に送る',
      '講演者の航空券を手配する',
      '講演者が泊まるホテルを予約する',
      '冊子に載せる講演者の略歴を用意する',
    ],
    answerIndex: 0,
    explanation:
      '男の人提議先訂機票，局長以「チケットが先というのはどうかしら」「全部無駄になりかねない」委婉否定，指出簽證申請必須有主辦方的邀請函，「うちがそれを出さないことには、先方は身動きが取れない」，他於是說今天就把邀請函寄給講者，這是首要工作。訂機票是被婉拒的提案；住宿已交給合作旅行社；手冊履歷「今やることじゃない」，時程在下個月。',
    explanationEn:
      'The man proposes booking the flight first, but the director demurs with 「チケットが先というのはどうかしら」 and 「全部無駄になりかねない」: the visa application requires an invitation letter from the host — 「うちがそれを出さないことには、先方は身動きが取れない」. He then says he will send the invitation letter to the speaker today, which is his first task. Booking flights is the proposal she waved off; the hotel has already been passed to the partner travel agency; and the program-booklet biography 「今やることじゃない」, since the deadline is early next month.',
  },
  {
    id: 'n1-listening-kadai-016',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '銀行の支店で男の課長と女の窓口係が、閉店後の締めの作業について話しています。' },
      { speaker: '女', text: '課長、本日の締めで現金が一万円足りません。何度数えても合わないんです。' },
      { speaker: '男', text: '一万円か。まずは落ち着いて。' },
      { speaker: '女', text: '万一盗難だといけませんし、警察に相談しておいたほうがいいでしょうか。' },
      { speaker: '男', text: '届けを出すような話かどうか、まだ分からないだろう。こういうのは大抵、どこかの入力と現物の食い違いだよ。' },
      { speaker: '女', text: 'では、本部への報告はいかがしますか。' },
      { speaker: '男', text: '第一報は原因の見当がついてからで遅くないさ。それより、今日の伝票を一枚ずつ端末の記録と突き合わせるのが定石だ。' },
      { speaker: '女', text: 'わかりました。今日の分を全部当たってみます。' },
      { speaker: '男', text: '頼む。ＡＴＭの精査は担当の森さんが今やってくれているから、君は窓口の分に集中していい。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '今日の伝票を端末の記録と突き合わせる',
      '警察に現金の不足を相談する',
      '本部に第一報を入れる',
      'ＡＴＭの中の現金を精査する',
    ],
    answerIndex: 0,
    explanation:
      '課長認為短少多半是「入力と現物の食い違い」，指示「今日の伝票を一枚ずつ端末の記録と突き合わせるのが定石」，她也回答要清查今天全部傳票，故第一件事是逐張核對傳票與終端機紀錄。報警被「届けを出すような話かどうか、まだ分からない」委婉否定；向總行通報被延到「原因の見当がついてから」；ATM 清點由承辦的森さん負責中。',
    explanationEn:
      'The section chief judges the shortfall is most likely 「入力と現物の食い違い」 and instructs that 「今日の伝票を一枚ずつ端末の記録と突き合わせるのが定石」; she answers that she will go through all of today\'s slips, so matching each slip against the terminal records is her first task. Going to the police is gently dismissed with 「届けを出すような話かどうか、まだ分からない」; reporting to head office is postponed until 「原因の見当がついてから」; and the ATM audit is already being done by Mori, the person in charge.',
  },
  {
    id: 'n1-listening-kadai-017',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '設計事務所で女の所長と男の所員が、設計中の住宅の変更について話しています。' },
      { speaker: '男', text: '所長、青木様邸の件ですが、施主様が居間に吹き抜けを設けたいとおっしゃっていまして。' },
      { speaker: '女', text: '吹き抜けねえ。あの間取りだと二階の梁を抜くことになるから、意匠だけでは決められない話よ。' },
      { speaker: '男', text: 'ええ。ひとまず図面を描き直して、次の打ち合わせでお見せしようかと思うんですが。' },
      { speaker: '女', text: '絵にするのは簡単だけど、構造が成り立たない案をお見せしてぬか喜びさせるほうが、よほど罪じゃない？' },
      { speaker: '男', text: '確かにそうですね。では、構造事務所に耐震上の検討をお願いして、成立するかどうかを先に確かめます。' },
      { speaker: '女', text: 'そうね、まずそこから。概算の見積もりの直しは、案が固まってからで十分だし。' },
      { speaker: '男', text: '施主様へのご返事はいかがしましょう。' },
      { speaker: '女', text: '次の打ち合わせには私も同席するから、回答はその場で私からするわ。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '構造事務所に構造の検討を依頼する',
      '変更した間取りの図面を描き直す',
      '工事の見積もりを直す',
      '施主に変更できるかどうか返事をする',
    ],
    answerIndex: 0,
    explanation:
      '男の人想先改圖面給業主看，所長以「構造が成り立たない案をお見せしてぬか喜びさせるほうが、よほど罪じゃない？」委婉否定，他領會後說要先請結構事務所做耐震檢討、確認方案是否成立，所長也肯定「まずそこから」。重畫圖面是被擋下的提案；重算概估報價被延到「案が固まってから」；答覆業主由所長在下次會議上親自進行。',
    explanationEn:
      'The man wants to redraw the plans and show the client, but the director rebuffs it with 「構造が成り立たない案をお見せしてぬか喜びさせるほうが、よほど罪じゃない？」. Taking the hint, he says he will first ask the structural engineering office for a seismic review to confirm the atrium is feasible, and she endorses it with 「まずそこから」. Redrawing the plans is the blocked proposal; revising the rough estimate is deferred until 「案が固まってから」; and answering the client will be done by the director herself at the next meeting.',
  },
  {
    id: 'n1-listening-kadai-018',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '劇団の稽古場で男の演出家と女の制作担当が、来月の公演について話しています。' },
      { speaker: '女', text: '昨日の稽古で足を痛めた高橋さんですが、全治三週間だそうです。初日には間に合いません。' },
      { speaker: '男', text: '三週間か。主役だけに痛いな。' },
      { speaker: '女', text: 'いっそ劇場に相談して、公演を一週間延ばしていただくというのはどうでしょう。' },
      { speaker: '男', text: '延期はチケットの払い戻しやら会場費やらで、かえって傷口を広げるだけだよ。最後の手段に取っておこう。' },
      { speaker: '女', text: 'では、以前から代役にと名前が挙がっていた村井さんに当たってみましょうか。' },
      { speaker: '男', text: 'そうだな。彼の都合がつくかどうかで打つ手が全部変わってくる。今日中に返事をもらってくれ。' },
      { speaker: '女', text: 'わかりました。お客様へのご案内はどうしましょう。' },
      { speaker: '男', text: '告知は配役が決まってからで十分。高橋さんの治療のほうは、ご本人とマネージャーに任せるしかないしね。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '代役の候補に出演できるかどうか連絡する',
      '劇場に公演の延期を相談する',
      '客に配役の変更を案内する',
      'けがをした俳優の治療の手配をする',
    ],
    answerIndex: 0,
    explanation:
      '她提議請劇場延期，演出家以「かえって傷口を広げるだけ」「最後の手段に取っておこう」委婉否定；接著她提出去問候補代角村井，演出家表示「彼の都合がつくかどうかで打つ手が全部変わってくる」並要求「今日中に返事をもらってくれ」，所以第一件事是聯絡代角確認能否演出。延期是被擋下的方案；對觀眾的告知要等「配役が決まってから」；傷者的治療交由本人與經紀人處理。',
    explanationEn:
      'Her idea of asking the theater to postpone is rejected with 「かえって傷口を広げるだけ」 and 「最後の手段に取っておこう」. She then suggests approaching Murai, the long-floated understudy, and the director says 「彼の都合がつくかどうかで打つ手が全部変わってくる」 and orders 「今日中に返事をもらってくれ」 — so contacting the understudy to confirm his availability is her first task. Postponement is the option shelved as a last resort; notifying the audience waits until 「配役が決まってから」; and the injured actor\'s treatment is left to him and his manager.',
  },
  {
    id: 'n1-listening-kadai-019',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '貿易会社で女の課長と男の担当者が、税関で止まっている輸入貨物について話しています。' },
      { speaker: '男', text: '課長、シンガポールからの部品ですが、原産地証明書の品目の記載が申告と食い違っていて、税関で保留になっています。' },
      { speaker: '女', text: 'またなの。それで、どうするつもり？' },
      { speaker: '男', text: '通関士さんを通じて事情を説明すれば、何とか通していただけないかと。' },
      { speaker: '女', text: '書類の不一致は、お願いでどうにかなる筋のものじゃないでしょう。正しい証明書がない限り、一歩も動かないわよ。' },
      { speaker: '男', text: 'ですよね。では、輸出者に証明書の再発行を今日中に依頼します。' },
      { speaker: '女', text: 'ええ、それが先決。急がせてね。倉庫の保管料の減免の交渉は、荷物が出る目処が立ってからで構わないから。' },
      { speaker: '男', text: '納品先への遅延のご連絡はいかがしますか。' },
      { speaker: '女', text: '得意先への説明は営業の窓口からするのが筋よ。こちらは状況をまとめて渡すだけでいいわ。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '輸出者に原産地証明書の再発行を頼む',
      '税関に事情を説明して通してもらう',
      '倉庫の保管料の減免を交渉する',
      '納品先に遅れることを連絡する',
    ],
    answerIndex: 0,
    explanation:
      '男の人想透過報關士向海關說情放行，被課長以「お願いでどうにかなる筋のものじゃない」「正しい証明書がない限り、一歩も動かない」委婉否定，他於是說今天就請出口商重發證明書，課長也肯定「それが先決」。向海關說情是被擋下的提案；倉租減免交涉被延到「荷物が出る目処が立ってから」；通知客戶延遲由業務窗口出面，他只需彙整狀況。',
    explanationEn:
      'The man hopes to have the customs broker plead their case, but the section chief rejects it: 「お願いでどうにかなる筋のものじゃない」 and 「正しい証明書がない限り、一歩も動かない」. He then says he will ask the exporter today to reissue the certificate of origin, and she confirms 「それが先決」 — so requesting the reissue is his first task. Explaining things to customs is the proposal she shot down; negotiating a warehouse-fee reduction is deferred until 「荷物が出る目処が立ってから」; and informing the customer of the delay is properly the sales desk\'s job — he only needs to hand over a summary of the situation.',
  },
  {
    id: 'n1-listening-kadai-020',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '大学の国際交流課で男の課長と女の職員が、来月来日する交換留学生について話しています。' },
      { speaker: '女', text: '課長、ハノイ大学のグエンさんから、来日まで一か月なのに住まいが決まらず不安だとメールが来ています。' },
      { speaker: '男', text: '留学生寮の抽選、彼女は外れたんだったね。' },
      { speaker: '女', text: 'はい。ですので、大学周辺の民間アパートのリストをお送りして、ご自分で選んでいただこうかと。' },
      { speaker: '男', text: '来日前に外国から民間と契約するのは、保証人やら初期費用やらで現実には難しいよ。それでは放り出すようなものだ。' },
      { speaker: '女', text: '確かにそうですね。では、寮の管理事務所に、辞退などで空きが出ていないか確認してみます。' },
      { speaker: '男', text: 'うん、まずそれだ。この時期は辞退が出やすいから、望みはあるよ。' },
      { speaker: '女', text: 'もし空きがなかった場合のご相談は。' },
      { speaker: '男', text: 'そのときは提携の学生会館に私から掛け合うよ。オリエンテーションの資料は、来日の日程が固まってからでいいからね。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '寮に空きがないか管理事務所に確認する',
      '民間アパートのリストを留学生に送る',
      '提携の学生会館に相談する',
      'オリエンテーションの資料を準備する',
    ],
    answerIndex: 0,
    explanation:
      '她提議寄民間公寓清單讓留學生自己找，課長以「現実には難しい」「放り出すようなものだ」委婉否定，她改口說要向宿舍管理處確認有無因辭退空出的床位，課長也肯定「まずそれだ」，故第一件事是向宿舍管理處確認空房。寄公寓清單是被擋下的提案；洽詢合作學生會館是宿舍沒空位時才由課長出面；說明會資料被延到「来日の日程が固まってから」。',
    explanationEn:
      'Her plan to send a list of private apartments is rejected by the section chief as 「現実には難しい」 — signing privately from abroad means guarantors and move-in fees — and 「放り出すようなものだ」. She revises course: check with the dormitory office whether any spots opened up through withdrawals, and he confirms 「まずそれだ」, so that is her first task. Sending the apartment list is the blocked proposal; approaching the affiliated student hall is a fallback the chief himself will pursue only if no dorm space exists; and the orientation materials are deferred until 「来日の日程が固まってから」.',
  },
  {
    id: 'n1-listening-kadai-021',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '食品メーカーの開発部で女の課長と男の社員が、新商品の試食会の準備について話しています。' },
      { speaker: '男', text: '課長、来週の焼き菓子の試食会ですが、アンケート用紙の案ができましたので、先に印刷してしまおうかと思います。' },
      { speaker: '女', text: '用紙は前日に刷れば足りるでしょう。それより、参加者にお見せする原材料の表示は用意できてるの？' },
      { speaker: '男', text: '表示、ですか。社内のモニターさんだけですし、聞かれたら口頭で説明すれば済むかと思っていたんですが。' },
      { speaker: '女', text: '口頭でというわけにはいかないわよ。アレルギーのある方が口にしてからでは、取り返しがつかないもの。' },
      { speaker: '男', text: 'おっしゃるとおりです。では、工場に原材料の一覧を問い合わせて、表示のカードを作ります。' },
      { speaker: '女', text: 'ええ、まずそこからね。試作品の追加は工場が焼いてくれる手はずだから、心配いらないわ。' },
      { speaker: '男', text: '会場の設営はいかがしましょう。' },
      { speaker: '女', text: '机や椅子は当日の朝で十分間に合うでしょう。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '工場に原材料の一覧を問い合わせる',
      'アンケート用紙を印刷する',
      '試作品を追加で作る',
      '会場に机や椅子を並べる',
    ],
    answerIndex: 0,
    explanation:
      '男の人想先印問卷，課長以「用紙は前日に刷れば足りる」擋下，並警告有過敏的參加者「口にしてからでは、取り返しがつかない」，要求先備妥原料標示，他於是說要向工廠查詢原料清單、製作標示卡，這是首要工作。印問卷前一天再印即可；追加試作品由工廠負責；會場桌椅「当日の朝で十分間に合う」，都不是他現在該做的事。',
    explanationEn:
      'The man wants to print the questionnaires first, but the section chief brushes that aside with 「用紙は前日に刷れば足りる」 and warns that with allergy sufferers 「口にしてからでは、取り返しがつかない」, so the ingredient labeling must come first. He then says he will ask the factory for the ingredient list and make the display cards — his first task. Printing can wait until the day before; the extra samples are the factory\'s job; and setting out tables and chairs 「当日の朝で十分間に合う」.',
  },
  {
    id: 'n1-listening-kadai-022',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '旅行会社で男の部長と女の社員が、パンフレットの改訂について話しています。' },
      { speaker: '女', text: '部長、春のパンフレットの改訂版ですが、料金の差し替えが終わりましたので、今日中に印刷所へ入稿しようかと思います。' },
      { speaker: '男', text: 'ちょっと待って。掲載している旅館のうち、確か海沿いの一軒が今月で休業するという話がなかったか。' },
      { speaker: '女', text: 'ああ、噂は耳にしましたが、正式な連絡は受けていません。' },
      { speaker: '男', text: '載せてしまってから休業でしたでは、お客様を欺くことになりかねないよ。まず一軒ずつ営業の予定を確かめるのが筋だろう。' },
      { speaker: '女', text: 'わかりました。掲載施設に片っ端から電話を入れて、営業状況を確認します。' },
      { speaker: '男', text: '頼むよ。入稿はその返事がそろってからでも、日程には十分間に合う。' },
      { speaker: '女', text: '表紙の写真も新しくしたほうがいいでしょうか。' },
      { speaker: '男', text: '表紙まで手を広げると切りがない。今回は中身だけでいこう。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '掲載している施設に営業の予定を確認する',
      'パンフレットを印刷所に入稿する',
      '料金のページを差し替える',
      '表紙の写真を新しくする',
    ],
    answerIndex: 0,
    explanation:
      '她想當天就送印，部長以「載せてしまってから休業でしたでは、お客様を欺くことになりかねない」擋下，指示「まず一軒ずつ営業の予定を確かめるのが筋」，她也回答要逐一致電刊載的設施確認營業狀況，這就是首要工作。送印被延到回覆到齊之後；價格頁早已替換完成；更換封面照片被「今回は中身だけでいこう」否決。',
    explanationEn:
      'She wants to send the pamphlet to the printer today, but the manager stops her with 「載せてしまってから休業でしたでは、お客様を欺くことになりかねない」 and directs 「まず一軒ずつ営業の予定を確かめるのが筋」; she agrees to phone every listed facility to confirm its operating plans, which is her first task. Submitting to the printer is deferred until the replies are in; the price pages have already been replaced; and refreshing the cover photo is rejected with 「今回は中身だけでいこう」.',
  },
  {
    id: 'n1-listening-kadai-023',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '保育園で女の園長と男の保育士が、運動会の準備について話しています。' },
      { speaker: '男', text: '園長先生、運動会のプログラムが刷り上がりました。今日のお迎えの時に配って、案内のメールも流そうと思います。' },
      { speaker: '女', text: 'それなんだけど、雨が降った場合の会場、プログラムにはどう書いてあるの？' },
      { speaker: '男', text: '例年どおり、隣の小学校の体育館としてあります。' },
      { speaker: '女', text: '今年は体育館に工事が入るって、この間の連絡会で聞いたわよ。借りられる前提で配って、当日使えませんでしたでは済まないでしょう。' },
      { speaker: '男', text: 'それは確認していませんでした。では、小学校に体育館を貸していただけるかどうか、先に問い合わせます。' },
      { speaker: '女', text: 'そうして。配布もメールも、その返事を聞いてからで遅くないわ。' },
      { speaker: '男', text: '玉入れなどの道具の点検はいかがしましょう。' },
      { speaker: '女', text: '道具は主任の先生が見てくれているから、あなたはまず小学校よ。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '小学校に体育館を借りられるか問い合わせる',
      'プログラムを保護者に配る',
      '保護者に案内のメールを送る',
      '運動会の道具を点検する',
    ],
    answerIndex: 0,
    explanation:
      '男の人打算今天發放節目表並寄通知信，園長點出小學體育館今年「工事が入る」，警告「借りられる前提で配って、当日使えませんでしたでは済まない」，他於是說要先向小學詢問能否出借體育館，園長最後也強調「あなたはまず小学校よ」。發放與寄信都被「その返事を聞いてからで遅くない」延後；器材檢查由主任負責，皆非他的首要工作。',
    explanationEn:
      'The man plans to hand out the programs and send the notice email today, but the director reveals the elementary school gym 「工事が入る」 this year and warns 「借りられる前提で配って、当日使えませんでしたでは済まない」. He then says he will first ask the school whether the gym can be borrowed, and she closes with 「あなたはまず小学校よ」. Both the handout and the email are deferred by 「その返事を聞いてからで遅くない」, and the equipment check is already being handled by the head teacher.',
  },
  {
    id: 'n1-listening-kadai-024',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '新聞社で男のデスクと女の記者が、来週の取材の段取りについて話しています。' },
      { speaker: '女', text: 'デスク、老舗の醤油蔵の特集ですが、質問のリストがまとまりましたので、今日先方にお送りしようと思います。' },
      { speaker: '男', text: '質問はまだいいよ。それより、蔵の中の撮影、先方の返事はもらえたのか。' },
      { speaker: '女', text: 'いえ、広報の方が検討中とのことで、まだです。' },
      { speaker: '男', text: '写真が撮れるかどうかで、紙面の作りが根本から変わるだろう。文章だけの構成なら、聞くことも増えるわけだし。' },
      { speaker: '女', text: '確かに、そこが決まらないことには質問も固められませんね。では、広報に撮影の可否を確認します。' },
      { speaker: '男', text: 'うん、まずそれだ。急かすようで悪いが、返事の期限を切らせてもらいなさい。' },
      { speaker: '女', text: 'カメラマンの手配はいかがしましょう。' },
      { speaker: '男', text: '手配は撮れると決まってからで十分。日程の調整なら、私のほうで先方の社長と話しておくよ。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '取材先に撮影ができるかどうか確認する',
      '質問のリストを先方に送る',
      'カメラマンを手配する',
      '取材の日程を調整する',
    ],
    answerIndex: 0,
    explanation:
      '她想先把提問清單寄給對方，デスク以「質問はまだいいよ」擋下，指出「写真が撮れるかどうかで、紙面の作りが根本から変わる」，她也認同「そこが決まらないことには質問も固められません」，故第一件事是向對方公關確認能否攝影。寄清單順序在後；攝影師「撮れると決まってから」再安排；日程協調由デスク親自與對方社長談。',
    explanationEn:
      'She wants to send the question list to the brewery first, but the desk editor waves it off with 「質問はまだいいよ」 and points out 「写真が撮れるかどうかで、紙面の作りが根本から変わる」; she concedes 「そこが決まらないことには質問も固められません」, so confirming with their PR whether photography is allowed is her first task. Sending the questions comes later; arranging a photographer waits until 「撮れると決まってから」; and the scheduling will be handled by the desk editor himself with the company president.',
  },
  {
    id: 'n1-listening-kadai-025',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '家具メーカーで女の部長と男の社員が、来月の展示会への出展準備について話しています。' },
      { speaker: '男', text: '部長、展示会で配るカタログですが、在庫が心もとないので、増刷をかけようと思います。' },
      { speaker: '女', text: '増刷の前に聞くけど、目玉にする新作の椅子、強度試験の結果はもう出たの？' },
      { speaker: '男', text: 'いえ、試験部門からはまだ何も。ただ、設計上は問題ないはずですので、出展する前提で進めていました。' },
      { speaker: '女', text: '万一基準に届かなかったら、目玉を差し替えることになるのよ。そうなればカタログの中身ごと変わるでしょう。刷ってからでは紙くずになりかねないわ。' },
      { speaker: '男', text: 'おっしゃるとおりです。では、試験部門に結果がいつ出るのか確認して、急いでもらいます。' },
      { speaker: '女', text: 'ええ、何をおいてもまずそこ。ブースの装飾は、業者に任せてあるから手を出さなくていいわ。' },
      { speaker: '男', text: '展示品を運ぶトラックの手配はいかがしましょう。' },
      { speaker: '女', text: '運送は出展する品が確定してからで間に合うわよ。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '試験部門に強度試験の結果を確認する',
      'カタログの増刷を発注する',
      'ブースの装飾を業者に頼む',
      '展示品を運ぶトラックを手配する',
    ],
    answerIndex: 0,
    explanation:
      '男の人想加印型錄，部長點出主打新品椅子的強度測試結果未出，警告一旦換掉主打品「刷ってからでは紙くずになりかねない」，他於是說要向測試部門確認結果何時出爐並請對方加急，部長也強調「何をおいてもまずそこ」。加印被擋在展品確定之前；攤位裝飾「業者に任せてある」不必插手；卡車運送「出展する品が確定してから」再安排即可。',
    explanationEn:
      'The man wants to order a reprint of the catalog, but the manager points out that the strength test results for the flagship new chair are not in yet, warning that if the centerpiece changes, 「刷ってからでは紙くずになりかねない」. He then says he will check with the testing department on when the results will come and ask them to hurry, and she stresses 「何をおいてもまずそこ」. The reprint is blocked until the exhibits are settled; the booth decoration is 「業者に任せてある」; and arranging the truck can wait until 「出展する品が確定してから」.',
  },
  {
    id: 'n1-listening-kadai-026',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '鉄道会社で男の課長と女の社員が、ダイヤ改正の告知のポスターについて話しています。' },
      { speaker: '女', text: '課長、来春のダイヤ改正のポスター案ができました。校了にして、印刷に回してよろしいでしょうか。' },
      { speaker: '男', text: 'デザインは悪くないね。ただ、この乗り継ぎ案内の欄、バスの時刻も載せてるだろう。' },
      { speaker: '女', text: 'はい、駅前のバスとの接続が売りですので、目立つように入れました。' },
      { speaker: '男', text: 'バス会社も同じ日に改正するはずだよ。先方の新しい時刻を確かめずに刷って、実際と食い違っていたら、苦情どころの話じゃなくなる。' },
      { speaker: '女', text: 'そうでした。では、バス会社に改正後の時刻表を照会して、突き合わせてから入稿します。' },
      { speaker: '男', text: 'そうしてくれ。駅への掲示の割り振りは、刷り上がってから考えれば済むことだし。' },
      { speaker: '女', text: 'ウェブサイトの告知はいかがしますか。' },
      { speaker: '男', text: 'サイトの更新は広報の担当だから、データを渡せばやってくれるよ。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      'バス会社に改正後の時刻を確認する',
      'ポスターを印刷に回す',
      '駅への掲示の割り振りを考える',
      'ウェブサイトの告知を更新する',
    ],
    answerIndex: 0,
    explanation:
      '她想定稿送印，課長點出巴士公司同日也要改點，「先方の新しい時刻を確かめずに刷って、実際と食い違っていたら、苦情どころの話じゃなくなる」，她於是說要先向巴士公司照會改點後的時刻表、核對後再入稿，這是首要工作。送印因此延後；車站張貼的分配「刷り上がってから考えれば済む」；網站更新是公關的職掌，交出資料即可。',
    explanationEn:
      'She wants to finalize the poster and send it to print, but the section chief notes the bus company revises its timetable the same day: 「先方の新しい時刻を確かめずに刷って、実際と食い違っていたら、苦情どころの話じゃなくなる」. She then says she will query the bus company for the revised times and cross-check before submitting, which is her first task. Printing is therefore postponed; allocating the station postings 「刷り上がってから考えれば済む」; and updating the website is the PR team\'s job once she hands over the data.',
  },
  {
    id: 'n1-listening-kadai-027',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '農産物直売所で女の店長と男のスタッフが、来月の収穫祭のイベントについて話しています。' },
      { speaker: '男', text: '店長、収穫祭のチラシの案ができました。焼き芋の振る舞いを大きく載せたので、今週中に配り始めようと思います。' },
      { speaker: '女', text: '振る舞いといえば、その場で焼いて配るのよね。火を使って食べ物を出すなら、保健所への届け出が要るんじゃなかった？' },
      { speaker: '男', text: 'えっ、無料で配るだけでも要るんでしょうか。' },
      { speaker: '女', text: '要るかどうかを私たちの判断で決めるのが一番危ないのよ。当日になって中止では、チラシがかえって仇になるでしょう。' },
      { speaker: '男', text: 'おっしゃるとおりです。では、保健所に届け出が必要かどうか、まず問い合わせます。' },
      { speaker: '女', text: 'ええ、そこがはっきりしてから配っても遅くないわ。テントは役場が貸してくれることになってるから、大丈夫。' },
      { speaker: '男', text: '芋掘り体験の畑のほうは。' },
      { speaker: '女', text: '畑は田中さんの農家と話がついてるわ。あなたはまず保健所ね。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '保健所に届け出が要るかどうか問い合わせる',
      '収穫祭のチラシを配り始める',
      '役場にテントを借りに行く',
      '芋掘り体験の畑を農家に頼む',
    ],
    answerIndex: 0,
    explanation:
      '男の人想本週開始發傳單，店長質疑現場烤地瓜分送可能需要向保健所報備，並以「要るかどうかを私たちの判断で決めるのが一番危ない」「チラシがかえって仇になる」提醒不能自行認定，他於是說要先向保健所詢問是否需要報備，店長最後也說「あなたはまず保健所ね」。發傳單被延到「そこがはっきりしてから」；帳篷已談妥由公所出借；地瓜田也已與田中農家談定。',
    explanationEn:
      'The man wants to start handing out flyers this week, but the manager questions whether serving grilled sweet potatoes on site requires notifying the health office, warning 「要るかどうかを私たちの判断で決めるのが一番危ない」 and 「チラシがかえって仇になる」. He then says he will first ask the health office whether a notification is needed, and she closes with 「あなたはまず保健所ね」. The flyers are deferred until 「そこがはっきりしてから」; the tent is already promised on loan from the town office; and the field is settled with farmer Tanaka.',
  },
  {
    id: 'n1-listening-kadai-028',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'ソフトウェア会社で男の部長と女の社員が、製品マニュアルの多言語化について話しています。' },
      { speaker: '女', text: '部長、マニュアルの英語版と中国語版の件、見積もりが出そろいましたので、翻訳会社に発注しようと思います。' },
      { speaker: '男', text: '発注の前に確認だが、元になる日本語版は最新の内容になってるのか。' },
      { speaker: '女', text: 'いえ、実は先月の更新で加わった機能が、まだ反映されていません。翻訳と並行して直せば間に合うかと。' },
      { speaker: '男', text: '並行はやめたほうがいい。古い版を訳させて、あとから直しを訳し足すのでは、二度手間の上に訳語もぶれるよ。' },
      { speaker: '女', text: '確かにそうですね。では、開発チームに仕様を確認して、まず日本語版を最新の内容に改めます。' },
      { speaker: '男', text: 'うん、それが先だ。発注は原稿が固まってからにしよう。' },
      { speaker: '女', text: '画面の図の差し替えはいかがしますか。' },
      { speaker: '男', text: '図は開発が撮り直してくれる手はずだから、上がりを待てばいい。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '日本語のマニュアルを最新の内容に直す',
      '翻訳会社に翻訳を発注する',
      '画面の図を撮り直す',
      '翻訳の見積もりを取り寄せる',
    ],
    answerIndex: 0,
    explanation:
      '她想直接向翻譯公司下單，部長追問日文原稿是否為最新版，並以「二度手間の上に訳語もぶれる」否定邊譯邊改的提案，她於是說要先向開發團隊確認規格、把日文版改成最新內容，部長也肯定「それが先だ」。下單被延到「原稿が固まってから」；畫面截圖由開發部門重拍、等成品即可；報價早已到齊，無須再取。',
    explanationEn:
      'She wants to place the order with the translation agency right away, but the manager asks whether the Japanese original is up to date and rejects translating in parallel with 「二度手間の上に訳語もぶれる」. She then says she will confirm the specs with the development team and first bring the Japanese manual up to date, and he affirms 「それが先だ」. The order is deferred until 「原稿が固まってから」; the screenshots will be retaken by the developers, so she only waits for them; and the quotes are already in, so nothing needs collecting.',
  },
  {
    id: 'n1-listening-kadai-029',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '健診センターで女の主任と男の職員が、健康診断の案内状の発送について話しています。' },
      { speaker: '男', text: '主任、秋の健診の案内状が刷り上がりました。今日から封筒に詰めて、順次発送しようと思います。' },
      { speaker: '女', text: '待って。宛名に使う名簿、いつのデータかしら。' },
      { speaker: '男', text: '確か、去年の春に契約先からいただいたものです。' },
      { speaker: '女', text: '一年半も前のじゃない。異動や退職で対象から外れた方も多いはずよ。届かないだけならまだしも、辞めた方の分を会社に送りつけたら、信用に関わるわ。' },
      { speaker: '男', text: 'おっしゃるとおりです。では、各契約先に最新の名簿を出していただくよう、まず依頼します。' },
      { speaker: '女', text: 'ええ、封入はそれからで十分間に合うから。' },
      { speaker: '男', text: '会場の予約の確認はいかがしましょう。' },
      { speaker: '女', text: '会場は先週私が押さえ直したところよ。あなたは名簿に専念して。' },
    ],
    question: '男の人はこのあとまず何をしなければなりませんか。',
    options: [
      '契約先に最新の名簿を頼む',
      '案内状を封筒に詰めて発送する',
      '案内状を印刷する',
      '会場の予約を確認する',
    ],
    answerIndex: 0,
    explanation:
      '男の人想今天就開始裝封發送，主任質疑名冊是一年半前的舊資料，警告寄給已離職者「信用に関わる」，他於是說要先請各簽約企業提供最新名冊，這是首要工作。裝封被「封入はそれからで十分間に合う」延後；通知函已經印好，不需再印；會場預約上週由主任親自重新確認過，輪不到他做。',
    explanationEn:
      'The man wants to start stuffing envelopes and mailing today, but the supervisor questions the roster — data from a year and a half ago — and warns that mailing letters for people who have left 「信用に関わる」. He then says he will first ask each client company to provide an up-to-date roster, which is his first task. The stuffing is deferred with 「封入はそれからで十分間に合う」; the invitation letters are already printed; and the venue booking was re-secured by the supervisor herself just last week.',
  },
  {
    id: 'n1-listening-kadai-030',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '環境保護団体の事務所で男の代表と女のスタッフが、海岸の清掃活動について話しています。' },
      { speaker: '女', text: '代表、再来月の海岸清掃ですが、日取りの案が固まりましたので、ＳＮＳで参加者の募集を始めようと思います。' },
      { speaker: '男', text: '募集の前に、市への届け出はもう出したんだっけ。あの海岸、団体で使うときは市の許可が要るだろう。' },
      { speaker: '女', text: 'いえ、まだです。例年認めていただいているので、形だけかと思って後回しにしていました。' },
      { speaker: '男', text: '今年は近くで護岸の工事が始まるって聞いたよ。日程が重なって許可が下りなかったら、募集してから日を変える羽目になる。それでは参加者の信用を失いかねないよ。' },
      { speaker: '女', text: 'おっしゃるとおりですね。では、市役所に使用の届け出を出して、許可の見通しを確かめます。' },
      { speaker: '男', text: 'うん、まずそれだ。ごみ袋や軍手は協賛の会社が送ってくれる手はずだから、心配いらない。' },
      { speaker: '女', text: '集めたごみの処分はいかがしましょう。' },
      { speaker: '男', text: '回収は例年どおり市の清掃課がやってくれるよ。届け出のついでに、日程だけ伝えておいて。' },
    ],
    question: '女の人はこのあとまず何をしなければなりませんか。',
    options: [
      '市役所に海岸を使う届け出を出す',
      'ＳＮＳで参加者の募集を始める',
      'ごみ袋や軍手を用意する',
      '集めたごみの処分を手配する',
    ],
    answerIndex: 0,
    explanation:
      '她想在ＳＮＳ開始招募參加者，代表點出該海岸供團體使用需要市府許可，且今年附近有護岸工程，「募集してから日を変える羽目になる」會失信於參加者，她於是說要先向市公所提出使用申請、確認許可展望，代表也說「まずそれだ」。招募順序在後；垃圾袋與棉紗手套由贊助企業寄來；垃圾清運照往例由市府清潔單位負責，只需順道告知日程。',
    explanationEn:
      'She wants to start recruiting participants on social media, but the leader points out the beach requires the city\'s permission for group use, and with seawall works starting nearby this year, 「募集してから日を変える羽目になる」 would cost them the participants\' trust. She then says she will file the use notification with city hall and check the outlook for approval, and he confirms 「まずそれだ」. Recruiting comes afterward; the garbage bags and gloves will be sent by a sponsor company; and the collected garbage will be hauled by the city\'s sanitation section as in past years.',
  },
]
