import type { JlptQuestion } from '../../types'

export const questions: JlptQuestion[] = [
  {
    id: 'n1-listening-togo-001',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '美術館で、係の人の説明を聞いて、夫婦が話しています。' },
      { speaker: '男', text: '本日は四つの講座をご用意しております。まず、浮世絵の摺り体験は午前十時からですが、大変人気のため、すでに満席となっております。' },
      { speaker: '男', text: '漆芸の蒔絵体験は午後二時からで、金粉を使って小箱に絵を描いていただきます。道具はすべてこちらでご用意いたします。' },
      { speaker: '男', text: '仏像の見方講座は夕方五時から、学芸員がスライドを使って鑑賞のポイントを解説いたします。' },
      { speaker: '男', text: '最後に、日本庭園のガイドツアーは午後三時からですが、雨天の場合は中止となりますので、ご了承ください。' },
      { speaker: '女', text: '浮世絵の摺り、ずっとやってみたかったのに、もう満席ですって。残念だわ。' },
      { speaker: '男', text: 'だったら蒔絵はどう？手を動かす体験なら、こっちも負けず劣らず面白そうだよ。' },
      { speaker: '女', text: 'そうね。金粉で絵を描くなんてめったにできないもの。私はそれにするわ。あなたは？' },
      { speaker: '男', text: '僕は体を動かすより話を聞きたい気分だな。夕方の解説を聞きに行くよ。庭園も捨てがたいけど、午後から雲行きが怪しいらしいからね。' },
      { speaker: '女', text: '分かったわ。じゃあ、終わったらロビーで待ち合わせましょう。' },
    ],
    question: '女の人はどの講座に参加しますか。',
    options: [
      '漆芸の蒔絵体験',
      '浮世絵の摺り体験',
      '仏像の見方講座',
      '日本庭園のガイドツアー',
    ],
    answerIndex: 0,
    explanation:
      '女の人原本最想參加浮世繪拓印體驗，但一開場館方就宣布已滿席；經丈夫提議後她說「私はそれにするわ」，改選下午的漆藝蒔繪體驗。「浮世絵の摺り体験」是她被迫放棄的第一志願；「仏像の見方講座」是男の人自己要去聽的，屬於「男方選項」混淆；「日本庭園のガイドツアー」則因下午天氣可能轉壞、雨天中止而被排除。',
    explanationEn:
      'The woman most wanted the ukiyo-e printing workshop, but the staff announces at the start that it is already full; after her husband’s suggestion she says 「私はそれにするわ」 and switches to the afternoon maki-e lacquer workshop. 「浮世絵の摺り体験」 is the first choice she was forced to give up; 「仏像の見方講座」 is what the husband decides to attend, a his-choice decoy; and 「日本庭園のガイドツアー」 is ruled out because the weather looks likely to turn and it is canceled in rain.',
  },
  {
    id: 'n1-listening-togo-002',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '旅行会社で、店員の説明を聞いて、夫婦が話しています。' },
      { speaker: '男', text: '日帰りバスツアーは、現在四つございます。まず「老舗巡りと食べ歩き」は、城下町を三時間ほど歩いてまわるコースです。' },
      { speaker: '男', text: '「温泉と海鮮市場」は、露天風呂にゆっくり浸かったあと、市場で新鮮な海の幸を召し上がっていただきます。' },
      { speaker: '男', text: '「紅葉クルーズ」は、湖の上から山々の紅葉を眺める一番人気のコースですが、朝六時集合と、出発がかなり早めでございます。' },
      { speaker: '男', text: 'それから「陶芸と酒蔵見学」は、湯のみ作りを体験したあと、地元の酒蔵を見学して、試飲も楽しめるコースです。' },
      { speaker: '女', text: '紅葉クルーズ、写真で見たら本当に素敵だったんだけど、朝六時集合はさすがに無理だわ。' },
      { speaker: '男', text: '食べ歩きは？君、こういうの好きだろう。' },
      { speaker: '女', text: '好きだけど、先週痛めた足で三時間も歩き回るのはちょっとね。それより、自分で器を作って、お酒の試飲までできるなんて贅沢じゃない？' },
      { speaker: '男', text: 'なるほどね。僕は歩くのも作るのも面倒だから、のんびり湯に浸かって、うまいものを食べるほうにするよ。' },
      { speaker: '女', text: 'あら、別々になっちゃうけど、たまにはいいか。じゃあ、それぞれ申し込みましょう。' },
    ],
    question: '女の人はどのツアーに申し込みますか。',
    options: [
      '陶芸と酒蔵見学のツアー',
      '温泉と海鮮市場のツアー',
      '紅葉クルーズのツアー',
      '老舗巡りと食べ歩きのツアー',
    ],
    answerIndex: 0,
    explanation:
      '女の人先以「朝六時集合はさすがに無理」放棄最想去的紅葉遊船，又因上週腳受傷、無法走三小時而婉拒老店食べ歩き，最後被「自己做陶器還能試飲日本酒」吸引，決定報名陶藝加酒藏參觀。「温泉と海鮮市場」是丈夫選的行程，屬於「男方選項」混淆；遊船與食べ歩き都是對話中被她親口否定的選項。',
    explanationEn:
      'The woman first gives up the foliage cruise she most wanted, saying 「朝六時集合はさすがに無理」, then declines the old-shop food walk because her foot, injured last week, cannot take three hours of walking. She is finally drawn to making her own pottery plus sake tasting and signs up for the pottery-and-brewery tour. 「温泉と海鮮市場」 is the husband’s pick, a his-choice decoy, while the cruise and the food walk are both options she rejects out of her own mouth in the dialogue.',
  },
  {
    id: 'n1-listening-togo-003',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で、男の人と女の人が創立五十周年の記念企画について話しています。' },
      { speaker: '男', text: '企画案は四つに絞られたね。ホールを借りての記念コンサート、全商品対象の感謝セール、お客様向けの工場見学ツアー、それから、商品の写真を投稿してもらうSNSのフォトコンテスト。' },
      { speaker: '女', text: '私はコンサートに惹かれます。五十周年ならではの華やかさが出せますから。' },
      { speaker: '男', text: '気持ちは分かるけど、ホールの使用料と出演料で予算を倍近く超えるんだ。今回は見送らざるを得ないな。' },
      { speaker: '女', text: 'では、感謝セールはどうでしょう。お客様に直接還元できますよ。' },
      { speaker: '男', text: 'セールは毎年やってるだろう。周年の特別感という点では、ちょっと弱い気がするな。' },
      { speaker: '女', text: '確かに。工場見学は、うちのものづくりを直接知ってもらえる、いい機会だと思いますが。' },
      { speaker: '男', text: '悪くないんだが、安全管理の準備に半年はかかるらしい。式典まで三か月しかない今からじゃ、間に合わないよ。' },
      { speaker: '女', text: 'となると、残るのは投稿コンテストですね。費用も抑えられますし、若い層にうちの商品を知ってもらうきっかけにもなります。' },
      { speaker: '男', text: 'そうだな。賞品を工夫すれば盛り上がるだろうし、それでいこう。' },
    ],
    question: '二人はどの企画にすることにしましたか。',
    options: [
      'SNSのフォトコンテスト',
      '記念コンサート',
      'お客様向けの工場見学ツアー',
      '全商品対象の感謝セール',
    ],
    answerIndex: 0,
    explanation:
      '四個方案被逐一淘汰：演唱會因場地費加演出費將近超出預算一倍而作罷；感謝セール因每年都辦、缺乏五十週年的特別感被否決；工場見學因安全管理準備需半年、趕不上三個月後的典禮而放棄。最後兩人以費用低、又能觸及年輕客層為由，拍板 SNS 攝影投稿比賽（「それでいこう」）。「記念コンサート」是女の人一開始屬意的方案，聽到前半就作答容易誤選。',
    explanationEn:
      'The four proposals are eliminated one by one: the concert would nearly double the budget with hall and performer fees; the thank-you sale runs every year and lacks fiftieth-anniversary specialness; the factory tour needs half a year of safety preparation and cannot make the ceremony three months away. The two finally settle on the SNS photo contest (「それでいこう」) for its low cost and its reach among younger customers. 「記念コンサート」 is what the woman favored at first, so answering from only the first half leads you astray.',
  },
  {
    id: 'n1-listening-togo-004',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '携帯電話の店で、店員の説明を聞いて、夫婦が話しています。' },
      { speaker: '女', text: '現在、料金プランは四つございます。まず「使い放題プラン」は、データ量を一切気にせずお使いいただけて、月額七千円です。' },
      { speaker: '女', text: '「段階制プラン」は、お使いになった分だけお支払いいただく仕組みで、あまり使わない月は千円台に収まります。' },
      { speaker: '女', text: '「家族割プラン」は、ご家族三回線以上のご契約で、お一人あたりの月額が四割引きになります。' },
      { speaker: '女', text: 'それから「シニアプラン」は、六十五歳以上のお客様限定で、国内通話が無料になる大変お得なプランです。' },
      { speaker: '男', text: '家族割が一番安くなりそうだけど、うちは二人だから対象外か。' },
      { speaker: '女', text: '残念ながらね。私はほとんど電話とメールしか使わないから、使った分だけのにするわ。あなたもそれでいいんじゃない？' },
      { speaker: '男', text: 'いや、僕は通勤中ずっと動画を見てるからなあ。使った分だけだと、かえって高くつきかねないよ。' },
      { speaker: '女', text: 'じゃあ、多少高くても定額で安心なほうね。シニアのは、あと二十年は先の話だし。' },
      { speaker: '男', text: 'そういうこと。じゃあ、僕はそれで申し込むよ。' },
    ],
    question: '男の人はどの料金プランにしますか。',
    options: [
      '使い放題プラン',
      '段階制プラン',
      '家族割プラン',
      'シニアプラン',
    ],
    answerIndex: 0,
    explanation:
      '男の人通勤時一直看影片、流量大，若選按用量計費的段階制反而「高くつきかねない」（恐怕更貴），因此選擇定額安心的吃到飽方案。「段階制プラン」是太太自己要辦的方案，屬於「對方選項」混淆；「家族割」需三條門號以上，他家只有夫妻兩人不符資格；「シニアプラン」限六十五歲以上，對話中說「還要二十年後」，也不適用。',
    explanationEn:
      'The man watches videos throughout his commute, so heavy data on the pay-as-you-go tiered plan could 「高くつきかねない」 (end up costing more), and he chooses the worry-free flat-rate unlimited plan. 「段階制プラン」 is what the wife takes for herself, a partner-choice decoy; 「家族割」 requires at least three lines while their household has only the two of them; and 「シニアプラン」 is for customers 65 and over — as the dialogue says, still twenty years away for him.',
  },
  {
    id: 'n1-listening-togo-005',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'スポーツクラブで、係の人の説明を聞いて、夫婦が話しています。' },
      { speaker: '男', text: '当クラブでは、今月から四つのプログラムを始めます。まず「早朝ヨガ」は毎朝六時半からで、一日を気持ちよく始めたい方におすすめです。' },
      { speaker: '男', text: '「水中ウォーキング」は、プールの中を歩く運動で、膝や腰への負担が少ないのが特長です。' },
      { speaker: '男', text: '「ダンスエクササイズ」は、音楽に合わせて全身を大きく動かす、汗をたっぷりかけるプログラムです。' },
      { speaker: '男', text: 'それから「筋力トレーニング講座」では、マシンの正しい使い方を、トレーナーが一人一人に指導いたします。' },
      { speaker: '女', text: 'ダンス、楽しそうだけど、あれだけ激しく動くと腰にこたえそうね。' },
      { speaker: '男', text: 'お医者さんにも、腰に負担をかけるなって言われてただろう。ヨガはどう？体が柔らかくなるらしいよ。' },
      { speaker: '女', text: '六時半に着くには五時起きよ。続けられる気がしないわ。やっぱり、水の中なら腰にも優しいっていうし、私はそれにする。' },
      { speaker: '男', text: '僕はせっかくだから、マシンの使い方を一から教わるよ。自己流でやって、前に肩を痛めたからね。' },
      { speaker: '女', text: 'それがいいわ。じゃあ、受付でそれぞれ申し込みましょう。' },
    ],
    question: '女の人はどのプログラムに申し込みますか。',
    options: [
      '水中ウォーキング',
      '早朝ヨガ',
      'ダンスエクササイズ',
      '筋力トレーニング講座',
    ],
    answerIndex: 0,
    explanation:
      '女の人有腰傷，醫生囑咐不要造成腰部負擔，因此動作激烈的ダンスエクササイズ先被排除；早朝ヨガ雖被丈夫推薦，但六點半開課得五點起床，她自認無法持續；最後選擇「水の中なら腰にも優しい」的水中ウォーキング。「筋力トレーニング講座」是男の人因曾自己亂練弄傷肩膀而選的，屬於「男方選項」混淆。',
    explanationEn:
      'The woman has a bad back and doctor’s orders not to strain it, so the vigorous dance exercise class is ruled out first; her husband suggests early-morning yoga, but a 6:30 start means getting up at five, which she doubts she could keep up. She settles on water walking because 「水の中なら腰にも優しい」 (the water is gentle on her back). 「筋力トレーニング講座」 is the husband’s pick — he once hurt his shoulder training self-taught — making it a his-choice decoy.',
  },
  {
    id: 'n1-listening-togo-006',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '不動産屋で、店の人の説明を聞いて、夫婦が話しています。' },
      { speaker: '女', text: 'ご希望に近い物件は四件ございます。一件目は駅前のマンションで、通勤には最適ですが、大通りに面しておりまして、家賃もご予算を二万円ほど超えます。' },
      { speaker: '女', text: '二件目は郊外の一戸建てで、庭付きの広いお住まいですが、駅まではバスで三十分かかります。' },
      { speaker: '女', text: '三件目は商店街のそばのアパートで、家賃はお手頃ですが、築四十年で、日当たりはあまりよくありません。' },
      { speaker: '女', text: '四件目は公園沿いのマンションです。駅まで徒歩十五分と少し歩きますが、環境が静かで、家賃もご予算の範囲内です。' },
      { speaker: '男', text: '駅前はやっぱり便利だなあ。多少高くても、通勤時間には代えられないよ。' },
      { speaker: '女', text: 'でも予算オーバーの上に、大通りの騒音でしょう。在宅で仕事をする私には、静かさだけは譲れないわ。' },
      { speaker: '男', text: '一戸建ては広くて魅力的だけど、バスで三十分は、朝の渋滞を考えると現実的じゃないか。' },
      { speaker: '女', text: '商店街のは安いけど、あの日当たりじゃ洗濯物も乾かないわよ。その点、公園沿いなら静かだし、十五分ならあなたも歩けるでしょう？' },
      { speaker: '男', text: 'まあ、運動だと思えばね。よし、そこに決めよう。' },
    ],
    question: '二人はどの物件に決めましたか。',
    options: [
      '公園沿いのマンション',
      '駅前のマンション',
      '郊外の一戸建て',
      '商店街のそばのアパート',
    ],
    answerIndex: 0,
    explanation:
      '駅前マンション超出預算兩萬圓且面向大馬路吵雜，被在家工作、堅持要安靜的妻子否決；郊外一戸建て因公車三十分鐘加上早晨塞車被認為不切實際；商店街旁的公寓屋齡四十年、日照差到「洗濯物も乾かない」。公園沿いのマンション安靜、租金在預算內、走路十五分鐘可當運動，最後丈夫說「そこに決めよう」拍板。「駅前のマンション」是丈夫最初屬意的，容易誤選。',
    explanationEn:
      'The station-front condo runs 20,000 yen over budget and faces a noisy main road, so the wife, who works from home and will not compromise on quiet, vetoes it; the suburban house is deemed unrealistic with a 30-minute bus ride plus morning congestion; the apartment by the shopping street is forty years old with sunlight so poor 「洗濯物も乾かない」 (the laundry would never dry). The parkside condo is quiet, within budget, and the 15-minute walk can count as exercise, so the husband closes with 「そこに決めよう」. 「駅前のマンション」 is what he initially favored, an easy wrong pick.',
  },
  {
    id: 'n1-listening-togo-007',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '温泉旅館で、フロントの人の説明を聞いて、夫婦が話しています。' },
      { speaker: '女', text: '当館の宿泊プランは四つございます。まず「露天風呂付き客室プラン」は、お部屋で源泉かけ流しの湯を心ゆくまでお楽しみいただけますが、料金は通常の倍近くになります。' },
      { speaker: '女', text: '「湯めぐりプラン」は、当館に加えて姉妹館二軒の湯にも入れるプランで、館の間は送迎バスでの移動となります。' },
      { speaker: '女', text: '「特選会席プラン」は、夕食を料理長おまかせの特選会席にグレードアップするプランで、当館で一番人気でございます。' },
      { speaker: '女', text: 'それから「素泊まりプラン」は、お食事は朝食のみで、夕食は温泉街で自由に召し上がりたい方向けの、一番お手頃なプランです。' },
      { speaker: '男', text: '部屋に露天風呂か。誰にも気兼ねなく、好きなだけ入れるなんて憧れだなあ。' },
      { speaker: '女', text: '倍近くもするのよ。結婚記念日でもあるまいし、今回そこまで奮発することはないでしょう。' },
      { speaker: '男', text: 'じゃあ湯めぐりは？三つの湯に入れるなんて、温泉好きには願ってもない話だよ。' },
      { speaker: '女', text: 'バスの移動が挟まるんじゃ、かえって慌ただしいわ。せっかくの骨休めなんだから、宿でゆっくり、おいしいものをいただくのが一番よ。夜に外へ食べに出るのも億劫だし。' },
      { speaker: '男', text: 'それもそうだな。よし、一番人気だというのにしよう。' },
    ],
    question: '二人はどのプランを予約しますか。',
    options: [
      '特選会席プラン',
      '露天風呂付き客室プラン',
      '湯めぐりプラン',
      '素泊まりプラン',
    ],
    answerIndex: 0,
    explanation:
      '丈夫先後屬意「露天風呂付き客室」與「湯めぐり」，但前者價格近乎兩倍、被妻子以「結婚記念日でもあるまいし」否決，後者因需搭接駁車往返反而匆忙也被打消；妻子主張在旅館裡悠閒享用美食，丈夫附和「一番人気だというのにしよう」，即館方介紹時說「當館第一人氣」的特選会席プラン。「露天風呂付き客室プラン」是丈夫最初的憧憬，只聽前半容易誤選；「素泊まり」因晚上外出用餐麻煩而被排除。',
    explanationEn:
      'The husband is tempted first by the open-air-bath room and then by the bath-hopping plan, but the former costs nearly double and the wife dismisses it with 「結婚記念日でもあるまいし」 (it’s not as if it’s our anniversary), and the latter is dropped because the shuttle-bus transfers would make things hectic. She argues for relaxing at the inn over a fine meal, and he agrees with 「一番人気だというのにしよう」 — the special kaiseki plan the front desk called the inn’s most popular. 「露天風呂付き客室プラン」 is the husband’s initial dream and traps anyone who stops listening halfway; 「素泊まり」 is ruled out because going out for dinner feels like a chore.',
  },
  {
    id: 'n1-listening-togo-008',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で、男の人と女の人が講演会の会場について話しています。' },
      { speaker: '男', text: '会場の候補は四つに絞ったよ。市民ホール、ホテルの宴会場、大学の講堂、それから駅前の貸し会議室だ。' },
      { speaker: '女', text: '市民ホールは五百人入りますし、音響も申し分ないんですが、利用は抽選制で、取れるかどうかは来月にならないと分からないそうです。' },
      { speaker: '男', text: '招待状の発送は再来週だろう。会場が未定のままじゃ、印刷にかかれないよ。' },
      { speaker: '女', text: 'ですよね。ホテルの宴会場は駅直結で立地は文句なしですが、見積もりを取ったら予算の一・五倍でした。' },
      { speaker: '男', text: '講演会一回にそこまでかけるわけにはいかないな。大学の講堂はどうなんだ。' },
      { speaker: '女', text: '三百人収容で、使用料も手頃です。ただ、駅からバスで二十分かかるのがネックですね。' },
      { speaker: '男', text: 'うーん。でも今回の参加者は半分以上があの大学の卒業生だろう。会場までの道は勝手知ったるものだし、懐かしさで足を運んでくれるかもしれないよ。' },
      { speaker: '女', text: '確かに、そう考えれば交通の不便は補って余りありますね。貸し会議室は百人しか入りませんから、そもそも論外ですし。' },
      { speaker: '男', text: 'じゃあ、そこに申し込んでおいてくれ。' },
    ],
    question: '二人はどの会場にすることにしましたか。',
    options: [
      '大学の講堂',
      '市民ホール',
      'ホテルの宴会場',
      '駅前の貸し会議室',
    ],
    answerIndex: 0,
    explanation:
      '四個場地逐一比較：市民ホール音響雖佳但採抽選制、下個月才知結果，趕不上再來週要寄的邀請函；ホテル宴会場交通絕佳卻要價預算的一點五倍；貸し会議室僅容百人、直接出局。大学の講堂雖然離車站要搭二十分鐘公車，但參加者過半是該校校友、路線熟門熟路，兩人認為足以彌補交通劣勢，最後男の人說「そこに申し込んでおいてくれ」拍板。「市民ホール」是條件看似最好的場地，只聽優點不聽時程限制就容易誤選。',
    explanationEn:
      'Comparing the four venues: the civic hall has fine acoustics but is allotted by lottery with results not known until next month, too late for invitations going out the week after next; the hotel banquet room has a perfect location but quotes 1.5 times the budget; the rental meeting room holds only a hundred people and is dismissed outright. The university auditorium requires a 20-minute bus ride from the station, but over half the attendees are alumni who know the way, which the two decide more than offsets the inconvenience, and the man closes with 「そこに申し込んでおいてくれ」. 「市民ホール」 looks best on paper, so hearing only its merits and not the scheduling constraint leads to the wrong answer.',
  },
  {
    id: 'n1-listening-togo-009',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で、人事の人の説明を聞いて、同僚の男の人と女の人が話しています。' },
      { speaker: '男', text: '今期の社員研修は四つあります。まず「プレゼンテーション研修」は、発表の組み立てと話し方を学ぶもので、平日夜間、全三回の講座です。' },
      { speaker: '男', text: '「データ分析研修」は、統計の基礎から表計算ソフトの実践まで扱います。毎回課題の提出がありますので、覚悟してお申し込みください。' },
      { speaker: '男', text: '「ビジネス英語研修」は、海外部門との会議を想定した実践講座で、初回にクラス分けのテストがあります。' },
      { speaker: '男', text: 'それから「ロジカルライティング研修」は、報告書や企画書の書き方を学ぶ、eラーニングの自習形式です。' },
      { speaker: '女', text: '来月の新製品発表、説明役は私だから、話し方を鍛えたかったんだけど、平日の夜三回は子どもの迎えと重なって、どうにも出られないのよね。' },
      { speaker: '男', text: 'eラーニングなら好きな時間にできるよ。書く力だって発表資料に生きるんじゃない？' },
      { speaker: '女', text: '書く前に、まず数字を根拠に語れるようになりたいの。課題が多いのは大変そうだけど、それだけ力がつくってことでしょう。私はそれにするわ。あなたは？' },
      { speaker: '男', text: '僕は秋から海外案件を任されるから、英語のにするよ。テストで下のクラスに回されそうで怖いけどね。' },
      { speaker: '女', text: '実力が分かっていいじゃない。じゃあ、お互い頑張りましょう。' },
    ],
    question: '女の人はどの研修を受けますか。',
    options: [
      'データ分析研修',
      'プレゼンテーション研修',
      'ビジネス英語研修',
      'ロジカルライティング研修',
    ],
    answerIndex: 0,
    explanation:
      '女の人原想為下個月的新產品發表鍛鍊「話し方」而報プレゼンテーション研修，卻因平日夜間三回與接小孩時間衝突而放棄；同事推薦可自由安排時間的ロジカルライティング，她以「想先學會用數字說話」婉拒，最後選擇雖然作業多但扎實的データ分析研修（「私はそれにするわ」）。「ビジネス英語研修」是男の人為秋天的海外案子選的，屬於「對方選項」混淆；「プレゼンテーション研修」是她被迫放棄的第一志願，也容易誤選。',
    explanationEn:
      'The woman originally wanted the presentation seminar to polish her speaking for next month’s product launch, but its three weekday-evening sessions clash with picking up her child; her colleague suggests the anytime e-learning logical-writing course, which she declines because she first wants to argue from numbers. She commits to the data analysis seminar — heavy on assignments but genuinely strengthening — with 「私はそれにするわ」. 「ビジネス英語研修」 is what the man picks for his autumn overseas assignments, a partner-choice decoy; 「プレゼンテーション研修」 is the first choice she had to abandon, another tempting wrong answer.',
  },
  {
    id: 'n1-listening-togo-010',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '保険会社で、担当者の説明を聞いて、夫婦が話しています。' },
      { speaker: '女', text: '本日ご案内するのは四つの保険です。まず「医療保険」は、入院と手術を一生涯保障する終身型で、掛け金は年齢が上がっても変わりません。' },
      { speaker: '女', text: '「がん保険」は、がんと診断された時点でまとまった一時金をお支払いするもので、保険料は割安に抑えられております。' },
      { speaker: '女', text: '「収入保障保険」は、病気やけがで働けなくなった場合に、毎月お給料のように保険金が支払われる、働き盛りの方向けの保険です。' },
      { speaker: '女', text: 'それから「積立型の養老保険」は、保障と貯蓄を兼ねており、満期にはお払い込みいただいた額を上回る満期金が受け取れますが、月々のご負担は一番重くなります。' },
      { speaker: '男', text: '積立型か。貯金が苦手な僕には、強制的に貯まる仕組みはありがたいけどなあ。' },
      { speaker: '女', text: '月々の負担が一番重いのよ。住宅ローンを抱えている今それを組んだら、家計が回らなくなりかねないわ。' },
      { speaker: '男', text: 'それもそうか。君はどうするんだい。' },
      { speaker: '女', text: 'うちは家系にがんが多いから、備えるならまずそこ。診断されたらすぐ一時金が出るのは心強いもの。あなたは自営業で、倒れたら収入が途絶えるでしょう。毎月お給料代わりに出るのが合ってるんじゃない？' },
      { speaker: '男', text: '確かに、僕に必要なのはそれだな。医療保険は今の共済と保障が重なるから見送るとして、それぞれ申し込もう。' },
    ],
    question: '男の人はどの保険に入りますか。',
    options: [
      '収入保障保険',
      'がん保険',
      '積立型の養老保険',
      '医療保険',
    ],
    answerIndex: 0,
    explanation:
      '男の人最初對能強制儲蓄的積立型養老保険心動，但被妻子以「背著房貸、月付最重恐怕讓家計轉不過來」勸退；妻子點出他是自營業者、一旦倒下收入就會中斷，最適合每月像薪水一樣給付的收入保障保険，他也認同「僕に必要なのはそれだな」。「がん保険」是妻子因家族多癌症病史而自己要保的，屬於「對方選項」混淆；「医療保険」因與現有共済保障重疊而被排除；「積立型」是他一開始屬意的，只聽前半容易誤選。',
    explanationEn:
      'The man is initially drawn to the savings-type endowment plan that would force him to save, but his wife talks him out of it: with a mortgage, the heaviest monthly premium could sink the household budget. She points out that as a self-employed worker his income stops the moment he falls ill, so the income-protection insurance that pays out monthly like a salary suits him best, and he agrees with 「僕に必要なのはそれだな」. 「がん保険」 is what the wife takes for herself given her family’s cancer history, a partner-choice decoy; 「医療保険」 is dropped as overlapping his existing kyosai coverage; and the endowment plan is the early temptation that misleads half-listeners.',
  },
  {
    id: 'n1-listening-togo-011',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で、ケータリング業者の説明を聞いて、男の人と女の人が創立記念パーティーの料理について話しています。' },
      { speaker: '男', text: 'コースは四つご用意しております。まず「立食ビュッフェコース」は、料理の種類が最も豊富で、温かい料理は会場で仕上げますが、簡単な調理スペースをお借りする必要がございます。' },
      { speaker: '男', text: '「和食弁当コース」は、お一人様一箱ずつお配りするもので、衛生的で進行の妨げにもなりませんが、華やかさにはやや欠けます。' },
      { speaker: '男', text: '「オードブル盛り合わせコース」は、大皿を並べるだけの一番お手頃なコースで、温かい料理は含まれません。' },
      { speaker: '男', text: 'それから「シェフの実演コース」は、お客様の目の前でローストビーフを切り分ける演出付きで盛り上がりますが、お値段は五割増しになります。' },
      { speaker: '女', text: '実演、絶対盛り上がりますよ。周年の目玉にうってつけじゃないですか。' },
      { speaker: '男', text: '五割増しは無理だよ。今年は経費削減のお達しが出ているんだから。じゃあ弁当は？配るだけで楽だろう。' },
      { speaker: '女', text: '楽ですけど、立って歓談してもらうパーティーなのに、箱のお弁当じゃ味気なくありません？かといって大皿だけだと、冷めた料理ばかりで寂しいですし。' },
      { speaker: '男', text: 'そうなると、調理スペースの有無が鍵か。確か会場の控室が使えると聞いたな。' },
      { speaker: '女', text: 'ええ、使えるそうです。種類も一番多いですし、それで見積もりをお願いしましょう。' },
    ],
    question: '二人はどのコースを頼むことにしましたか。',
    options: [
      '立食ビュッフェコース',
      'シェフの実演コース',
      '和食弁当コース',
      'オードブル盛り合わせコース',
    ],
    answerIndex: 0,
    explanation:
      '女の人最想要有現場秀的シェフの実演コース，但價格加五成、在公司下達節約經費指令的今年不可行；和食弁当被她以「站著歡談的派對配盒裝便當太乏味」否決；オードブル只有冷盤也嫌冷清。剩下的立食ビュッフェ需要簡易調理空間，確認會場休息室可借用後，兩人以「菜色種類最多」為由請業者估價定案。「シェフの実演コース」是女の人一開始力推的方案，只聽前半就作答容易誤選。',
    explanationEn:
      'The woman most wants the chef’s live-carving course, but its 50-percent surcharge is impossible in a year when cost-cutting orders have come down; she rejects the boxed washoku lunches as dreary for a standing, mingling party, and the hors d’oeuvre platters alone would mean nothing but cold dishes. That leaves the standing buffet, which needs a simple cooking space — once they confirm the venue’s anteroom can be borrowed, they request a quote on it for having the widest variety. 「シェフの実演コース」 is what the woman pushed at the start, so answering from the first half alone leads you astray.',
  },
  {
    id: 'n1-listening-togo-012',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'シェアオフィスの見学で、スタッフの説明を聞いて、フリーランスの男の人と女の人が話しています。' },
      { speaker: '女', text: '料金プランは四つございます。まず「固定席プラン」は、専用のデスクに私物や機材を置いたままにできるプランで、月額二万五千円です。' },
      { speaker: '女', text: '「自由席プラン」は、空いている席をその都度お使いいただくプランで、月額一万五千円ですが、混み合う時間帯は席が見つからないこともございます。' },
      { speaker: '女', text: '「個室プラン」は、鍵付きの完全個室で、オンライン会議も気兼ねなく行えます。月額四万円です。' },
      { speaker: '女', text: 'それから「ナイト・週末プラン」は、平日の夜と土日のみご利用いただけるプランで、月額八千円です。' },
      { speaker: '男', text: '個室は魅力だけど、四万はさすがにきついな。' },
      { speaker: '女', text: 'あなた、撮影機材を毎回担いで来るのは大変でしょう。置きっぱなしにできる席のほうがいいんじゃない？' },
      { speaker: '男', text: 'そうだな。自由席だと、重い機材を抱えて席を探し回る羽目になりかねない。僕はそれにするよ。君こそ、昼間は取材で飛び回ってるんだから、夜だけの安いので足りるんじゃないか？' },
      { speaker: '女', text: 'そう思ったんだけど、原稿を書くのはたいてい平日の午後なのよ。昼に使えないんじゃ話にならないわ。かといってあなたほど毎日は通わないし、荷物もノートパソコン一台だから、安いほうの席で十分。' },
      { speaker: '男', text: '混んでて座れないこともあるらしいよ。まあ、君なら近くのカフェに逃げ込めばいいか。じゃあ、それぞれ契約しよう。' },
    ],
    question: '女の人はどのプランで契約しますか。',
    options: [
      '自由席プラン',
      '固定席プラン',
      'ナイト・週末プラン',
      '個室プラン',
    ],
    answerIndex: 0,
    explanation:
      '男の人建議女の人選最便宜的ナイト・週末プラン，但她寫稿多在平日下午，白天不能用就毫無意義；她又表明不像對方那樣每天報到、行李只有一台筆電，不需要固定席，因此選擇較便宜的自由席プラン，尖峰沒位子時去咖啡店即可。「固定席プラン」是男の人因攝影器材笨重、想放著不動而選的，屬於「對方選項」混淆；「個室プラン」月費四萬一開始就被嫌太貴而出局。',
    explanationEn:
      'The man suggests the woman take the cheapest night-and-weekend plan, but she writes her drafts mostly on weekday afternoons, so a plan unusable in daytime is pointless; she also notes she will not come in daily like him and carries only a laptop, so she needs no fixed desk and picks the cheaper free-address plan, retreating to a nearby cafe when it is crowded at peak times. 「固定席プラン」 is the man’s choice, made so he can leave his heavy camera gear in place — a partner-choice decoy; 「個室プラン」 was knocked out at the start as too expensive at 40,000 yen a month.',
  },
  {
    id: 'n1-listening-togo-013',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '引っ越しの相談センターで、係の人の説明を聞いて、夫婦が話しています。' },
      { speaker: '男', text: '見積もりが四社から届いております。まず「スピード便」は一番お安いんですが、引っ越しの日にちは業者側が指定する仕組みで、こちらからは選べません。' },
      { speaker: '男', text: '「まごころ引越センター」は、荷造りから荷ほどきまで全部おまかせできるプランで、その分お値段は他社の五割増しになります。' },
      { speaker: '男', text: '「みなと運送」は土日も同じ料金で、作業が丁寧と評判ですが、ピアノなどの重量物の運搬は取り扱っておりません。' },
      { speaker: '男', text: 'それから「あおぞら引越便」は、平日限定ならスピード便に近いお値段で、時間の指定もできます。' },
      { speaker: '女', text: '全部おまかせできるのは夢みたいだけど、五割増しはねえ。箱詰めぐらい、自分たちでやれば済む話だし。' },
      { speaker: '男', text: '一番安いのも捨てがたいけど、日にちを選べないんじゃ、鍵の引き渡しの日と合わないかもしれないよ。' },
      { speaker: '女', text: 'それに、うちにはピアノがあるでしょう。丁寧だっていう会社は、そもそも運んでもらえないわ。' },
      { speaker: '男', text: 'そうか。じゃあ、僕が平日に休みを取れば、安くて時間も選べるところに頼めるな。' },
      { speaker: '女', text: 'ええ、そうしましょう。' },
    ],
    question: '二人はどの業者に頼むことにしましたか。',
    options: [
      'あおぞら引越便',
      'まごころ引越センター',
      'スピード便',
      'みなと運送',
    ],
    answerIndex: 0,
    explanation:
      '四家業者逐一比較：最便宜的「スピード便」因搬家日期由業者指定、可能對不上交屋拿鑰匙的日子而放棄；「まごころ引越センター」從打包到拆箱全包雖令人嚮往，但貴五成，妻子認為裝箱自己來就好；「みなと運送」評價雖好卻不承接鋼琴等重物，而他們家有鋼琴。最後丈夫決定平日請假，選便宜又能指定時間的「あおぞら引越便」。「まごころ引越センター」是被稱讚卻因價格出局的干擾項。',
    explanationEn:
      'Comparing the four movers: the cheapest 「スピード便」 lets the company pick the date, which may not match the day they get the keys; the full-service 「まごころ引越センター」 sounds dreamy but costs fifty percent more, and the wife says they can pack the boxes themselves; 「みなと運送」 has a fine reputation but does not handle heavy items like pianos, and they own one. The husband decides to take a weekday off, so they go with 「あおぞら引越便」, which is cheap and lets them choose the time. 「まごころ引越センター」 is the praised-but-priced-out decoy.',
  },
  {
    id: 'n1-listening-togo-014',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '子ども向けの教室の説明会で、係の人の説明を聞いて、夫婦が話しています。' },
      { speaker: '女', text: '当教室には四つのコースがございます。まず水泳コースは、基礎体力づくりに一番人気で、ただいま入会は半年待ちとなっております。' },
      { speaker: '女', text: '英会話コースは、外国人の先生と遊びながら学ぶコースですが、月謝は四つの中で一番高くなります。' },
      { speaker: '女', text: '絵画コースは、毎回好きな材料で自由に作品を作る、のびのびとしたコースです。' },
      { speaker: '女', text: 'それから体操コースは、マット運動や跳び箱で全身を動かすコースで、平日の夕方に週二回ございます。' },
      { speaker: '男', text: '水泳、いいと思ったのになあ。体力をつけさせたくて来たのに、半年も待つんじゃ意味がないよ。' },
      { speaker: '女', text: 'そうねえ。英会話はどう？小さいうちから耳を慣らすといいって言うし。' },
      { speaker: '男', text: 'うちの子はまだ人見知りが激しいだろう。それに、一番高い月謝を払い続けるのは厳しいよ。絵なら家でも毎日描いてるしなあ。' },
      { speaker: '女', text: 'じゃあ、体を動かすほうで、待たずに始められるのにしましょう。夕方なら私が送っていけるわ。' },
      { speaker: '男', text: 'うん、それがいい。' },
    ],
    question: '二人は子どもをどのコースに通わせることにしましたか。',
    options: [
      '体操コース',
      '水泳コース',
      '英会話コース',
      '絵画コース',
    ],
    answerIndex: 0,
    explanation:
      '夫婦來的目的是培養孩子的基礎體力，第一志願「水泳コース」雖最有人氣，卻要排隊等半年，被父親以「等半年就失去意義」放棄；「英会話コース」因孩子怕生嚴重、月費又是四種中最貴而否決；「絵画コース」則是孩子在家每天都在畫，不必特地去上。最後選擇不用等、又能活動全身的「体操コース」，傍晚上課媽媽也能接送。「水泳コース」是被稱讚為第一人氣卻因候補期太長被排除的干擾項。',
    explanationEn:
      'The couple came to build their child’s basic fitness. Their first choice, 「水泳コース」, is the most popular but has a six-month waiting list, so the father drops it, saying waiting that long defeats the purpose; 「英会話コース」 is rejected because the child is very shy and its monthly fee is the highest of the four; 「絵画コース」 is something the child already does at home every day. They settle on 「体操コース」, which starts without a wait, works the whole body, and meets in the evening when the mother can drive the child there. 「水泳コース」 is the praised most-popular option excluded by the long wait.',
  },
  {
    id: 'n1-listening-togo-015',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で、幹事の説明を聞いて、同僚の男の人と女の人が社員旅行の行き先について話しています。' },
      { speaker: '女', text: '社員旅行の行き先の候補は四つです。まず南の島は、アンケートで一番人気でしたが、飛行機代だけで予算を大きく超えてしまいます。' },
      { speaker: '女', text: '温泉地は、旅館でゆっくりできる定番のコースで、費用も予算内に収まります。' },
      { speaker: '女', text: '高原のリゾートは、バーベキューやハイキングが楽しめて、貸し切りバスで行ける距離です。' },
      { speaker: '女', text: 'それから城下町を巡るコースは、名物料理の食べ歩きが目玉ですが、九月はまだ暑さが厳しいそうです。金曜までに投票をお願いします。' },
      { speaker: '男', text: '南の島、行きたかったなあ。まあ、あれだけ予算を超えるんじゃ、幹事も困るだろうけど。' },
      { speaker: '女', text: '温泉は去年行ったばかりじゃないですか。二年続けて同じようなのも芸がないですよ。' },
      { speaker: '男', text: '城下町の食べ歩きもうまそうだけど、あの暑さの中を一日歩き回るのは、ちょっと考えものだな。' },
      { speaker: '女', text: 'その点、涼しい高原でバーベキューなら体も楽ですし、みんなでわいわいできますよ。' },
      { speaker: '男', text: 'そうだね。じゃあ、二人ともそれに入れよう。' },
    ],
    question: '二人はどの行き先に投票することにしましたか。',
    options: [
      '高原のリゾート',
      '南の島',
      '温泉地',
      '城下町を巡るコース',
    ],
    answerIndex: 0,
    explanation:
      '問卷最高票的「南の島」光是機票就大幅超出預算，男の人雖想去也只能作罷；「温泉地」去年才去過，女の人認為連兩年去類似地點太沒新意；「城下町を巡るコース」的食べ歩き雖吸引人，但九月暑氣仍烈、要走一整天令人卻步。最後兩人以氣候涼爽、能烤肉同樂、包車就到為由，決定都投給「高原のリゾート」。「南の島」是人氣最高卻因預算被排除的干擾項，只聽前半容易誤選。',
    explanationEn:
      '「南の島」 topped the survey, but airfare alone blows the budget, so the man reluctantly lets it go; 「温泉地」 was last year’s destination, and the woman finds two similar trips in a row uninspired; the food walk of 「城下町を巡るコース」 is tempting, but walking all day in September’s lingering heat is off-putting. The two decide to both vote for 「高原のリゾート」 — cool, great for a group barbecue, and reachable by chartered bus. 「南の島」 is the most popular option knocked out by budget, an easy wrong pick if you only hear the first half.',
  },
  {
    id: 'n1-listening-togo-016',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '家電量販店で、店員の説明を聞いて、夫婦が話しています。' },
      { speaker: '男', text: 'ご用途でしたら、候補は四つですね。まずこちらの薄型モバイルは、重さが一キロを切っていて持ち運びは楽ですが、画面が小さめです。' },
      { speaker: '男', text: 'こちらの高性能タイプは、動画の編集も楽々こなせる一番の売れ筋です。ただ、お値段は他の倍近くいたします。' },
      { speaker: '男', text: 'タブレットにもなるこちらは、画面を外して使える面白い一台ですが、保存できる容量が少なめです。' },
      { speaker: '男', text: 'それからこの標準タイプは、画面が大きくて性能も十分、ちょうど今週はセールで二割引きになっております。' },
      { speaker: '女', text: '倍近くするのはやっぱり無理ね。性能は申し分ないんだけど。' },
      { speaker: '男', text: '君は家で写真を整理する仕事だろう。ほとんど持ち歩かないなら、軽さにお金を払うのはもったいないよ。' },
      { speaker: '女', text: 'そうね。タブレットになるのは面白いけど、写真をため込むには容量が心もとないわ。' },
      { speaker: '男', text: 'となると、画面が大きくて、今なら安く買えるのが一番じゃないか。' },
      { speaker: '女', text: 'ええ、それに決めるわ。' },
    ],
    question: '女の人はどのパソコンを買いますか。',
    options: [
      '標準タイプのパソコン',
      '高性能タイプのパソコン',
      '薄型モバイルのパソコン',
      'タブレットにもなるパソコン',
    ],
    answerIndex: 0,
    explanation:
      '女の人的用途是在家整理照片的工作。「高性能タイプ」雖被她稱讚「性能は申し分ない」，但價格近乎其他機種的兩倍，第一個被排除；「薄型モバイル」的賣點是輕，但她幾乎不帶出門，丈夫認為為了輕量多花錢很浪費；「タブレットにもなる」機型雖有趣，容量卻不夠存放大量照片。最後選擇螢幕大、效能足夠、本週又打八折的「標準タイプ」。「高性能タイプ」是被稱讚卻因價格出局的干擾項。',
    explanationEn:
      'The woman works from home organizing photos. She praises 「高性能タイプ」 with 「性能は申し分ない」, but at nearly double the price it is the first to go; the selling point of 「薄型モバイル」 is its weight, yet she rarely carries a laptop out, so the husband calls paying extra for lightness a waste; the tablet-convertible model is fun but its storage is too small for hoarding photos. She picks 「標準タイプ」 with its large screen, sufficient performance, and a twenty percent discount this week. 「高性能タイプ」 is the praised-but-priced-out decoy.',
  },
  {
    id: 'n1-listening-togo-017',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '結婚式場の相談会で、プランナーの説明を聞いて、カップルが話しています。' },
      { speaker: '女', text: 'ご希望に合いそうな会場は四つございます。まず駅前のホテルは、二百名様まで入る格式ある宴会場ですが、その分ご費用は一番かかります。' },
      { speaker: '女', text: '専門式場のチャペルは、当社で一番人気の会場で、あいにく来年の秋まで予約で埋まっております。' },
      { speaker: '女', text: '庭園を望むガーデン会場は、緑の中での挙式が魅力ですが、雨の場合は室内の小さなお部屋に変更となります。' },
      { speaker: '女', text: 'それから老舗の料亭は、五十名様までの会場で、お料理の評判は当社の扱う中でも随一でございます。' },
      { speaker: '男', text: 'チャペル、写真で見て一番よかったんだけどな。来年の秋まで待つのは、さすがに長すぎるよ。' },
      { speaker: '女', text: 'そうね。ホテルは立派だけど、うちは親族中心の四十人でしょう。あの広さじゃ、かえって寂しく見えるわ。' },
      { speaker: '男', text: '庭園は君の好みだと思ったけど、式は六月だろう。雨で狭い部屋に変更なんてことになったら、目も当てられないよ。' },
      { speaker: '女', text: 'ええ。それなら、人数もぴったりで、お料理でおもてなしできるところが一番よ。おばあちゃんも喜ぶわ。' },
      { speaker: '男', text: 'よし、そこで見積もりをお願いしよう。' },
    ],
    question: '二人はどの会場にすることにしましたか。',
    options: [
      '老舗の料亭',
      '専門式場のチャペル',
      '駅前のホテルの宴会場',
      '庭園のガーデン会場',
    ],
    answerIndex: 0,
    explanation:
      '男の人看照片最中意的「専門式場のチャペル」預約已排到明年秋天，等太久而作罷；「駅前のホテル」氣派但可容兩百人，對以親族為主的四十人婚宴反而顯得冷清，費用也最高；「ガーデン会場」雖合女の人喜好，但婚期在六月，一下雨就得改到狹小的室內，風險太大。最後選擇人數剛好、料理口碑第一、還能讓奶奶開心的「老舗の料亭」。「専門式場のチャペル」是最被中意卻因檔期被排除的干擾項。',
    explanationEn:
      '「専門式場のチャペル」, which the groom liked best in the photos, is booked through next autumn — too long to wait; 「駅前のホテル」 is grand but holds two hundred guests, which would feel empty for their forty-guest, family-centered reception, and it costs the most; 「ガーデン会場」 suits the bride’s taste, but with a June wedding a rainy-day switch to a cramped indoor room is too big a risk. They choose 「老舗の料亭」 — the right size, the best-reputed cuisine, and sure to delight grandma. 「専門式場のチャペル」 is the favorite ruled out by availability.',
  },
  {
    id: 'n1-listening-togo-018',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '市民センターで、受付の人の説明を聞いて、夫婦が話しています。' },
      { speaker: '男', text: '今期の語学クラスは四つございます。まず英会話の入門クラスは、毎回応募が多くて、今期も抽選になります。結果が出るのは開講の三日前です。' },
      { speaker: '男', text: '中国語のクラスは、今期は中級のみの開講で、初めての方はご受講いただけません。' },
      { speaker: '男', text: '韓国語の入門クラスは土曜の午前中で、まだ席に余裕がございます。' },
      { speaker: '男', text: 'それからスペイン語の入門クラスは、平日の夜七時からの開講です。' },
      { speaker: '女', text: '英会話をやり直したかったんだけど、抽選で、しかも結果が三日前じゃ、予定の立てようがないわね。' },
      { speaker: '男', text: '来年の春、友達とソウルに行くんだろう。だったら、旅行で使える言葉を今から始めたほうが実になるんじゃないか。' },
      { speaker: '女', text: 'それもそうね。中国語も気になってたけど、初心者は駄目だっていうし。土曜の午前なら確実に通えるわ。' },
      { speaker: '男', text: '僕は定年後の楽しみに、夜のスペイン語でも始めてみるかな。' },
      { speaker: '女', text: 'あら、いいじゃない。じゃあ、二人分申し込みましょう。' },
    ],
    question: '女の人はどのクラスに申し込みますか。',
    options: [
      '韓国語の入門クラス',
      '英会話の入門クラス',
      '中国語のクラス',
      'スペイン語の入門クラス',
    ],
    answerIndex: 0,
    explanation:
      '女の人原想重修的「英会話の入門クラス」要抽籤，且開課前三天才知結果，無法安排計畫而放棄；「中国語のクラス」本期只開中級班，初學者不能報；「スペイン語の入門クラス」是丈夫為退休後的樂趣選的平日夜間班，屬於「對方選項」混淆。丈夫提醒她明年春天要和朋友去首爾旅行，學旅途用得上的語言才實在，加上週六上午確定能出席，她因此報名「韓国語の入門クラス」。「英会話の入門クラス」是她被迫放棄的第一志願，容易誤選。',
    explanationEn:
      'The woman first hoped to restart 「英会話の入門クラス」, but it is decided by lottery with results only three days before classes begin, making planning impossible; 「中国語のクラス」 runs intermediate-only this term, so beginners cannot enroll; 「スペイン語の入門クラス」 is the weekday-evening class the husband picks as a post-retirement hobby, a partner-choice decoy. Reminded that she is traveling to Seoul with a friend next spring and that Saturday mornings are a slot she can reliably attend, she signs up for 「韓国語の入門クラス」. 「英会話の入門クラス」 is the first choice she had to abandon, an easy wrong pick.',
  },
]
