import type { JlptQuestion } from '../../types'

export const questions: JlptQuestion[] = [
  {
    id: 'n1-listening-pointo-001',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'ラジオ番組で、女のアナウンサーが男の小説家にインタビューしています。' },
      { speaker: '女', text: '新作の舞台に、あの北の港町を選ばれたのはなぜでしょう。幼い頃を過ごされた土地だと伺いましたが。' },
      { speaker: '男', text: 'ええ、確かに思い出深い土地ではあります。ただ、懐かしさだけで書けるほど小説は甘くないんですよ。' },
      { speaker: '女', text: 'では、取材のしやすさでしょうか。ご実家もまだあちらにあるとか。' },
      { speaker: '男', text: '拠点があるのは楽と言えば楽ですがね、決め手というほどのものではありません。実はあの町の方言なんです。あの独特の語り口を主人公の声にしたら、物語が勝手に動き出す気がしましてね。' },
      { speaker: '女', text: '方言が、ですか。' },
      { speaker: '男', text: 'ええ。標準語では出せない湿り気といいますか、あれはあの土地ならではのものです。' },
      { speaker: '女', text: 'なるほど、景色より先に言葉があったわけですね。' },
      { speaker: '男', text: 'そうなんです。あの声に惚れ込んで、舞台が決まったんですよ。' },
    ],
    question: '男の人がこの町を新作の舞台に選んだ一番の理由は何ですか。',
    options: [
      '町の方言を主人公の声にしたかったから',
      '幼い頃を過ごした思い出の土地だから',
      '実家があって取材がしやすいから',
      '港町の景色に惚れ込んだから',
    ],
    answerIndex: 0,
    explanation:
      '決め手是「実はあの町の方言なんです」，他想把當地獨特語感（あの土地ならでは）化為主角的聲音。童年回憶被「懐かしさだけで書けるほど甘くない」降級；取材方便被「決め手というほどのものではありません」明確排除；他最後說「景色より先に言葉があった」，愛上的是「聲音」不是景色。',
    explanationEn:
      'The deciding factor is stated as 「実はあの町の方言なんです」: he wanted to give the protagonist the town\'s distinctive way of speaking, a quality 「あの土地ならでは」. Childhood memories are downgraded by 「懐かしさだけで書けるほど甘くない」; convenience for research is explicitly ruled out with 「決め手というほどのものではありません」; and his closing line 「景色より先に言葉があった」 shows what he fell for was the voice, not the scenery.',
  },
  {
    id: 'n1-listening-pointo-002',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社の会議で、男の人と女の人が新製品について話しています。' },
      { speaker: '男', text: '例の調理家電ですが、発売を三か月延期せざるを得なくなりました。' },
      { speaker: '女', text: 'またですか。部品の調達が滞っていると聞きましたが。' },
      { speaker: '男', text: '調達は綱渡りではあるものの、どうにか目処は立っています。問題はそこじゃないんです。' },
      { speaker: '女', text: 'では、広告の準備ですか。代理店との調整が難航しているとか。' },
      { speaker: '男', text: '広告は多少ずれ込んでも発売自体には響きません。実は海外の安全規格の認証が下りるのが大幅に遅れていましてね。認証なしで出すわけにはいきませんから。' },
      { speaker: '女', text: 'それは動かしようがありませんね。' },
      { speaker: '男', text: 'ええ。審査機関の混み具合次第なので、こちらとしては待つほかないんです。' },
      { speaker: '女', text: '分かりました。販売店への説明はこちらで引き受けます。' },
    ],
    question: '新製品の発売が延期になった一番の理由は何ですか。',
    options: [
      '安全規格の認証が遅れているから',
      '部品の調達が滞っているから',
      '広告の準備が難航しているから',
      '販売店への説明が終わっていないから',
    ],
    answerIndex: 0,
    explanation:
      '男方明言「実は海外の安全規格の認証が下りるのが大幅に遅れていまして」，且「認証なしで出すわけにはいかない」，這是唯一無法迴避的延期主因。零件調度雖「綱渡り」但「目処は立っています」（有眉目了）被降級；廣告被「発売自体には響きません」排除；對經銷商的說明是延期後的善後工作，不是原因。',
    explanationEn:
      'The man states plainly 「実は海外の安全規格の認証が下りるのが大幅に遅れていまして」 and 「認証なしで出すわけにはいかない」 — the certification delay is the one unavoidable cause of the postponement. Parts procurement, though 「綱渡り」, is downgraded because 「目処は立っています」; advertising is dismissed with 「発売自体には響きません」; and briefing the retailers is cleanup work that follows the delay, not its cause.',
  },
  {
    id: 'n1-listening-pointo-003',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'テレビ番組で、女のアナウンサーが男の建築家に話を聞いています。' },
      { speaker: '女', text: '先生が古民家の再生を専門になさるようになったきっかけを伺えますか。新築より採算が取りにくい分野だと言われていますが。' },
      { speaker: '男', text: '儲からないのは事実ですが、そこは端から承知の上でしてね。' },
      { speaker: '女', text: '環境への配慮からでしょうか。廃材を出さない建築が注目されていますし。' },
      { speaker: '男', text: 'それも大義名分としてはありますよ。ただ、正直に申し上げると後付けの理由でして。祖父の家が取り壊されるのに立ち会ったとき、柱の一本一本に職人の技が残っているのを目の当たりにしましてね。あれを土に返すのは罪だと、心底思ったんです。' },
      { speaker: '女', text: 'ご自身の体験が原点なんですね。' },
      { speaker: '男', text: 'ええ。以来、壊す前に一度私に見せてくれと言い続けています。' },
      { speaker: '女', text: '今では全国から依頼が来るそうですね。' },
      { speaker: '男', text: 'ありがたいことに。ただ、手が回らないのが悩みの種です。' },
    ],
    question: '男の人が古民家の再生を専門にするようになった一番のきっかけは何ですか。',
    options: [
      '祖父の家の解体で職人の技を目の当たりにしたから',
      '廃材を出さない建築が注目されているから',
      '新築より採算が取りやすいから',
      '全国から依頼が殺到したから',
    ],
    answerIndex: 0,
    explanation:
      '原點是親眼看到祖父老家被拆時「柱の一本一本に職人の技が残っている」，覺得毀掉是罪過。環保理由被他自己說是「大義名分」「後付けの理由」（事後補上的理由），是被語氣降級的干擾項；採算方面他說「儲からないのは事実」，正好相反；全國委託是成名後的結果，不是契機。',
    explanationEn:
      'The origin was witnessing his grandfather\'s house being demolished and seeing that 「柱の一本一本に職人の技が残っている」 — he felt returning that to the earth would be a sin. The environmental rationale is discounted by his own words 「大義名分」 and 「後付けの理由」 (a justification added later); on profitability he says 「儲からないのは事実」, the very opposite of the distractor; and nationwide commissions are the result of his later fame, not the trigger.',
  },
  {
    id: 'n1-listening-pointo-004',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '大学の研究室で、女の学生と男の教授が話しています。' },
      { speaker: '女', text: '先生、来月の国際学会の基調講演、お断りになったと伺いましたが、本当ですか。' },
      { speaker: '男', text: 'ああ、ずいぶん迷ったんだがね、辞退させてもらったよ。' },
      { speaker: '女', text: 'ご準備がお忙しいからですか。今学期は授業も多いですし。' },
      { speaker: '男', text: '忙しいには忙しいが、その程度のことで断るようじゃ研究者は務まらんよ。' },
      { speaker: '女', text: 'では、テーマが先生のご専門と合わなかったとか。' },
      { speaker: '男', text: 'テーマ自体は願ってもないものだった。ただね、今進めている共同研究のデータがまだ検証しきれていないんだ。生煮えの結果をあの舞台で語るわけにはいかない。' },
      { speaker: '女', text: '発表の中身に納得がいっていない、ということですか。' },
      { speaker: '男', text: 'そういうことだ。招待してくれた側には申し訳ないが、来年、万全の形で臨みたいと伝えたよ。' },
    ],
    question: '教授はどうして基調講演を辞退したのですか。',
    options: [
      '研究データの検証がまだ終わっていないから',
      '授業が多くて準備の時間が取れないから',
      'テーマが自分の専門と合わなかったから',
      '来年の学会に招待されているから',
    ],
    answerIndex: 0,
    explanation:
      '教授說共同研究的資料「まだ検証しきれていない」，不能拿「生煮えの結果」（半生不熟的結果）上台，這是辭退主因。忙碌被「忙しいには忙しいが、その程度のことで断るようじゃ…」降級排除；主題他說「願ってもないもの」（求之不得），與專業不合是反向干擾；「來年」是他自己提出改期的打算，不是受邀在先。',
    explanationEn:
      'The professor says the joint research data 「まだ検証しきれていない」 and that he cannot present 「生煮えの結果」 (half-baked results) on that stage — that is the real reason for declining. Busyness is dismissed with 「忙しいには忙しいが、その程度のことで断るようじゃ…」; the theme was 「願ってもないもの」 (more than he could ask for), so a mismatch with his specialty is a reversed distractor; and "next year" is his own proposal to return in full form, not a prior invitation.',
  },
  {
    id: 'n1-listening-pointo-005',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'ラジオで、男のアナウンサーが美術館の女の館長にインタビューしています。' },
      { speaker: '男', text: 'この一年で入館者数が倍増したそうですね。改装で展示室が広くなった効果でしょうか。' },
      { speaker: '女', text: '改装の効果もゼロではないでしょうが、実は改装直後はさほど伸びなかったんですよ。' },
      { speaker: '男', text: 'では、話題になった夜間開館の影響ですか。' },
      { speaker: '女', text: '夜間開館は常連の方には好評ですけれど、新規のお客様を呼ぶ力は限られていまして。転機になったのは、地元の高校生に展示解説を任せた企画なんです。' },
      { speaker: '男', text: '高校生が、ですか。' },
      { speaker: '女', text: 'ええ。彼らの言葉は専門用語に頼らない分、かえって作品の核心を突くんですね。それが口コミで広がって、美術館は敷居が高いと思っていた層が足を運んでくださるようになりました。' },
      { speaker: '男', text: '解説が入り口になったわけですね。' },
      { speaker: '女', text: 'おっしゃる通りです。今では予約待ちが出るほどの人気企画です。' },
    ],
    question: '入館者数が増えた一番の要因は何だと言っていますか。',
    options: [
      '高校生が展示解説をする企画が評判になったから',
      '改装で展示室が広くなったから',
      '夜間開館を始めたから',
      '専門家による解説が人気になったから',
    ],
    answerIndex: 0,
    explanation:
      '館長明說「転機になったのは、地元の高校生に展示解説を任せた企画」，靠口碑吸引了原本覺得美術館門檻高的客層。改裝效果被「ゼロではないでしょうが、改装直後はさほど伸びなかった」降級；夜間開館被「新規のお客様を呼ぶ力は限られて」排除；解說者是高中生而非專家，「専門用語に頼らない」才是賣點，選項四正好說反。',
    explanationEn:
      'The director says outright 「転機になったのは、地元の高校生に展示解説を任せた企画」: word of mouth about the students\' commentary drew in people who had felt museums were intimidating. The renovation effect is downgraded — 「ゼロではないでしょうが」, attendance 「改装直後はさほど伸びなかった」; evening hours are ruled out by 「新規のお客様を呼ぶ力は限られて」; and the guides are high schoolers, not experts — 「専門用語に頼らない」 is exactly the selling point, so option four says the reverse.',
  },
  {
    id: 'n1-listening-pointo-006',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'テレビ番組で、女のレポーターが男の農家の人に話を聞いています。' },
      { speaker: '女', text: '十年前に有機栽培に切り替えられたそうですね。やはり販売価格を高くつけられるからでしょうか。' },
      { speaker: '男', text: '高く売れるのは確かですが、手間を考えれば差し引きとんとんですよ。それが目当てなら、とっくに音を上げています。' },
      { speaker: '女', text: 'では、消費者の安全志向の高まりを見込んでのことですか。' },
      { speaker: '男', text: '時流に乗ったと言われればそれまでですがね、きっかけは別にあるんです。うちの畑の土が、農薬で年々痩せていくのが手に取るように分かりましてね。このままでは子の代に渡せる畑がなくなると思ったんです。' },
      { speaker: '女', text: '土を守るためだったんですね。' },
      { speaker: '男', text: 'ええ。案の定、切り替えて五年もすると、ミミズが戻ってきました。' },
      { speaker: '女', text: '収量のほうはいかがですか。' },
      { speaker: '男', text: '正直、まだ以前には及びません。それでも後悔はしていませんよ。' },
    ],
    question: '男の人が有機栽培に切り替えた一番のきっかけは何ですか。',
    options: [
      '畑の土が農薬で痩せていくのが分かったから',
      '有機野菜は高い値段で売れるから',
      '消費者の安全志向が高まっていたから',
      '収量が以前より増えると見込んだから',
    ],
    answerIndex: 0,
    explanation:
      '契機是親眼看著「畑の土が農薬で年々痩せていく」，擔心沒有田可以傳給下一代。高價賣點被「手間を考えれば差し引きとんとん」（扣掉工夫打平）降級，還說「それが目当てならとっくに音を上げています」；安全志向被「きっかけは別にあるんです」撇開；收量他自承「まだ以前には及びません」，選項四與事實相反。',
    explanationEn:
      'The trigger was watching 「畑の土が農薬で年々痩せていく」 with his own eyes and fearing there would be no field left to pass to his children. The higher selling price is downgraded — 「手間を考えれば差し引きとんとん」 (it breaks even once you count the labor), and 「それが目当てならとっくに音を上げています」; consumer safety consciousness is brushed aside with 「きっかけは別にあるんです」; and on yield he admits 「まだ以前には及びません」, so option four contradicts the facts.',
  },
  {
    id: 'n1-listening-pointo-007',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で、女の人と男の人が同僚の課長について話しています。' },
      { speaker: '女', text: '課長、ロンドン支社への赴任、断ったらしいですね。あんなに希望していたのに。' },
      { speaker: '男', text: '私も驚いて本人に聞いてみたんですよ。てっきり語学に自信がないのかと思ったら、笑われました。毎朝オンラインで英会話を続けているそうで。' },
      { speaker: '女', text: 'じゃあ、お子さんの受験ですか。来年、高校受験だと伺いましたけど。' },
      { speaker: '男', text: 'それも頭をよぎったにはよぎったそうです。ただ、ご本人いわく、受験なら単身赴任という手もあると。決め手はお母様の介護だそうですよ。最近、容体が思わしくなくて、施設に入るかどうかの瀬戸際らしいんです。' },
      { speaker: '女', text: 'そうでしたか。それは代わりがききませんものね。' },
      { speaker: '男', text: 'ええ。会社も事情が事情だけに、無理には勧められなかったようです。' },
      { speaker: '女', text: '次の機会があるといいですね。' },
      { speaker: '男', text: '本人も、落ち着いたら改めて手を挙げるつもりだと言っていましたよ。' },
    ],
    question: '課長が海外赴任を断った一番の理由は何ですか。',
    options: [
      '母親の介護をしなければならないから',
      '子どもの高校受験が近いから',
      '語学に自信がないから',
      '会社に赴任を反対されたから',
    ],
    answerIndex: 0,
    explanation:
      '轉述中明說「決め手はお母様の介護」，母親病況危急、正處於是否入住機構的關頭，無人可替代。小孩考高中雖「頭をよぎったにはよぎった」（確實閃過念頭）但被「受験なら単身赴任という手もある」降級；語學一項被本人笑著否認（每天早上都在上線上英語會話）；公司並未反對，只是「無理には勧められなかった」。',
    explanationEn:
      'As relayed, 「決め手はお母様の介護」: his mother\'s condition is critical and she is on the verge of entering a care facility — something no one else can take over. The child\'s entrance exam did cross his mind (「頭をよぎったにはよぎった」) but is downgraded by 「受験なら単身赴任という手もある」; the language worry is laughed off by the man himself, who takes online English conversation every morning; and the company did not object — it merely 「無理には勧められなかった」.',
  },
  {
    id: 'n1-listening-pointo-008',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'テレビ番組で、男のアナウンサーが老舗旅館の女将に話を聞いています。' },
      { speaker: '男', text: '創業百年を機に大改装をされたそうですが、一番こだわったのはどこでしょう。客室の露天風呂が話題になっていますね。' },
      { speaker: '女', text: '露天風呂は確かに評判をいただいていますが、あれはむしろ設計士さんの提案に乗っただけでして。' },
      { speaker: '男', text: 'では、地元の食材を生かしたお料理のほうですか。' },
      { speaker: '女', text: 'お料理は改装前から代々の板長が守ってきたものですから、今回特に変えたわけではないんですよ。私が何より譲れなかったのは、廊下や梁に創業当時の木材を残すことでした。' },
      { speaker: '男', text: '新しくするのではなく、残すことに、ですか。' },
      { speaker: '女', text: 'ええ。百年分のお客様の足音が染み込んだ木を捨ててしまったら、うちがうちでなくなる気がしましてね。工期が倍近く延びましたが、大工さんに拝み倒しました。' },
      { speaker: '男', text: 'それであの飴色の廊下なんですね。' },
      { speaker: '女', text: 'はい。お客様が一番懐かしがってくださるのも、あの廊下なんですよ。' },
    ],
    question: '女将が改装で一番こだわったのはどんなことですか。',
    options: [
      '創業当時の木材を廊下や梁に残すこと',
      '客室に露天風呂を付けること',
      '地元の食材を生かした料理に変えること',
      '工期をできるだけ短くすること',
    ],
    answerIndex: 0,
    explanation:
      '女將明言「私が何より譲れなかったのは、廊下や梁に創業当時の木材を残すこと」，甚至不惜工期延長近一倍。露天風呂雖受好評，卻被「設計士さんの提案に乗っただけ」降級為別人的主意；料理是歷代主廚一直守下來的，「特に変えたわけではない」；工期反而是被犧牲的項目，選項四與內容相反。',
    explanationEn:
      'The proprietress declares 「私が何より譲れなかったのは、廊下や梁に創業当時の木材を残すこと」, even letting the construction period nearly double for it. The open-air baths, though popular, are downgraded as merely 「設計士さんの提案に乗っただけ」 — someone else\'s idea; the cuisine has been guarded by successive head chefs and 「特に変えたわけではない」; and the schedule was the thing sacrificed, so shortening it (option four) contradicts the content.',
  },
  {
    id: 'n1-listening-pointo-009',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'ラジオで、女のアナウンサーが市役所の男の担当者に話を聞いています。' },
      { speaker: '女', text: '商店街の空き店舗を若い起業家に貸し出す事業が好評だそうですね。家賃の補助が手厚いのが人気の理由でしょうか。' },
      { speaker: '男', text: '補助はあくまで呼び水でして、額だけならよその市のほうが手厚いくらいなんですよ。' },
      { speaker: '女', text: 'では、駅から近いという立地の良さでしょうか。' },
      { speaker: '男', text: '立地は正直、胸を張れるほどではありません。うちが何より重視したのは、商店街の先輩方が新規の店主に商売のいろはを教える仕組みです。' },
      { speaker: '女', text: 'ベテランと新人を組ませるわけですね。' },
      { speaker: '男', text: 'ええ。開業しても三年持たずに畳む店が多いのは、資金より経験の不足が大きいんです。帳簿の付け方から常連さんとの付き合い方まで、隣の店主が師匠になる。これが定着率を押し上げていると自負しています。' },
      { speaker: '女', text: '単にお金を出すだけではないと。' },
      { speaker: '男', text: 'おっしゃる通りです。おかげさまで、この三年で閉めた店は一軒もありません。' },
    ],
    question: '男の人はこの事業で最も重視したのは何だと言っていますか。',
    options: [
      '先輩の店主が新しい店主に商売を教える仕組み',
      '手厚い家賃の補助',
      '駅から近い立地の良さ',
      '開業資金の貸し付け',
    ],
    answerIndex: 0,
    explanation:
      '負責人明說「うちが何より重視したのは、商店街の先輩方が新規の店主に商売のいろはを教える仕組み」，因為倒店主因是經驗不足而非資金。房租補助被「あくまで呼び水」（只是引子）降級，金額還輸別的市；立地被「胸を張れるほどではありません」自貶排除；「開業資金の貸し付け」對話中根本沒提，且他強調「資金より経験の不足」。',
    explanationEn:
      'The official says clearly 「うちが何より重視したのは、商店街の先輩方が新規の店主に商売のいろはを教える仕組み」, because shops fail mainly from lack of experience, not funds. The rent subsidy is downgraded as 「あくまで呼び水」 (just a lure), and other cities offer more anyway; the location is self-deprecated with 「胸を張れるほどではありません」; and startup loans are never mentioned in the conversation — he even stresses 「資金より経験の不足」.',
  },
  {
    id: 'n1-listening-pointo-010',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '記者会見で、女の記者が男のマラソン選手にインタビューしています。' },
      { speaker: '女', text: '現役引退を決断された一番の理由をお聞かせください。やはり長年の膝の故障でしょうか。' },
      { speaker: '男', text: '膝のせいにできれば楽なんですがね、実は手術後の経過は良好で、走ること自体に支障はないんです。' },
      { speaker: '女', text: 'では、若手の台頭で代表入りが難しくなったからですか。' },
      { speaker: '男', text: '彼らに追われる立場はむしろ張り合いがありましたよ。決め手は、去年の大会のゴールの瞬間、悔しさより先に安堵が来てしまったことなんです。' },
      { speaker: '女', text: '安堵、ですか。' },
      { speaker: '男', text: 'ええ。ああ終わったと、ほっとしてしまった。勝ちたいという飢えが消えた選手が走り続けるのは、応援してくださる方々に失礼だと思ったんです。' },
      { speaker: '女', text: 'お気持ちの問題だったんですね。' },
      { speaker: '男', text: 'そうです。体より先に、心が競技を離れてしまいました。' },
    ],
    question: '男の人が引退を決めた一番の理由は何ですか。',
    options: [
      '勝ちたいという気持ちがなくなったから',
      '膝の故障で走れなくなったから',
      '若手の台頭で代表入りが難しくなったから',
      '応援してくれる人が減ったから',
    ],
    answerIndex: 0,
    explanation:
      '選手說決め手是衝線瞬間「悔しさより先に安堵が来てしまった」——求勝的飢渴消失了，「体より先に、心が競技を離れた」。膝傷被「手術後の経過は良好で、走ること自体に支障はない」明確否定；年輕選手的競爭反而讓他覺得「張り合いがあった」（有勁）；他是怕對支持者失禮，並非支持者變少，選項四無中生有。',
    explanationEn:
      'The runner says the decisive moment was crossing last year\'s finish line and feeling 「悔しさより先に安堵が来てしまった」 — the hunger to win was gone, and 「体より先に、心が競技を離れた」. The knee is explicitly ruled out by 「手術後の経過は良好で、走ること自体に支障はない」; the rise of younger runners actually gave him 「張り合い」 (motivation); and he worried about being disrespectful to his supporters, not about their numbers shrinking — option four is invented.',
  },
  {
    id: 'n1-listening-pointo-011',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'テレビ番組で、男のアナウンサーがパン屋の女の店主に話を聞いています。' },
      { speaker: '男', text: '大手から全国チェーン展開の話があったのに、お断りになったそうですね。やはり資金面の不安からですか。' },
      { speaker: '女', text: 'いえいえ、資金は先方が全部持つという破格の条件でしたから、その心配は要らなかったんです。' },
      { speaker: '男', text: 'では、今のお店だけで手一杯ということでしょうか。行列が絶えないと伺いますが。' },
      { speaker: '女', text: '忙しいのは忙しいですが、人を増やせば済む話ですからね。断った理由はもっと根本的なところで、うちのパンはレシピにできないんですよ。' },
      { speaker: '男', text: 'レシピにできない、と言いますと。' },
      { speaker: '女', text: '生地の水加減も発酵の時間も、その日の気温と湿度で毎朝変えているんです。数字にした途端、別物になってしまう。何十店舗にも広げたら、うちの味は守れません。' },
      { speaker: '男', text: 'マニュアル化できない手仕事だということですね。' },
      { speaker: '女', text: 'ええ。この店の窯の前でしか焼けない味なんです。' },
    ],
    question: '女の人がチェーン展開の話を断った一番の理由は何ですか。',
    options: [
      'パン作りがマニュアル化できない手仕事だから',
      '資金面に不安があったから',
      '今の店が忙しくて手が回らないから',
      '大手の提示した条件が悪かったから',
    ],
    answerIndex: 0,
    explanation:
      '店主明說「うちのパンはレシピにできない」——水量與發酵時間每天隨氣溫濕度調整，「数字にした途端、別物になってしまう」，展店會守不住味道。資金被「先方が全部持つ破格の条件」明確排除；忙碌被「人を増やせば済む話」降級；條件其實是「破格」的好條件，選項四與內容相反。',
    explanationEn:
      'The owner says outright 「うちのパンはレシピにできない」 — she adjusts water and fermentation time every morning by temperature and humidity, and 「数字にした途端、別物になってしまう」, so expanding to dozens of stores would destroy the taste. Funding is expressly eliminated: the chain offered 「破格の条件」 covering everything; busyness is downgraded with 「人を増やせば済む話」; and the terms were exceptionally generous, so option four contradicts the content.',
  },
  {
    id: 'n1-listening-pointo-012',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'ラジオで、男のアナウンサーが図書館の女の館長にインタビューしています。' },
      { speaker: '男', text: '貴重な郷土資料のデジタル化を進めておられますね。書庫が手狭になったのがきっかけですか。' },
      { speaker: '女', text: '場所が空くのは事実ですけれど、それはあくまで副産物でして。原本はデジタル化した後も全部保管しますから、実は書庫はほとんど空かないんですよ。' },
      { speaker: '男', text: 'では、職員の手間を減らすためでしょうか。閲覧のたびに出納するのは大変だと聞きます。' },
      { speaker: '女', text: '正直に言えば、撮影や校正でかえって手間は増えています。私どもが何より恐れているのは、災害なんです。' },
      { speaker: '男', text: '災害、ですか。' },
      { speaker: '女', text: 'ええ。隣の県で水害があったとき、江戸時代の文書が一晩で泥に沈むのを目の当たりにしましてね。原本は一点物ですから、失われたら二度と戻りません。せめて中身だけでも複製を残しておきたいんです。' },
      { speaker: '男', text: '万一に備えた保険というわけですね。' },
      { speaker: '女', text: 'そうです。遠方の研究者に喜ばれているのは、ありがたいおまけですね。' },
    ],
    question: '資料のデジタル化の一番の目的は何だと言っていますか。',
    options: [
      '災害で資料が失われるのに備えるため',
      '書庫の場所を空けるため',
      '職員の出納の手間を減らすため',
      '遠方の研究者が利用しやすくするため',
    ],
    answerIndex: 0,
    explanation:
      '館長說最害怕的是災害：親眼見過水災讓江戶時代文書「一晩で泥に沈む」，原本是孤本，「せめて中身だけでも複製を残したい」。空出書庫被「あくまで副産物」降級，且原本仍全數保管；省人力被「かえって手間は増えています」反向否定；方便遠地研究者只是「ありがたいおまけ」（附帶的好處）。',
    explanationEn:
      'The director says what they fear above all is disaster: she watched Edo-period documents in a neighboring prefecture 「一晩で泥に沈む」 in a flood, and since originals are one of a kind, 「せめて中身だけでも複製を残したい」. Freeing shelf space is downgraded as 「あくまで副産物」 — the originals are all kept anyway, so the stacks barely empty; saving staff labor is refuted head-on by 「かえって手間は増えています」; and convenience for distant researchers is just 「ありがたいおまけ」, a welcome bonus.',
  },
  {
    id: 'n1-listening-pointo-013',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'ラジオ番組で、女のアナウンサーが辞書編集者の男の人に話を聞いています。' },
      { speaker: '女', text: '十年ぶりの大改訂が完成したそうですね。何万もの語釈を書き直すのが、やはり一番のご苦労でしたか。' },
      { speaker: '男', text: '語釈の書き直しは確かに量こそ膨大ですが、三十年やってきた身には慣れた作業でしてね。' },
      { speaker: '女', text: 'では、用例を新しく作る作業でしょうか。' },
      { speaker: '男', text: '例文作りはむしろ楽しみの部類です。頭を抱えたのは、新語の線引きなんですよ。' },
      { speaker: '女', text: '線引き、と言いますと。' },
      { speaker: '男', text: '毎年何百と生まれる言葉のうち、十年後も使われている語だけを載せたい。ですが未来は誰にも分かりません。載せれば軽率と言われ、見送れば時代遅れと言われる。この取捨選択には最後まで胃が痛みました。' },
      { speaker: '女', text: 'どちらに転んでも批判は避けられないわけですね。' },
      { speaker: '男', text: 'ええ。辞書は選ばなかった言葉にこそ、編集者の覚悟が出るんです。' },
    ],
    question: '男の人が改訂で一番苦労したのはどんなことですか。',
    options: [
      'どの新語を載せるかの取捨選択',
      '膨大な語釈を書き直すこと',
      '新しい用例を作ること',
      '批判的な投書に対応すること',
    ],
    answerIndex: 0,
    explanation:
      '編輯說「頭を抱えたのは、新語の線引き」——收了會被罵輕率、不收會被罵過時，取捨讓他「最後まで胃が痛みました」。改寫語釋雖然量大，但被「慣れた作業」降級；造例句被「むしろ楽しみの部類」排除；「批判」只是他預想中兩難的後果，對話裡並沒有處理投書這回事，選項四無中生有。',
    explanationEn:
      'The editor says 「頭を抱えたのは、新語の線引き」: include a word and be called rash, omit it and be called out of date — the winnowing left him with 「最後まで胃が痛みました」. Rewriting definitions, though vast in volume, is downgraded as 「慣れた作業」 after thirty years; composing example sentences is ruled out as 「むしろ楽しみの部類」; and criticism is only the anticipated consequence of his dilemma — handling reader complaints never comes up, so option four is invented.',
  },
  {
    id: 'n1-listening-pointo-014',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '記者会見で、女の記者がサッカーチームの男の監督にインタビューしています。' },
      { speaker: '女', text: '今季から起用している十九歳の田中選手ですが、監督は彼のどこを一番買っておられるんですか。あの足の速さでしょうか。' },
      { speaker: '男', text: '速いことは速いですが、速いだけの選手ならどのチームにもごろごろいますよ。' },
      { speaker: '女', text: 'では、得点力ですか。先週も一点決めましたが。' },
      { speaker: '男', text: '数字だけ見れば、正直まだ物足りません。私が買っているのは、失敗を恐れない姿勢なんです。' },
      { speaker: '女', text: '姿勢、ですか。' },
      { speaker: '男', text: 'ええ。彼は十回仕掛けて九回奪われても、十一回目も迷わず勝負するんです。若いうちに縮こまる癖がつくと一生直りません。ああいう選手だけが、壁を越えていくんですよ。' },
      { speaker: '女', text: '練習態度も真面目だと聞きますが。' },
      { speaker: '男', text: '真面目なのはプロなら当たり前のことでね、褒めるところではありません。' },
    ],
    question: '監督は田中選手のどんなところを一番評価していますか。',
    options: [
      '失敗を恐れずに挑戦し続けるところ',
      '誰よりも足が速いところ',
      '得点力が高いところ',
      '練習態度が真面目なところ',
    ],
    answerIndex: 0,
    explanation:
      '監督明說「私が買っているのは、失敗を恐れない姿勢」——被搶九次第十一次照樣毫不猶豫地挑戰，這種選手才能突破高牆。速度被「速いだけの選手ならごろごろいます」降級；得分被「数字だけ見れば正直まだ物足りません」否定；認真被「プロなら当たり前のこと、褒めるところではありません」明確排除。',
    explanationEn:
      'The coach says outright 「私が買っているのは、失敗を恐れない姿勢」: robbed nine times out of ten attempts, the player still challenges without hesitation on the eleventh — only such players break through the wall. Speed is downgraded with 「速いだけの選手ならごろごろいます」; scoring is dismissed by 「数字だけ見れば正直まだ物足りません」; and diligence is explicitly excluded — 「プロなら当たり前のことでね、褒めるところではありません」.',
  },
  {
    id: 'n1-listening-pointo-015',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'テレビ番組で、男のアナウンサーが劇団を主宰する女の人に話を聞いています。' },
      { speaker: '男', text: 'もう二十年、百席ほどの小さな劇場だけで公演を続けておられますね。大きな劇場は費用がかかるからでしょうか。' },
      { speaker: '女', text: 'よく誤解されるんですが、一席あたりで計算すると、小さい劇場のほうがむしろ割高なんですよ。' },
      { speaker: '男', text: 'では、あの劇場がご自身の故郷にあるからですか。' },
      { speaker: '女', text: '故郷に恩返しをという気持ちも、ないとは言いません。でも本当の理由は、客席との距離なんです。' },
      { speaker: '男', text: '距離、ですか。' },
      { speaker: '女', text: 'ええ。あの広さだと、最後列のお客様の息遣いまで舞台に届くんです。笑いをこらえる気配、身を乗り出す衣擦れの音。役者はそれを浴びて、その晩の芝居を作り変えていく。芝居はお客様と一緒に育てるものなんです。' },
      { speaker: '男', text: '大劇場から声がかかっても、動かれないわけですね。' },
      { speaker: '女', text: 'ありがたいお話ですが、当分はここを離れるつもりはありません。' },
    ],
    question: '女の人が小さな劇場で公演を続ける一番の理由は何ですか。',
    options: [
      '客席が近く、観客の反応が芝居を育てるから',
      '大きな劇場より費用が安く済むから',
      '劇場が自分の故郷にあるから',
      '大きな劇場から声がかからないから',
    ],
    answerIndex: 0,
    explanation:
      '主宰說真正的理由是「客席との距離」——連最後一排觀眾的氣息都能傳到舞台，演員靠這些反應「その晩の芝居を作り変えていく」，戲是和觀眾一起養大的。費用被「一席あたりではむしろ割高」反向否定；報答故鄉被「ないとは言いません。でも本当の理由は…」降級；大劇場其實有邀約（声がかかっても動かない），選項四與內容相反。',
    explanationEn:
      'The director says the real reason is 「客席との距離」: in that small hall even the breathing of the back row reaches the stage, and the actors soak up those reactions and 「その晩の芝居を作り変えていく」 — theater is raised together with the audience. Cost is refuted head-on: per seat, small theaters are 「むしろ割高」; repaying her hometown is downgraded with 「ないとは言いません。でも本当の理由は…」; and large theaters have in fact courted her (she stays even when 「声がかかって」), so option four contradicts the content.',
  },
  {
    id: 'n1-listening-pointo-016',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'ラジオで、女のアナウンサーが町工場の男の社長にインタビューしています。' },
      { speaker: '女', text: '一時は海外移転まで検討されていたのに、国内に新工場を建てられたそうですね。円安で国内生産の採算が合うようになったからですか。' },
      { speaker: '男', text: '円安は確かに追い風ですが、為替なんていつひっくり返るか分かりません。あれを当てにして工場は建てられませんよ。' },
      { speaker: '女', text: 'では、市の手厚い補助金が決め手ですか。' },
      { speaker: '男', text: '補助はありがたい後押しでしたが、あくまで背中を押された程度でしてね。腹を決めたのは、うちの職人の技を絶やしたくなかったからです。' },
      { speaker: '女', text: '技の継承、ですか。' },
      { speaker: '男', text: 'ええ。うちの研磨の技術は、機械にも図面にも落とせません。ベテランの手元を若い者が毎日隣で見て、十年かけてようやく身につくものなんです。海外に移せば、その鎖が切れてしまう。' },
      { speaker: '女', text: '人から人へしか渡せないものなんですね。' },
      { speaker: '男', text: 'そうです。新工場は、いわば技を渡すための道場ですよ。' },
    ],
    question: '社長が国内に新工場を建てた一番の理由は何ですか。',
    options: [
      '職人の技を若手に継承するため',
      '円安で国内生産の採算が合うから',
      '市の補助金が手厚かったから',
      '海外の人件費が上がったから',
    ],
    answerIndex: 0,
    explanation:
      '社長說下定決心（腹を決めた）是因為不想讓師傅的技術斷絕——研磨技術「機械にも図面にも落とせません」，只能靠年輕人天天在旁邊看十年才學得會，移到海外「鎖が切れてしまう」。日圓貶值被「いつひっくり返るか分からない、当てにできない」降級；補助金被「あくまで背中を押された程度」降級；海外人事費對話中完全沒提，無中生有。',
    explanationEn:
      'The president says he made up his mind (「腹を決めた」) because he refused to let his artisans\' craft die out: the polishing technique 「機械にも図面にも落とせません」 and can only be absorbed by young workers watching a veteran\'s hands daily for ten years — moving abroad would mean 「鎖が切れてしまう」. The weak yen is downgraded — exchange rates 「いつひっくり返るか分からない」 and cannot be counted on; the subsidy was 「あくまで背中を押された程度」; and overseas labor costs are never mentioned at all — a fabricated option.',
  },
  {
    id: 'n1-listening-pointo-017',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'テレビ番組で、男のアナウンサーが登山ガイドの女の人に話を聞いています。' },
      { speaker: '男', text: '今年からツアーの定員を二十人から十人に減らされたそうですね。山小屋に泊まれる人数の制限ですか。' },
      { speaker: '女', text: '小屋は二十人でも問題なく受けてくれますので、そこではないんです。' },
      { speaker: '男', text: 'では、事故を防ぐためでしょうか。' },
      { speaker: '女', text: '安全はもちろん大前提ですが、実は二十人でも副ガイドを付ければ十分対応できるんですよ。減らした一番のわけは、高山植物なんです。' },
      { speaker: '男', text: '植物、ですか。' },
      { speaker: '女', text: 'ええ。列が長くなると、後ろのほうのお客様が写真を撮ろうと登山道を外れても、私の目が届かないんです。あの花畑は一度踏まれたら、元に戻るのに何十年もかかります。全員の足元を見ていられる人数が、私には十人が限度でした。' },
      { speaker: '男', text: '収入は減ってしまいますよね。' },
      { speaker: '女', text: '正直痛いですが、山が荒れたらこの仕事自体が成り立ちませんから。' },
    ],
    question: '女の人がツアーの定員を減らした一番の理由は何ですか。',
    options: [
      '客が登山道を外れて高山植物を踏むのを防ぐため',
      '山小屋に泊まれる人数に制限があるから',
      '人数が多いと事故に対応できないから',
      '収入を増やしたいから',
    ],
    answerIndex: 0,
    explanation:
      '導遊說減少人數「一番のわけは高山植物」——隊伍太長時，後面的客人離開登山道拍照她照顧不到，花田被踩過要花數十年才能復原，十人是她能盯住所有人腳下的極限。山屋被「二十人でも問題なく受けてくれます」排除；安全被「大前提ですが、副ガイドを付ければ十分対応できる」降級；收入她自承「正直痛い」（反而減少），選項四相反。',
    explanationEn:
      'The guide says the number-one reason (「一番のわけ」) is the alpine flora: with a long line, she cannot see customers at the rear stepping off the trail for photos, and a flower field once trampled takes decades to recover — ten people is the most whose feet she can watch. The mountain hut is eliminated by 「二十人でも問題なく受けてくれます」; safety is downgraded — a premise, but 「副ガイドを付ければ十分対応できる」 even with twenty; and income actually falls (「正直痛い」), so option four is the reverse.',
  },
  {
    id: 'n1-listening-pointo-018',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'ラジオ番組で、女のアナウンサーが高校の男の校長に話を聞いています。' },
      { speaker: '女', text: '来年度から制服を自由化されるそうですね。近隣の学校で自由化が相次いでいますから、その流れに乗った形でしょうか。' },
      { speaker: '男', text: 'よそがどうしているかは、正直ほとんど気にしていません。横並びで決めるようなことではありませんから。' },
      { speaker: '女', text: 'では、生徒からの強い要望があったんですか。' },
      { speaker: '男', text: 'それが面白いことに、アンケートでは賛否がちょうど半々でしてね。要望に押されたわけではないんです。私の狙いは、生徒に毎朝一つ、自分で決めさせることなんですよ。' },
      { speaker: '女', text: '服装を自分で決める、ということ自体が目的なんですか。' },
      { speaker: '男', text: 'ええ。決められた服を着るだけなら、判断力は育ちません。場に合うかどうかを毎朝自分の頭で考えて、その結果を自分で引き受ける。小さな決断の積み重ねこそ、卒業後に効いてくるんです。' },
      { speaker: '女', text: '保護者の方からは、服代の負担を心配する声もあるようですが。' },
      { speaker: '男', text: 'そこは制服の着用も引き続き認めますので、無理に買い替える必要はありません。' },
    ],
    question: '校長が制服を自由化する一番の狙いは何ですか。',
    options: [
      '生徒が自分で考えて決める力を育てること',
      '近隣の学校の自由化の流れに合わせること',
      '生徒からの強い要望に応えること',
      '保護者の服代の負担を減らすこと',
    ],
    answerIndex: 0,
    explanation:
      '校長明說狙い是「生徒に毎朝一つ、自分で決めさせること」——每天自己判斷穿著是否合乎場合並承擔結果，小決斷的累積畢業後才見效。跟進他校被「よそはほとんど気にしていません」否定；學生要求被「賛否がちょうど半々、要望に押されたわけではない」排除；治裝費是記者提出的疑慮，校長只回應配套（制服仍可穿），並非目的。',
    explanationEn:
      'The principal states his aim plainly: 「生徒に毎朝一つ、自分で決めさせること」 — judging every morning whether an outfit suits the occasion and owning the result, an accumulation of small decisions that pays off after graduation. Following neighboring schools is denied by 「よそはほとんど気にしていません」; student demand is ruled out because the survey split exactly half and half — 「要望に押されたわけではない」; and the clothing-cost concern is raised by the interviewer, to which he only offers the accommodation that uniforms may still be worn — it is not his purpose.',
  },
  {
    id: 'n1-listening-pointo-019',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: 'テレビ番組で、男のアナウンサーが気象を研究する女の人に話を聞いています。' },
      { speaker: '男', text: '桜の開花が年々早まっていますね。お花見の予定が立てにくくなったとか、観光への影響がよく話題になりますが。' },
      { speaker: '女', text: 'ええ、取材でもまずそれを聞かれます。ただ、祭りの日程は人間の側でずらせますから、私はさほど心配していないんです。' },
      { speaker: '男', text: 'では、このまま暖冬が続くと、桜自体が咲かなくなるおそれがあるんでしょうか。' },
      { speaker: '女', text: '一部の暖かい地方では将来そういう懸念もありますが、大半の地域ではまだ先の話です。私が今一番案じているのは、生き物同士の時間のずれなんです。' },
      { speaker: '男', text: '時間のずれ、ですか。' },
      { speaker: '女', text: 'ええ。花は暖かさに敏感に反応して早く咲きますが、蜜を運ぶ昆虫の目覚めはそれほど早まらないんです。花が咲いても虫がいない。すると実がならず、その実を食べる鳥にも響く。ずれが一つ生じると、鎖のように連鎖していくんです。' },
      { speaker: '男', text: '桜だけの問題ではないんですね。' },
      { speaker: '女', text: 'そうなんです。桜は目に見えやすい警告にすぎません。' },
    ],
    question: '女の人が開花の早まりについて最も心配しているのは何ですか。',
    options: [
      '花と昆虫など生き物の間で時期のずれが連鎖すること',
      '花見や観光の予定が立てにくくなること',
      '桜自体が咲かなくなること',
      '開花予想が外れて研究の信頼が落ちること',
    ],
    answerIndex: 0,
    explanation:
      '研究者說最擔心的是「生き物同士の時間のずれ」——花提早開但昆蟲甦醒沒跟著提早，花開了沒蟲授粉就不結果，連鳥都受影響，錯位會像鎖鏈一樣連鎖擴散。賞花與觀光被「日程は人間の側でずらせるから、さほど心配していない」降級；櫻花不開花被「大半の地域ではまだ先の話」排除；預測失準與研究信譽對話中沒有提到，無中生有。',
    explanationEn:
      'The researcher says her greatest worry is 「生き物同士の時間のずれ」: blossoms respond quickly to warmth and open earlier, but the pollinating insects\' awakening does not shift as much — flowers with no insects set no fruit, which then hits the birds that eat it, one mismatch cascading down the chain. Blossom-viewing and tourism are downgraded because festival dates 「人間の側でずらせる」, so she is 「さほど心配していない」; cherry trees failing to bloom is 「大半の地域ではまだ先の話」; and forecast misses harming research credibility never comes up — a fabricated option.',
  },
  {
    id: 'n1-listening-pointo-020',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社の休憩室で、男の人と女の人が話しています。' },
      { speaker: '男', text: 'そういえば転職して半年だっけ。前の会社、業界じゃ名の通った大手だったのに、思い切ったよね。給料に釣られたって聞いたけど。' },
      { speaker: '女', text: '誰よ、そんなこと言ったの。実はここ、前より一割下がってるのよ。' },
      { speaker: '男', text: 'えっ、下がったの。じゃあ通勤が楽になったとか。' },
      { speaker: '女', text: 'それも逆。乗り換えが一回増えて、二十分は遠くなったわ。' },
      { speaker: '男', text: 'じゃあ何が決め手だったのさ。' },
      { speaker: '女', text: '面接のときにね、社員の人が三人同席したんだけど、自分の失敗談を身振り手振りで、それは楽しそうに話すのよ。ああ、この人たちは仕事を面白がってるんだなって。前の会社で私、愚痴しか言わなくなってたから、はっとしちゃって。' },
      { speaker: '男', text: 'なるほどね。条件より空気を取ったわけだ。' },
      { speaker: '女', text: 'そういうこと。おかげで今は、日曜の夜が憂鬱じゃなくなったわ。' },
    ],
    question: '女の人が今の会社に転職を決めた一番の決め手は何ですか。',
    options: [
      '社員が仕事を楽しそうに語る姿を見たこと',
      '前の会社より給料が高かったこと',
      '通勤が楽になること',
      '業界で名の通った大手であること',
    ],
    answerIndex: 0,
    explanation:
      '女方說決め手是面試時同席的員工「自分の失敗談をそれは楽しそうに話す」——她驚覺這群人是真心覺得工作有趣，對照自己在前公司只剩抱怨。薪水被「前より一割下がってる」反向否定；通勤「それも逆」，多轉一次車還遠了二十分鐘；「名の通った大手」是她離開的前公司的形容，不是現在這家，選項四張冠李戴。',
    explanationEn:
      'The woman says the deciding factor was the interview, where the three employees present told their own failure stories 「それは楽しそうに話す」 — she realized these people genuinely enjoyed their work, a jolt compared with herself, who had come to do nothing but complain at her old job. Salary is refuted outright: here it is 「前より一割下がってる」; the commute is 「それも逆」 — one more transfer and twenty minutes farther; and 「名の通った大手」 describes the company she left, not the current one, so option four pins the label on the wrong firm.',
  },
]
