import type { KaiwaScene } from '../../types'

export const scene: KaiwaScene = {
  id: 'biz-keigo',
  category: 'business',
  title: '敬語入門',
  titleJa: '敬語の基本',
  icon: '🎎',
  suggestedLevel: 'n3',
  dialogues: [
    {
      id: 'biz-keigo-d1',
      title: '尊敬語與謙讓語的分工',
      lines: [
        {
          speaker: '新人',
          gender: '男',
          ja: '先輩、敬語のことでちょっと質問してもいいですか。尊敬語と謙譲語の違いがよく分かりません。',
          reading: 'せんぱい、けいごの ことで ちょっと しつもんしても いいですか。そんけいごと けんじょうごの ちがいが よく わかりません。',
          zh: '前輩，可以問一下敬語的問題嗎？我不太懂尊敬語和謙讓語的差別。',
        },
        {
          speaker: '先輩',
          gender: '女',
          ja: 'いい質問ね。簡単に言うと、尊敬語は相手の動作を高める言葉で、謙譲語は自分の動作を低くする言葉よ。',
          reading: 'いい しつもんね。かんたんに いうと、そんけいごは あいての どうさを たかめる ことばで、けんじょうごは じぶんの どうさを ひくくする ことばよ。',
          zh: '好問題。簡單來說，尊敬語是抬高對方動作的說法，謙讓語是壓低自己動作的說法。',
        },
        {
          speaker: '新人',
          gender: '男',
          ja: '例えば「行く」はどうなりますか。',
          reading: 'たとえば、いくは どう なりますか。',
          zh: '比如說「行く」（去）會變成怎樣呢？',
        },
        {
          speaker: '先輩',
          gender: '女',
          ja: '相手が行くなら「いらっしゃる」、自分が行くなら「伺う」を使うの。',
          reading: 'あいてが いくなら いらっしゃる、じぶんが いくなら うかがうを つかうの。',
          zh: '對方去就用「いらっしゃる」，自己去就用「伺う」。',
        },
        {
          speaker: '新人',
          gender: '男',
          ja: 'じゃあ、「部長が資料を拝見しました」は正しいですか。',
          reading: 'じゃあ、ぶちょうが しりょうを はいけんしましたは ただしいですか。',
          zh: '那「部長拝見了資料」這樣說對嗎？',
        },
        {
          speaker: '先輩',
          gender: '女',
          ja: 'それは間違い。「拝見する」は謙譲語だから、部長の動作には使えないの。「ご覧になりました」が正解よ。',
          reading: 'それは まちがい。はいけんするは けんじょうごだから、ぶちょうの どうさには つかえないの。ごらんに なりましたが せいかいよ。',
          zh: '那就錯了。「拝見する」是謙讓語，不能用在部長的動作上。正確說法是「ご覧になりました」。',
        },
        {
          speaker: '新人',
          gender: '男',
          ja: 'なるほど。相手を高めるか、自分を低くするか、まず考えればいいんですね。',
          reading: 'なるほど。あいてを たかめるか、じぶんを ひくくするか、まず かんがえれば いいんですね。',
          zh: '原來如此。先想清楚是要抬高對方、還是壓低自己就好了對吧。',
        },
        {
          speaker: '先輩',
          gender: '女',
          ja: 'その通り。慣れるまでは動詞ごとに対応表を作って覚えるといいわよ。',
          reading: 'その とおり。なれるまでは どうしごとに たいおうひょうを つくって おぼえると いいわよ。',
          zh: '沒錯。在習慣之前，可以幫每個動詞做一張對照表來記。',
        },
      ],
    },
    {
      id: 'biz-keigo-d2',
      title: '電話中對客戶的自謙',
      lines: [
        {
          speaker: '社員',
          gender: '男',
          ja: 'はい、山田商事でございます。',
          reading: 'はい、やまだしょうじで ございます。',
          zh: '您好，這裡是山田商事。',
        },
        {
          speaker: '取引先',
          gender: '女',
          ja: 'お世話になっております。花丸産業の林と申しますが、佐藤様はいらっしゃいますか。',
          reading: 'おせわに なって おります。はなまるさんぎょうの りんと もうしますが、さとうさまは いらっしゃいますか。',
          zh: '承蒙關照。我是花丸產業的林，請問佐藤先生在嗎？',
        },
        {
          speaker: '社員',
          gender: '男',
          ja: '申し訳ございません。佐藤はただいま席を外しております。',
          reading: 'もうしわけ ございません。さとうは ただいま せきを はずして おります。',
          zh: '非常抱歉，佐藤現在不在位子上。',
        },
        {
          speaker: '取引先',
          gender: '女',
          ja: 'そうですか。では、見積もりの件でお電話したとお伝えいただけますか。',
          reading: 'そうですか。では、みつもりの けんで おでんわしたと おつたえ いただけますか。',
          zh: '這樣啊。那可以麻煩您轉告他，我是為了報價的事來電的嗎？',
        },
        {
          speaker: '社員',
          gender: '男',
          ja: 'かしこまりました。私、営業部の田中と申します。確かに申し伝えます。',
          reading: 'かしこまりました。わたくし、えいぎょうぶの たなかと もうします。たしかに もうしつたえます。',
          zh: '好的。我是業務部的田中，一定會轉達。',
        },
        {
          speaker: '取引先',
          gender: '女',
          ja: '助かります。では、明日の午後、御社に伺ってもよろしいでしょうか。',
          reading: 'たすかります。では、あしたの ごご、おんしゃに うかがっても よろしいでしょうか。',
          zh: '太好了。那明天下午我方便拜訪貴公司嗎？',
        },
        {
          speaker: '社員',
          gender: '男',
          ja: 'はい、お待ちしております。お気をつけてお越しください。',
          reading: 'はい、おまちして おります。おきを つけて おこしください。',
          zh: '好的，恭候您的到來。路上請小心。',
        },
        {
          speaker: '取引先',
          gender: '女',
          ja: 'ありがとうございます。それでは失礼いたします。',
          reading: 'ありがとうございます。それでは しつれい いたします。',
          zh: '謝謝您。那麼我先掛電話了。',
        },
      ],
    },
    {
      id: 'biz-keigo-d3',
      title: '常見敬語地雷糾正',
      lines: [
        {
          speaker: '新人',
          gender: '男',
          ja: '先輩、お疲れさまです。さっき部長に「ご苦労さまです」と言ったら、変な顔をされました。',
          reading: 'せんぱい、おつかれさまです。さっき ぶちょうに ごくろうさまですと いったら、へんな かおを されました。',
          zh: '前輩辛苦了。剛剛我對部長說「ご苦労さまです」，他的表情變得好奇怪。',
        },
        {
          speaker: '先輩',
          gender: '女',
          ja: 'あら、それは危ないわ。「ご苦労さま」は目上の人が目下の人に使う言葉なのよ。',
          reading: 'あら、それは あぶないわ。ごくろうさまは めうえの ひとが めしたの ひとに つかう ことばなのよ。',
          zh: '哎呀，那很危險耶。「ご苦労さま」是上位者慰勞下位者用的話。',
        },
        {
          speaker: '新人',
          gender: '男',
          ja: 'えっ、そうなんですか。じゃあ、上司には何と言えばいいですか。',
          reading: 'えっ、そうなんですか。じゃあ、じょうしには なんと いえば いいですか。',
          zh: '咦，是這樣嗎？那對上司要說什麼才好？',
        },
        {
          speaker: '先輩',
          gender: '女',
          ja: '「お疲れさまです」を使えば間違いないわ。それから、メールで「了解しました」と書いていない？',
          reading: 'おつかれさまですを つかえば まちがいないわ。それから、メールで りょうかいしましたと かいて いない？',
          zh: '用「お疲れさまです」就不會錯。還有，你是不是常在信裡寫「了解しました」？',
        },
        {
          speaker: '新人',
          gender: '男',
          ja: 'はい、いつも書いています。だめですか。',
          reading: 'はい、いつも かいて います。だめですか。',
          zh: '對，我每次都這樣寫。不行嗎？',
        },
        {
          speaker: '先輩',
          gender: '女',
          ja: '「了解」は同僚や目下向きの言葉と感じる人が多いの。上司やお客様には「承知しました」か「かしこまりました」が安心よ。',
          reading: 'りょうかいは どうりょうや めしたむきの ことばと かんじる ひとが おおいの。じょうしや おきゃくさまには しょうちしましたか かしこまりましたが あんしんよ。',
          zh: '很多人覺得「了解」是對同事或晚輩用的詞。對上司或客戶說「承知しました」或「かしこまりました」比較保險。',
        },
        {
          speaker: '新人',
          gender: '男',
          ja: '知りませんでした。今日から気をつけます。',
          reading: 'しりませんでした。きょうから きを つけます。',
          zh: '我都不知道。從今天開始會注意的。',
        },
        {
          speaker: '先輩',
          gender: '女',
          ja: '敬語は形だけじゃなくて、相手との関係を表すものだから、少しずつ覚えていけば大丈夫よ。',
          reading: 'けいごは かたちだけじゃ なくて、あいてとの かんけいを あらわす ものだから、すこしずつ おぼえて いけば だいじょうぶよ。',
          zh: '敬語不只是形式，而是表達你和對方關係的東西，慢慢學起來就沒問題了。',
        },
      ],
    },
  ],
  phrases: [
    {
      ja: '社長は会議室にいらっしゃいます。',
      reading: 'しゃちょうは かいぎしつに いらっしゃいます。',
      zh: '社長在會議室。',
      note: '「いらっしゃる」是「いる・行く・来る」的尊敬語，只用於對方或上位者的動作。',
    },
    {
      ja: '明日、御社に伺います。',
      reading: 'あした、おんしゃに うかがいます。',
      zh: '明天我會拜訪貴公司。',
      note: '「伺う」是「行く・聞く」的謙讓語，只能用在自己的動作，與「いらっしゃる」成對。',
    },
    {
      ja: '営業部の田中と申します。',
      reading: 'えいぎょうぶの たなかと もうします。',
      zh: '我是業務部的田中。',
      note: '「申す」是「言う」的謙讓語，自我介紹的固定說法。',
    },
    {
      ja: '部長は何とおっしゃいましたか。',
      reading: 'ぶちょうは なんと おっしゃいましたか。',
      zh: '部長說了什麼呢？',
      note: '「おっしゃる」是「言う」的尊敬語，和謙讓語「申す」正好成對。',
    },
    {
      ja: 'お送りいただいた資料を拝見しました。',
      reading: 'おおくり いただいた しりょうを はいけんしました。',
      zh: '您寄來的資料我已經看過了。',
      note: '「拝見する」是「見る」的謙讓語，主語只能是自己。',
    },
    {
      ja: 'こちらの企画書をご覧ください。',
      reading: 'こちらの きかくしょを ごらんください。',
      zh: '請過目這份企劃書。',
      note: '「ご覧になる」是「見る」的尊敬語，請對方看時用「ご覧ください」。',
    },
    {
      ja: 'お客様がご注文をなさいました。',
      reading: 'おきゃくさまが ごちゅうもんを なさいました。',
      zh: '客人下訂了。',
      note: '「なさる」是「する」的尊敬語，用於對方的動作。',
    },
    {
      ja: '資料の準備は私がいたします。',
      reading: 'しりょうの じゅんびは わたくしが いたします。',
      zh: '資料由我來準備。',
      note: '「いたす」是「する」的謙讓語，和「なさる」成對。',
    },
    {
      ja: '先ほどお土産をいただきました。',
      reading: 'さきほど おみやげを いただきました。',
      zh: '剛才收下了伴手禮。',
      note: '「いただく」是「もらう・食べる・飲む」的謙讓語。',
    },
    {
      ja: 'どうぞ遠慮なく召し上がってください。',
      reading: 'どうぞ えんりょなく めしあがって ください。',
      zh: '請別客氣盡量享用。',
      note: '「召し上がる」是「食べる・飲む」的尊敬語，與「いただく」成對。',
    },
    {
      ja: '課長はもうお帰りになりました。',
      reading: 'かちょうは もう おかえりに なりました。',
      zh: '課長已經回去了。',
      note: '「お〜になる」是萬用尊敬語句型，套一般動詞就能抬高對方。',
    },
    {
      ja: '後ほどこちらからご連絡いたします。',
      reading: 'のちほど こちらから ごれんらく いたします。',
      zh: '稍後由我們與您聯繫。',
      note: '「ご〜いたす」是萬用謙讓語句型，用於自己對對方做的動作。',
    },
  ],
  drills: [
    {
      kind: 'choice',
      id: 'biz-keigo-001',
      stem: '（電話で取引先に）いつもお世話になっております。営業部の田中と（　）。',
      options: ['申します', 'おっしゃいます', 'なさいます', 'ご覧になります'],
      answerIndex: 0,
      explanation:
        '對外報上自己的名字，要用「言う」的謙讓語「申す」來壓低自己，所以「田中と申します」才對。「おっしゃる」是「言う」的尊敬語，用在自己身上等於抬高自己，方向完全顛倒；「なさる」「ご覧になる」也是尊敬語，且詞義（做、看）根本對不上。',
      explanationEn:
        'When introducing yourself to an outside party, you lower yourself with 「申す」, the humble form of 「言う」, so 「田中と申します」 is correct. 「おっしゃる」 is the honorific form of 「言う」, and using it about yourself would elevate yourself — exactly backwards; 「なさる」 and 「ご覧になる」 are also honorifics, and their meanings ("do" and "look") do not even match.',
    },
    {
      kind: 'choice',
      id: 'biz-keigo-002',
      stem: '社長は明日の朝、大阪へ（　）そうです。',
      options: ['いらっしゃる', '伺う', '参る', '拝見する'],
      answerIndex: 0,
      explanation:
        '句子的主語是社長，動作要用尊敬語抬高，「行く」的尊敬語是「いらっしゃる」。「伺う」和「参る」都是「行く」的謙讓語，只能用在自己或自己人身上，套在社長的動作上是失禮的誤用；「拝見する」是「見る」的謙讓語，連詞義都不對。',
      explanationEn:
        'The subject is the company president, so his action takes an honorific: the respectful form of 「行く」 is 「いらっしゃる」. 「伺う」 and 「参る」 are both humble forms of 「行く」, usable only for yourself or your own side — applying them to the president is a rude misuse; 「拝見する」 is the humble form of 「見る」, so even its meaning is wrong.',
    },
    {
      kind: 'choice',
      id: 'biz-keigo-003',
      stem: '部長「この資料、明日までにまとめておいて。」あなた「（　）。」',
      options: ['承知しました', '了解しました', 'ご苦労さまです', 'うん、わかった'],
      answerIndex: 0,
      explanation:
        '接受上司指示時，最穩的回覆是「承知しました」（或「かしこまりました」）。「了解しました」被許多人視為對同事、晚輩的用語，對上司易失禮；「ご苦労さまです」是上位者慰勞下位者的話，對部長說是經典地雷；「うん、わかった」是常體，職場對上司不可用。',
      explanationEn:
        'The safest reply when accepting a superior\'s instruction is 「承知しました」 (or 「かしこまりました」). 「了解しました」 is widely regarded as appropriate only toward peers or juniors and can offend a boss; 「ご苦労さまです」 is what a superior says to appreciate a subordinate\'s work, so saying it to your department head is a classic blunder; 「うん、わかった」 is plain casual style and unusable toward a boss at work.',
    },
    {
      kind: 'choice',
      id: 'biz-keigo-004',
      stem: '（取引先へのメールで）お送りいただいた企画書を（　）。大変参考になりました。',
      options: ['拝見しました', 'ご覧になりました', '拝見されました', 'お見しました'],
      answerIndex: 0,
      explanation:
        '看企劃書的人是自己，要用「見る」的謙讓語「拝見する」壓低自己的動作。「ご覧になりました」是尊敬語，用在自己身上變成自抬身價；「拝見されました」是在謙讓語上再疊尊敬助動詞「れる」的常見誤用，方向混亂；「お見しました」則根本不成詞。',
      explanationEn:
        'You are the one who read the proposal, so your own action takes the humble 「拝見する」 (humble form of "to see"). 「ご覧になりました」 is honorific and would raise your own status; 「拝見されました」 is the common error of stacking the honorific auxiliary れる on top of a humble verb, muddling the direction of respect; and 「お見しました」 is simply not a word.',
    },
    {
      kind: 'order',
      id: 'biz-keigo-005',
      before: '部長が',
      after: 'ました。',
      segments: ['お書きに', 'なった', '報告書を', '拝見し'],
      starIndex: 1,
      explanation:
        '正解語序是「部長がお書きになった報告書を拝見しました」。寫報告書的是部長，用萬用尊敬語句型「お書きになる」抬高對方；看的人是自己，用謙讓語「拝見する」壓低自己，一句話裡完成尊敬與謙讓的分工。「お書きに」後面只能接「なった」，修飾「報告書を」，最後接動詞「拝見し」，語序唯一。',
      explanationEn:
        'The correct order is 「部長がお書きになった報告書を拝見しました」 (I read the report the department head wrote). The writer is the boss, so the all-purpose honorific 「お書きになる」 elevates him; the reader is you, so the humble 「拝見する」 lowers yourself — one sentence dividing respect and humility correctly. 「お書きに」 can only be followed by 「なった」, which modifies 「報告書を」, and the verb 「拝見し」 comes last; the order is unique.',
    },
    {
      kind: 'order',
      id: 'biz-keigo-006',
      before: '社長が',
      after: 'ました。',
      segments: ['召し上がった', 'お菓子を', '私も', 'いただき'],
      starIndex: 2,
      explanation:
        '正解語序是「社長が召し上がったお菓子を私もいただきました」。吃的動作屬於社長時用尊敬語「召し上がる」，屬於自己時用謙讓語「いただく」，同一個「吃」依主語切換說法。「社長が召し上がった」是修飾「お菓子」的連體修飾節，之後主語換成「私も」，句尾接「いただき」＋「ました」，其他排列會造成主語衝突而不通。',
      explanationEn:
        'The correct order is 「社長が召し上がったお菓子を私もいただきました」 (I too ate the sweets the president had eaten). The same verb "eat" switches by subject: honorific 「召し上がる」 for the president, humble 「いただく」 for yourself. 「社長が召し上がった」 is a relative clause modifying 「お菓子」; the subject then changes to 「私も」, and the sentence closes with 「いただき」+「ました」. Any other arrangement creates a subject clash and breaks down.',
    },
  ],
}
