import type { JlptQuestion } from '../../types'

export const questions: JlptQuestion[] = [
  {
    id: 'n3-listening-kadai-001',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で女の人と男の人が話しています。' },
      { speaker: '女', text: '田中くん、午後の会議の資料、もうコピーした？' },
      { speaker: '男', text: 'いえ、まだです。今からコピーしようと思っていたところです。' },
      { speaker: '女', text: 'あ、ちょっと待って。さっき部長から、グラフのデータが古いって連絡があったの。' },
      { speaker: '男', text: 'えっ、そうなんですか。じゃあ、先にデータを直します。' },
      { speaker: '女', text: 'うん、お願い。直したら私がチェックするから、コピーはその後でいいよ。' },
      { speaker: '男', text: 'わかりました。会議室の準備はどうしましょうか。' },
      { speaker: '女', text: '会議室は鈴木さんに頼んであるから、大丈夫。' },
      { speaker: '男', text: 'はい、では、すぐに直します。' },
    ],
    question: '男の人はこのあとまず何をしますか。',
    options: ['資料のデータを直す', '資料をコピーする', '会議室の準備をする', '部長に連絡する'],
    answerIndex: 0,
    explanation:
      '部長指出圖表資料太舊，女の人要男の人先修正，他最後也說「すぐに直します」，所以第一件事是修改資料。影印雖是他原本要做的，但被「コピーはその後でいいよ」改到修正並檢查之後，順序不對；會議室已經「鈴木さんに頼んである」（拜託給鈴木了），不用他做；聯絡部長對話中沒有要求。',
    explanationEn:
      'The department head reported that the graph data is outdated, the woman asks him to fix it first, and he ends with 「すぐに直します」, so correcting the data comes first. Copying was his original plan, but 「コピーはその後でいいよ」 pushes it to after the fix and her check; the meeting room has already been delegated with 「鈴木さんに頼んである」; and contacting the department head is never requested in the conversation.',
  },
  {
    id: 'n3-listening-kadai-002',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '大学で男の学生と女の学生が話しています。' },
      { speaker: '男', text: '来週のゼミの発表、準備どう？僕はまだ全然なんだけど。' },
      { speaker: '女', text: '私はアンケートの結果をまとめてるところ。テーマはもう先生に見せた？' },
      { speaker: '男', text: 'あ、まだ。メールで送ればいいかな。' },
      { speaker: '女', text: 'メールじゃなくて、直接研究室に持って行ったほうがいいよ。先生、メールはあまり見ないから。' },
      { speaker: '男', text: 'そっか。じゃあ、今日の午後、研究室に行ってくるよ。' },
      { speaker: '女', text: 'うん。スライドはテーマがオーケーになってから作ったほうがいいよ。' },
      { speaker: '男', text: 'わかった。スライドは週末に作ることにする。' },
    ],
    question: '男の学生はこのあとまず何をしますか。',
    options: [
      '先生の研究室にテーマを持って行く',
      '先生にメールでテーマを送る',
      '発表のスライドを作る',
      'アンケートの結果をまとめる',
    ],
    answerIndex: 0,
    explanation:
      '男學生說「今日の午後、研究室に行ってくるよ」，所以最先做的是把題目直接拿去老師的研究室。寄電子郵件是他自己的提案，被女學生用「メールじゃなくて」明確更正；做簡報被提醒要等題目通過之後，他也決定「週末に作る」，順序在後；整理問卷結果是女學生正在做的事，不是他的課題。',
    explanationEn:
      'The male student says 「今日の午後、研究室に行ってくるよ」, so his first task is taking the topic directly to the professor\'s office. Emailing it was his own idea, but the female student explicitly corrects it with 「メールじゃなくて」 because the professor rarely checks email; making slides should wait until the topic is approved, and he decides to do it on the weekend; and compiling the survey results is what the female student is working on, not his job.',
  },
  {
    id: 'n3-listening-kadai-003',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '家で男の人と女の人が引っ越しについて話しています。' },
      { speaker: '女', text: 'ねえ、引っ越しまであと一週間だよ。段ボール、足りる？' },
      { speaker: '男', text: 'うーん、あと十枚ぐらい必要かも。スーパーでもらってこようか。' },
      { speaker: '女', text: 'それより先に、市役所に転出届を出してきてくれない？平日しかやってないから。' },
      { speaker: '男', text: 'あ、そうだった。今日は金曜日だから、今日中に行かないとね。' },
      { speaker: '女', text: 'うん。段ボールは週末でも間に合うでしょ。' },
      { speaker: '男', text: 'わかった。ついでに電気の解約もしておこうか。' },
      { speaker: '女', text: '電気はネットで私がやっておくから、いいよ。' },
      { speaker: '男', text: '了解。じゃあ、行ってきます。' },
    ],
    question: '男の人はこのあとまず何をしますか。',
    options: [
      '市役所に転出届を出しに行く',
      'スーパーで段ボールをもらってくる',
      '電気の解約をする',
      '引っ越しの荷物を運ぶ',
    ],
    answerIndex: 0,
    explanation:
      '女の人說「それより先に、市役所に転出届を出してきて」，市公所只有平日辦公、今天又是週五，所以男の人第一件事是去市公所辦遷出登記。拿紙箱是他原本的提議，但被「それより先に」壓到後面，且「週末でも間に合う」；解約電力被女の人以「私がやっておくから、いいよ」接手，不用他做；搬行李對話中沒提到。',
    explanationEn:
      'The woman says 「それより先に、市役所に転出届を出してきてくれない？」 — the city office is only open on weekdays and today is Friday — so his first task is filing the move-out notification at the city office. Getting boxes was his own suggestion, but it is pushed back by 「それより先に」 and the boxes 「週末でも間に合う」; canceling the electricity is taken over by the woman with 「私がやっておくから、いいよ」; and moving the luggage is never mentioned in the conversation.',
  },
  {
    id: 'n3-listening-kadai-004',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で男の人と女の人が出張について話しています。' },
      { speaker: '男', text: '佐藤さん、来週の大阪出張の新幹線、もう予約した？' },
      { speaker: '女', text: 'それが、まだなんです。先にホテルを取ろうと思って、調べていたんですが。' },
      { speaker: '男', text: 'ホテルは会社が契約しているところがあるから、総務に頼めばすぐ取れるよ。' },
      { speaker: '女', text: 'あ、そうなんですか。知りませんでした。' },
      { speaker: '男', text: 'それより、新幹線は早く予約しないと、朝の便はすぐいっぱいになるよ。' },
      { speaker: '女', text: 'わかりました。じゃあ、すぐ予約します。' },
      { speaker: '男', text: 'うん。総務への依頼はその後でいいから。' },
    ],
    question: '女の人はこのあとまず何をしますか。',
    options: ['新幹線を予約する', '自分でホテルを探して予約する', '総務にホテルの予約を頼む', '出張の報告書を書く'],
    answerIndex: 0,
    explanation:
      '男の人提醒新幹線早上的班次很快就會客滿，女の人回答「じゃあ、すぐ予約します」，所以最先做的是訂新幹線。自己查飯店是她原本在做的事，但被更正為「總務に頼めばすぐ取れる」，不必自己訂；而拜託總務這件事又被「その後でいいから」排到訂新幹線之後，順序不對；出差報告對話中完全沒提到。',
    explanationEn:
      'The man warns that morning bullet train seats fill up fast, and the woman replies 「じゃあ、すぐ予約します」, so booking the Shinkansen comes first. Searching for a hotel herself is what she had been doing, but she is corrected: the company has a contracted hotel and general affairs can arrange it; that request in turn is deferred with 「その後でいいから」 until after the train is booked; and a business trip report is never mentioned at all.',
  },
  {
    id: 'n3-listening-kadai-005',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '高校で男の学生と女の学生が文化祭の準備をしています。' },
      { speaker: '女', text: '焼きそばの材料、そろそろ買いに行かなくちゃ。田中くん、一緒に行ける？' },
      { speaker: '男', text: 'いいよ。でも、その前に先生に買い物の許可をもらわないといけないんじゃない？' },
      { speaker: '女', text: 'あ、それなら私が昨日もらっておいたから、大丈夫。' },
      { speaker: '男', text: 'さすが。じゃあ、看板作りはどうする？' },
      { speaker: '女', text: '看板は絵が上手な山田さんたちに任せてあるから、心配しなくていいよ。' },
      { speaker: '男', text: 'わかった。あ、財布を教室に置いてきちゃった。先に取ってくるよ。' },
      { speaker: '女', text: 'じゃあ、昇降口で待ってるね。' },
    ],
    question: '男の学生はこのあとまず何をしますか。',
    options: [
      '教室に財布を取りに行く',
      '先生に買い物の許可をもらいに行く',
      '看板を作る',
      '焼きそばの材料を買いに行く',
    ],
    answerIndex: 0,
    explanation:
      '男學生發現「財布を教室に置いてきちゃった」，說「先に取ってくるよ」，所以第一件事是回教室拿錢包。向老師申請購物許可是他提出的疑慮，但女學生說「昨日もらっておいた」，已經辦好，不必再做；看板已經「山田さんたちに任せてある」（交給山田他們），也不用管；買材料要等他拿了錢包、兩人會合之後才去，順序在後。',
    explanationEn:
      'The male student realizes 「財布を教室に置いてきちゃった」 and says 「先に取ってくるよ」, so his first move is going back to the classroom for his wallet. Getting the teacher\'s permission was his concern, but the female student already handled it yesterday (「昨日もらっておいた」); the sign has been entrusted to Yamada\'s group (「山田さんたちに任せてある」); and shopping for ingredients happens only after he retrieves the wallet and they meet up, so it comes later.',
  },
  {
    id: 'n3-listening-kadai-006',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '病院の受付で女の人と受付の男の人が話しています。' },
      { speaker: '女', text: 'すみません、予約していないんですが、診てもらえますか。' },
      { speaker: '男', text: 'はい、大丈夫ですよ。当院は初めてですか。' },
      { speaker: '女', text: 'はい、初めてです。' },
      { speaker: '男', text: 'では、まずこちらの問診票にご記入ください。保険証はお持ちですか。' },
      { speaker: '女', text: 'あ、はい。今出します。' },
      { speaker: '男', text: '保険証は問診票を書き終わってから、一緒に出していただければ結構ですよ。' },
      { speaker: '女', text: 'わかりました。体温も測ったほうがいいですか。' },
      { speaker: '男', text: '体温は診察の前に看護師が測りますので、そのままでお待ちください。' },
    ],
    question: '女の人はこのあとまず何をしますか。',
    options: ['問診票に記入する', '保険証を受付に出す', '自分で体温を測る', '診察の予約をする'],
    answerIndex: 0,
    explanation:
      '櫃檯人員說「まずこちらの問診票にご記入ください」，所以第一件事是填寫初診單。健保卡雖然她說「今出します」想馬上拿出來，但被更正為「問診票を書き終わってから、一緒に出していただければ結構」，順序被排到填完之後；量體溫則被「看護師が測りますので、そのままでお待ちください」否定，不用自己量；掛號預約也被開頭的「大丈夫ですよ」表明不需要。',
    explanationEn:
      'The receptionist says 「まずこちらの問診票にご記入ください」, so filling out the medical questionnaire comes first. She tried to hand over her insurance card right away with 「今出します」, but is told to submit it together after finishing the form; taking her own temperature is ruled out because a nurse will do it before the examination (「そのままでお待ちください」); and making an appointment is unnecessary, as the receptionist confirmed at the start with 「大丈夫ですよ」 that she can be seen without one.',
  },
  {
    id: 'n3-listening-kadai-007',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で女の人が新人の男の人と話しています。' },
      { speaker: '女', text: '山本くん、午前中に頼んだ商品リストの入力、終わった？' },
      { speaker: '男', text: 'はい、さっき終わりました。次は何をしましょうか。' },
      { speaker: '女', text: 'じゃあ、倉庫の在庫チェックをお願いしたいんだけど、その前に昼休みを取っちゃって。もう一時過ぎてるよ。' },
      { speaker: '男', text: 'でも、在庫チェックは急ぎじゃないんですか。' },
      { speaker: '女', text: '急ぎじゃないから大丈夫。三時までに終わればいいの。休憩も仕事のうちだよ。' },
      { speaker: '男', text: 'わかりました。では、お先に失礼します。' },
      { speaker: '女', text: 'うん、ゆっくりしてきて。' },
    ],
    question: '男の人はこのあとまず何をしますか。',
    options: ['昼休みを取る', '倉庫の在庫チェックをする', '商品リストの入力を続ける', '午後の会議の準備をする'],
    answerIndex: 0,
    explanation:
      '前輩說「その前に昼休みを取っちゃって」，要他在盤點之前先去吃午休，男の人也回答「お先に失礼します」，所以最先做的是休息。倉庫盤點雖然是接下來的工作，但被明確排在午休「その前に」之後，而且「三時までに終わればいい」不趕，順序不對；商品清單輸入他已回報「さっき終わりました」，是完成的事；會議準備對話中沒有出現。',
    explanationEn:
      'The senior colleague tells him 「その前に昼休みを取っちゃって」 — take lunch before the inventory check — and he answers 「お先に失礼します」, so taking his lunch break comes first. The warehouse inventory check is his next job, but it is explicitly placed after the break and is not urgent since 「三時までに終わればいい」; the product list entry is already done, as he reported 「さっき終わりました」; and meeting preparation never appears in the conversation.',
  },
  {
    id: 'n3-listening-kadai-008',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '電話で男の人と女の人が明日の旅行について話しています。' },
      { speaker: '男', text: 'もしもし、明日の集合、朝八時に駅の改札でいいんだよね。' },
      { speaker: '女', text: 'あ、ごめん、八時じゃなくて七時半に変わったの。特急の時間が早くなったから。' },
      { speaker: '男', text: 'えっ、七時半か。じゃあ、今日はもう寝ないと。' },
      { speaker: '女', text: 'その前に、ホテルの予約確認のメール、印刷してきてくれない？チェックインの時に見せるんだって。' },
      { speaker: '男', text: 'わかった。今からすぐ印刷するよ。' },
      { speaker: '女', text: 'お願いね。お土産のリストは私が作っておくから。' },
      { speaker: '男', text: '了解。じゃあ、また明日。' },
    ],
    question: '男の人はこのあとまず何をしますか。',
    options: ['ホテルの予約確認のメールを印刷する', 'すぐに寝る', 'お土産のリストを作る', '八時に駅へ行く'],
    answerIndex: 0,
    explanation:
      '女の人拜託他「その前に、ホテルの予約確認のメール、印刷してきて」，男の人回答「今からすぐ印刷するよ」，所以第一件事是印飯店的預約確認信。睡覺是他自己說要做的，但被「その前に」排到印完之後，順序不對；伴手禮清單被女の人以「私が作っておくから」接手；八點集合則被更正為「八時じゃなくて七時半」，時間本身就是被否定的資訊。',
    explanationEn:
      'The woman asks him 「その前に、ホテルの予約確認のメール、印刷してきてくれない？」 and he replies 「今からすぐ印刷するよ」, so printing the hotel confirmation email comes first. Going to bed was his own plan, but 「その前に」 puts it after the printing; the souvenir list is taken over by the woman with 「私が作っておくから」; and meeting at eight is corrected to seven thirty with 「八時じゃなくて七時半」, so that time itself is rejected information.',
  },
  {
    id: 'n3-listening-kadai-009',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '大学の図書館で女の学生と男の学生が話しています。' },
      { speaker: '女', text: 'レポートに使う本、見つかった？' },
      { speaker: '男', text: 'それが、借りたい本が貸出中なんだ。来週の月曜日に返ってくるんだって。' },
      { speaker: '女', text: '予約はした？' },
      { speaker: '男', text: 'うん、さっきカウンターでしてきた。でも、締め切りは金曜日だから、待ってたら間に合わないよ。' },
      { speaker: '女', text: 'じゃあ、同じテーマの論文をデータベースで探したら？パソコン室で無料で読めるよ。' },
      { speaker: '男', text: 'そうだね、そうするよ。使い方、教えてくれない？' },
      { speaker: '女', text: 'いいよ。私はこの本を借りてから行くから、先にパソコン室に行ってて。' },
      { speaker: '男', text: 'わかった。じゃあ、先に行ってるね。' },
    ],
    question: '男の学生はこのあとまず何をしますか。',
    options: ['パソコン室に行く', 'カウンターで本の予約をする', '月曜日まで本が返るのを待つ', 'カウンターで本を借りる'],
    answerIndex: 0,
    explanation:
      '女學生建議用資料庫查同主題的論文，並要他「先にパソコン室に行ってて」，男學生也說「先に行ってるね」，所以最先做的是去電腦室。預約書他已經「さっきカウンターでしてきた」，是做完的事；等到週一書還回來，被他自己以「待ってたら間に合わないよ」否定，因為截止日是週五；到櫃檯借書的是女學生（「私はこの本を借りてから行く」），不是他。',
    explanationEn:
      'The female student suggests searching the database for papers on the same theme and tells him 「先にパソコン室に行ってて」; he answers 「先に行ってるね」, so going to the computer room comes first. Reserving the book is already done — 「さっきカウンターでしてきた」; waiting until Monday for the book\'s return is rejected by his own words 「待ってたら間に合わないよ」 since the deadline is Friday; and it is the female student who will borrow a book at the counter (「私はこの本を借りてから行く」), not him.',
  },
  {
    id: 'n3-listening-kadai-010',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で女の人と男の人が飲み会について話しています。' },
      { speaker: '女', text: '木村くん、金曜日の飲み会の店、もう決めた？' },
      { speaker: '男', text: 'はい、駅前の居酒屋を予約しようと思っています。' },
      { speaker: '女', text: 'あそこ、先月行ったばかりだよ。違う店のほうがいいんじゃない？' },
      { speaker: '男', text: 'そうですか。じゃあ、新しくできたイタリアンの店はどうでしょう。' },
      { speaker: '女', text: 'いいね。でも予約の前に、まず参加する人の数を確認して。アレルギーがある人もいるかもしれないし。' },
      { speaker: '男', text: 'わかりました。今からみんなにメールします。' },
      { speaker: '女', text: '返事が集まったら、店に電話してね。' },
      { speaker: '男', text: 'はい、そうします。' },
    ],
    question: '男の人はこのあとまず何をしますか。',
    options: [
      '参加する人にメールで人数を確認する',
      'イタリアンの店を予約する',
      '駅前の居酒屋を予約する',
      '店に電話して料理を注文する',
    ],
    answerIndex: 0,
    explanation:
      '女の人指示「予約の前に、まず参加する人の数を確認して」，男の人回答「今からみんなにメールします」，所以第一件事是寄信確認人數。訂義式餐廳雖然已被同意，但被排在「予約の前に」之後，要等回信收齊才打電話，順序不對；站前的居酒屋則被「先月行ったばかりだよ」委婉否定而換店；打電話點餐更是要在最後才做。',
    explanationEn:
      'The woman instructs 「予約の前に、まず参加する人の数を確認して」, and the man responds 「今からみんなにメールします」, so emailing everyone to confirm the headcount comes first. Booking the Italian restaurant is approved but placed after the count with 「予約の前に」, and he should phone the restaurant only once the replies are in; the izakaya by the station is gently vetoed with 「先月行ったばかりだよ」, prompting a change of venue; and calling to order food would come last of all.',
  },
  {
    id: 'n3-listening-kadai-011',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で女の人と男の人が新しい社員の席の準備について話しています。' },
      { speaker: '女', text: '来週の月曜日から、新しい人がうちの課に来るの。悪いけど、席の準備をお願いできる？' },
      { speaker: '男', text: 'はい。じゃあ、まず空いている机を運びます。' },
      { speaker: '女', text: '机はいいのよ。業者さんが明日、新しいのを運んでくれることになってるから。' },
      { speaker: '男', text: 'わかりました。パソコンはどうしますか。' },
      { speaker: '女', text: 'それが一番急ぎなの。総務に申請書を出さないと、届くまで一週間かかるのよ。今日中にお願い。' },
      { speaker: '男', text: 'はい、すぐ書いて出します。名前の札はどうしましょうか。' },
      { speaker: '女', text: '名札は私が作っておくから、大丈夫よ。' },
    ],
    question: '男の人はこのあとまず何をしますか。',
    options: ['総務にパソコンの申請書を出す', '空いている机を運ぶ', '新しい社員の名札を作る', '業者に机を注文する'],
    answerIndex: 0,
    explanation:
      '女の人說電腦最急，「総務に申請書を出さないと、届くまで一週間かかる」而且「今日中にお願い」，男の人也回答「すぐ書いて出します」，所以第一件事是向總務提出電腦的申請書。搬桌子是他自己的提議，被「業者さんが明日運んでくれる」否定，不用他做；名牌由女の人以「私が作っておくから」接手；向業者訂桌子在對話中沒有要求他做。',
    explanationEn:
      'The woman says the computer is the most urgent item — without submitting the request form to general affairs it takes a week to arrive, and she asks for it 「今日中にお願い」; the man replies 「すぐ書いて出します」, so submitting the PC request form comes first. Moving a spare desk was his own idea, rejected because 「業者さんが明日運んでくれる」; the name plate is taken over by the woman with 「私が作っておくから」; and ordering a desk from the vendor is never asked of him.',
  },
  {
    id: 'n3-listening-kadai-012',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '薬局で男の人と薬剤師の女の人が話しています。' },
      { speaker: '男', text: 'すみません、この処方箋の薬、お願いします。' },
      { speaker: '女', text: 'はい、お預かりします。……申し訳ありません。こちらの薬、今、在庫が一つ足りなくて、そろうのが夕方になってしまうんです。' },
      { speaker: '男', text: '夕方ですか。うーん、これから仕事なので、また来るのは難しいなあ。' },
      { speaker: '女', text: 'それでしたら、ご自宅にお届けすることもできますよ。配達は無料です。' },
      { speaker: '男', text: '助かります。じゃあ、それでお願いします。' },
      { speaker: '女', text: 'では、こちらの用紙にご住所とお電話番号をお書きください。お届けは明日の午前中になります。' },
      { speaker: '男', text: 'わかりました。今書きますね。' },
    ],
    question: '男の人はこのあとまず何をしますか。',
    options: ['配達の用紙に住所と電話番号を書く', '夕方、もう一度薬局に来る', '明日の午前中に薬を取りに来る', '病院へ処方箋をもらいに行く'],
    answerIndex: 0,
    explanation:
      '藥師提出可以免費宅配，並請他「こちらの用紙にご住所とお電話番号をお書きください」，男の人回答「今書きますね」，所以第一件事是在配送單上填住址和電話。傍晚再來一趟被他自己以「また来るのは難しい」婉拒，才改成宅配；藥是明天上午「送到家」，不必自己去拿；處方箋他已經交給藥局了，不需要再回醫院拿。',
    explanationEn:
      'The pharmacist offers free home delivery and asks him to fill in the form: 「こちらの用紙にご住所とお電話番号をお書きください」; he answers 「今書きますね」, so writing his address and phone number on the delivery form comes first. Coming back in the evening is rejected by his own words 「また来るのは難しい」, which is why delivery was chosen; the medicine will be delivered to his home tomorrow morning, so he does not need to pick it up; and he has already handed over the prescription, so returning to the hospital is unnecessary.',
  },
  {
    id: 'n3-listening-kadai-013',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '電話で男の人と宅配便の会社の女の人が話しています。' },
      { speaker: '男', text: 'すみません、留守の間に来た荷物の再配達をお願いしたいんですが。' },
      { speaker: '女', text: 'かしこまりました。それでは、不在票の番号をお願いします。' },
      { speaker: '男', text: 'えっと、1234の567です。今日の夜、届けてもらえますか。' },
      { speaker: '女', text: '申し訳ありません。本日の夜はもういっぱいでして、明日の午前中ならお届けできます。' },
      { speaker: '男', text: '明日の午前は出かけるんです。あのう、駅前のコンビニで受け取ることはできますか。' },
      { speaker: '女', text: 'できますよ。ただ、その場合は、先にスマホのアプリで受け取りの手続きをしていただく必要があります。' },
      { speaker: '男', text: 'わかりました。じゃあ、すぐやってみます。' },
    ],
    question: '男の人はこのあとまず何をしますか。',
    options: ['アプリで受け取りの手続きをする', 'コンビニへ荷物を取りに行く', '明日の午前中に家で荷物を待つ', '今日の夜、もう一度電話をかける'],
    answerIndex: 0,
    explanation:
      '客服說明超商取貨要「先にスマホのアプリで受け取りの手続きをしていただく必要があります」，男の人回答「すぐやってみます」，所以第一件事是用手機的App辦理取貨手續。去超商拿貨要等手續完成、貨送到之後，順序在後；明天上午在家等被他自己以「出かけるんです」否定；今晚配送已被「本日の夜はもういっぱい」回絕，再打一次電話也沒有用。',
    explanationEn:
      'The operator explains that convenience-store pickup requires completing the procedure first: 「先にスマホのアプリで受け取りの手続きをしていただく必要があります」, and the man replies 「すぐやってみます」, so doing the pickup procedure on the app comes first. Going to the convenience store happens only after the procedure is done and the parcel arrives; waiting at home tomorrow morning is ruled out by his own 「出かけるんです」; and tonight is already fully booked (「本日の夜はもういっぱい」), so calling again would not help.',
  },
  {
    id: 'n3-listening-kadai-014',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '公民館で女の人と男の人が町内会の夏祭りの準備について話しています。' },
      { speaker: '男', text: 'お祭りまであと三日ですね。ポスター、そろそろ貼りに行きましょうか。' },
      { speaker: '女', text: 'ポスターはまだ印刷屋さんから届いてないの。夕方に届くから、貼るのは明日にしましょう。' },
      { speaker: '男', text: 'わかりました。じゃあ、会場のテントを立てますか。' },
      { speaker: '女', text: 'テントは当日の朝、若い人たちがやってくれることになってるわ。それより、商店街の田中さんのお店に、椅子を五十脚借りに行ってくれない？' },
      { speaker: '男', text: '五十脚ですか。運ぶのが大変そうですね。' },
      { speaker: '女', text: '軽トラックは佐藤さんが出してくれるって。もうお店の前で待ってるはずよ。' },
      { speaker: '男', text: 'わかりました。じゃあ、すぐ行ってきます。' },
    ],
    question: '男の人はこのあとまず何をしますか。',
    options: ['商店街へ椅子を借りに行く', 'ポスターを貼りに行く', '会場にテントを立てる', '軽トラックを借りに行く'],
    answerIndex: 0,
    explanation:
      '女の人說「それより、商店街の田中さんのお店に、椅子を五十脚借りに行ってくれない？」，還提到佐藤先生已在店門口等，男の人回答「すぐ行ってきます」，所以最先做的是去商店街借椅子。貼海報因「まだ印刷屋さんから届いてない」被延到明天；搭帳篷是活動當天早上由年輕人負責的事；小貨車由佐藤先生出借，不用他去借。',
    explanationEn:
      'The woman says 「それより、商店街の田中さんのお店に、椅子を五十脚借りに行ってくれない？」 and adds that Sato is already waiting in front of the shop with a light truck; the man answers 「すぐ行ってきます」, so borrowing the chairs from the shopping street comes first. Putting up posters is postponed to tomorrow because they 「まだ印刷屋さんから届いてない」; the tents will be set up by the young members on the morning of the festival; and the light truck is provided by Sato, so he does not need to arrange one.',
  },
  {
    id: 'n3-listening-kadai-015',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '会社で男の人と女の人が名刺について話しています。' },
      { speaker: '男', text: '佐藤さん、名刺があと十枚ぐらいしかないんです。注文したいんですが。' },
      { speaker: '女', text: '注文は私が課の分をまとめてシステムでやるから、大丈夫よ。' },
      { speaker: '男', text: 'よかった。じゃあ、お願いします。' },
      { speaker: '女', text: 'あ、でも先月、部署の名前が変わったでしょう。その前に、新しい名刺のデータが正しいかどうか、確認してくれる？' },
      { speaker: '男', text: 'わかりました。どこで確認すればいいですか。' },
      { speaker: '女', text: '総務のページに見本があるから、それを見て。もし間違いがあったら、総務に連絡してね。' },
      { speaker: '男', text: 'はい、今から見てみます。' },
    ],
    question: '男の人はこのあとまず何をしますか。',
    options: ['新しい名刺のデータを確認する', 'システムで名刺を注文する', '総務に電話で連絡する', '名刺を百枚印刷する'],
    answerIndex: 0,
    explanation:
      '女の人提醒上個月部門改了名稱，要他「その前に、新しい名刺のデータが正しいかどうか、確認してくれる？」，男の人回答「今から見てみます」，所以第一件事是核對新名片的資料。用系統下訂被女の人以「注文は私がまとめてやる」接手，不用他做；聯絡總務是「もし間違いがあったら」的條件動作，不一定會發生；印一百張名片在對話中根本沒出現。',
    explanationEn:
      'The woman reminds him that the department name changed last month and asks 「その前に、新しい名刺のデータが正しいかどうか、確認してくれる？」; he replies 「今から見てみます」, so checking the new business-card data comes first. Ordering through the system is taken over by the woman with 「注文は私がまとめてやる」; contacting general affairs is conditional — only 「もし間違いがあったら」; and printing a hundred cards never appears in the conversation.',
  },
  {
    id: 'n3-listening-kadai-016',
    kind: 'listening',
    script: [
      { speaker: '旁白', text: '病院で男の人が健康診断の受付の女の人と話しています。' },
      { speaker: '男', text: 'すみません、九時から健康診断を予約している田中です。' },
      { speaker: '女', text: '田中様ですね。こちらが検査の紙です。まず、あちらの部屋で検査用の服に着替えてください。' },
      { speaker: '男', text: 'はい。あのう、血液検査は最初ですか。朝から何も食べていないので、早く終わらせたいんですが。' },
      { speaker: '女', text: '血液検査は今、込んでいますので、着替えたら、先にレントゲンにご案内しますね。' },
      { speaker: '男', text: 'わかりました。荷物はどうすればいいですか。' },
      { speaker: '女', text: '着替えの部屋のロッカーに入れて、かぎをかけてください。' },
      { speaker: '男', text: 'はい、ありがとうございます。' },
    ],
    question: '男の人はこのあとまず何をしますか。',
    options: ['検査用の服に着替える', '血液検査を受ける', 'レントゲンを受ける', '朝ご飯を食べに行く'],
    answerIndex: 0,
    explanation:
      '櫃檯人員指示「まず、あちらの部屋で検査用の服に着替えてください」，所以第一件事是去更衣室換上檢查服。抽血是他想先做完的項目，但被「今、込んでいますので」婉拒；照X光被安排在「着替えたら」之後，順序不對；他說「朝から何も食べていない」是抽血前必須空腹，並不是要去吃早餐。',
    explanationEn:
      'The receptionist instructs him: 「まず、あちらの部屋で検査用の服に着替えてください」, so changing into the examination clothes comes first. The blood test is what he hoped to finish early, but it is deferred because it is crowded (「今、込んでいますので」); the X-ray is scheduled for after he changes (「着替えたら」), so its order is wrong; and 「朝から何も食べていない」 means he is fasting for the blood test, not that he is going off to eat breakfast.',
  },
]
